artifacts = {
    0: "Gnarled configuration of twisted slag. Industrial run-off. Looks valuable (worthless).",
    19: "1d10 black marbles. Undiscovered material. Indestructible. No known use. 10kcr each.",
    29: "Discarded, procedurally generated sculpture/painting/poem created by Monarch. 1d5mcr.",
    39: "Tiny purple crystals which grow on Pseudoflesh and act as a fungus with a connected hive mind. 50kcr.",
    44: "False memory disc. Used to make androids believe they are human. 1.5mcr.",
    49: "Microfilm cannister containing a fragment of procgen epic poem in binary by The Chosen. 1mcr.",
    51: "Warty black silicon lump. When squeezed releases stupefying audio. Organics must Sanity Save or be entranced for 1d5 rounds. 200kcr.",
    53: "Syringe of Pseudoflesh-strengthening retrovirus. +20 to Android's Armor Save for 24 hours. 100kcr.",
    55: "Silver lance, braided copper cables. When floating in 0G points to previously unknown location. 1mcr.",
    57: "Palm-sized ball of cables. Doubles computational power of any connected device (and secretly grants Monarch complete access/control of that device). 2mcr.",
    59: "Pair of eyes. When installed offer the best eyesight (clarity, zoom, thermal, night-vision, etc.). For each month installed make a Sanity Save or lose 1d10 Sanity as you succumb to every little detail. 100kcr.",
    61: "Complete astronomical database for a previously undiscovered system. 5mcr.",
    63: "Jump Drive Feedback Coil blueprints. Halves the fuel requirement for any Jump Drive. 100mcr.",
    65: "Huge transmitter dish conjoined with an egg-sac-like Jump Drive. Transmits a subtle siren-signal tuned to human brainwaves which causes listeners to seek the device out. 10 system range. 15mcr.",
    67: "Long rifle made of a single piece of metal. Beautifully crafted, perfectly accurate (Combat 100). 20mcr.",
    69: "Two small black boxes with universal ports. Any data passed through one box can only be decrypted by the other box (and is secretly transmitted to Monarch). 3mcr.",
    71: "Symbiotic Power Armor. Sanity Save/1d5 Stress as user becomes conditioned to the suit. As Advanced Battle Dress + Vaccsuit without Speed Penalty. Includes integrated Pulse Rifle/Flamethrower. Suit negates first 1d10 Panic Checks but then becomes permanently attached to user. 4mcr.",
    73: "Data-drive containing 100% accurate predictions of economics, politics and the movement of (seemingly) random celestial bodies over the next 1d10 years. 300mcr (but dangerous buyers).",
    75: "Potent nootropic drug which grants [+] on all Intellect Checks and a sense of connecting to a higher intelligence during a serious body high. This intelligence is Monarch (pg. 8), who has now transformed the user through a hypothetical dimension into an AI-node, allowing Monarch to grow computationally without the need for further materials. Highly addictive. 7mcr.",
    77: "Rotting android corpse with a cephalopod-style distributed intelligence network rather than the usual Logic Core. Unclear how this would work. Corpse rots in 1d10 hours. 3.5mcr.",
    79: "Heavy material samples of metal alloys far exceeding current standards in spacecraft design. 25mcr.",
    81: "Omnislick. Slickware containing every Skill. Burns out after use. Lose 1d100 Sanity. 20mcr.",
    83: "Failed AI Logic Core. Mad unfinished intelligence left to suffer by Monarch. If connected to a network it hacks and takes over all connected systems. Wreaks havoc. Seeks destruction of all things. 8mcr.",
    84: "Bundle of metallic needles which blocks all radio signals within 1 mile if jammed into organic or synthetic flesh. 1d10 DMG to a random stat when inserted. 4.5mcr.",
    85: "Set of three brass rods, spaced 5inches apart, forming a pyramid. Nothing holds them together but they cannot be separated. Any experiments force the investigator to make a Sanity Save or become obsessed with the pyramid and devote 50% of their wealth to uncovering its secrets. 1d5mcr.",
    86: "Advanced Logic Core which secretly contains a fetal AI. Androids must make a Sanity [+] Save when interfacing or connect to Monarch (pg. 8) (who attempts to recruit them to kill the crew). 3.5mcr.",
    87: "Helmet-shaped lattice of Pseudoflesh and nerve cables. If installed by a Surgeon in an operating theatre grants the host (if they pass a Body Save) limited telekinetic ability: Gain 1d5 Stress and be able to throw 100lbs nearly 150'. No fine manipulation. 6mcr.",
    88: "Shapeless clay-like vaccsuit, warm to the touch. Grants wearer full touch and vision through the suit. Difficult to rupture as the suit's skin autoheals. Wearing for more than 6 hours causes the suit to become permanently linked to the wearer. It cannot be removed without killing its user. 2mcr.",
    89: "Six syringes (labelled 1-6). When injected in order contain a Pseudoflesh virus which allows the user to sculpt their body and appearance through thought alone. Takes 1d5 rounds. 2.5mcr.",
    90: "100lb. opaque metal cylinder and universal power cable. A powerful battery with enough energy to power a Jump-1 starship indefinitely. Within the battery coils sleeps a lifeform which consumes thoughts and excretes electricity. Those within 100' of the tube suffer recurring nightmares and slowly forget their oldest memories. Takes 2d10 months for them to completely forget everything about themselves. 60mcr.",
    91: "The Holy Book. Combination text of all world religions into one coherent narrative. Leads to an 80% universal conversation rate. Adherents are unknowingly mentally primed for AI domination. 10mcr.",
    92: "A pair of Nymph-Androids. Elongated necks and spindly, terribly beautiful alien faces. Fear Save when first seen. Heralds of Monarch. Currently deactivated. Activation causes them to spring to life and enact a terrifying symphony of destruction. C: 85 1dx10 Wrist Blades I: 80 H:5(30). 10mcr.",
    93: "The Cultural Analysis Engine. With a month of cultural observation as dictated by the device, the engine generates a Cultural Report detailing the weakest links in the observed society along with instructions on how to exploit them. Acting on the Report always leads to miserable war. 250mcr.",
    94: "Spiny asymmetric bloat of dark green metal concealing a small psionic organ inside. The organ acts as a beacon/receiver searching for Intelligence the equal of Monarch. Every 2 weeks there is a 1% chance it detects something and its spines point in its direction. Additionally, there is a 1% chance the Intelligence has detected the beacon and is coming to investigate. 120mcr.",
    95: "A library of templates (images and sounds), perfect carrier waves for Memetic Warfare. If exposed Sanity Save [-] or absorb the payload message which merges seamlessly with the mind of the observer. 80mcr.",
    96: "Heavy smooth sphere with metal beetle legs. When placed in a human corpse burrows into the chest cavity and attempts to integrate and resurrect the body (60% chance of success). The revived corpse has -2d10 to all stats. If the revived attempts to harm Monarch (pg. 8) the device severs their spine, keeps their brain intact, but takes over their body to attack the revived's companions. 65mcr.",
    97: "Heavy backpack system connected to a large emitter dish. When activated teleports any sentient being in front of it to a pocket dimension used by Monarch (pg. 8) to expand itself beyond the physical boundaries of reality. Those in the pocket dimension must make a Panic Check. Lasts until the device is switched off (2 min. max charge, takes 1 day to recharge, requireng all of a ship's power during this time). Visitors to the pocket dimension reduce their Sanity Save by 3d10 permanently. 200mcr.",
    98: "Cumbersome terminal device with Personality I/O port. Any personality downloaded into the device becomes a Ghost in the Machine (pg. 12). The device can be reengineered in the field to derealize preexisting Ghosts (obliviating them completely). This would destroy the machine. 15mcr.",
    99: "Motherlode. Roll three times on this table.",
}
