from .dice import get_key, roll_d10


encounters_per_floor = {
    "1": {
        "name": "Floor 1: Reception & habitation",
        0: "1d10 Troubleshooters",
        3: "1d5 Forgotten Androids",
        6: "Distorted corporate muzak plays over the intercom.",
        8: "A Security Android",
        9: "A Diver",
    },
    "2": {
        "name": "Floor 2: Eden",
        0: "The Minautor",
        3: "1d5 Chosen Androids",
        6: "1d10 Fallen Androids",
        8: "Ghost in the Machine",
        9: "A Diver",
    },
    "3.1": {
        "name": "Floor 3.1: Maintenance Zone",
        0: "Waste disposal, Save or 1d6 damage",
        3: "1d10 Fallen Androids",
        6: "1d10 Security Androids",
        8: "Ghost in the Machine",
        9: "A Diver",
    },
    "3.2": {
        "name": "Floor 3.2: Skeleton Works",
        0: "A Diver",
        3: "2d10 Bee Drones (p38)",
        6: "1d10 Forgotten Androids",
        8: "1d10 Security Androids",
        9: "Ghost in the Machine",
    },
    "3.3": {
        "name": "Floor 3.3: Pseudoflesh Farms",
        0: "A Diver",
        3: "Silus makes Demands (p40)",
        6: "1d10 Pseudomilk Eels (p42)",
        8: "1d5 Stunted Androids (p41)",
        9: "A Ghost in the Machine",
    },
    "3.4": {
        "name": "Floor 3.4: Brain Construction",
        0: "A Diver",
        3: "1d5 Escaped Child Androids from [55a] seeking the Mind Thief [45e]",
        6: "The Mind Thief [45e] and 1d10 Forgotten Androids",
        8: "1d5 Android Dogs from [44d]",
        9: "Ghost in the Machine",
    },
    "3.5": {
        "name": "Floor 3.5: Dis/assembly",
        0: "A Diver",
        3: "1d10 Forgotten Androids",
        6: "1d5 Failed Androids looking to escape Disassembly",
        8: "1d10 Security Androids chasing escapees",
        9: "Ghost in the Machine",
    },
    "3.6": {
        "name": "Floor 3.6: Storage",
        0: "A Diver",
        3: "1d10 Forgotten Androids",
        6: "1d10 Escaped Androids from [49g]",
        8: "1d10 Security Androids",
        9: "Ghost in the Machine",
    },
    "3.7": {
        "name": "Floor 3.7: “Quality Assurance”",
        0: "Exact duplicates of the Crew (WIL save or 1d4 WIL dmg)",
        3: "1d5 Divers",
        6: "1d10 Security Androids",
        8: "Infiltrator Android of an NPC the crew has already met",
        9: "Ghost in the Machine",
    },
    "4": {
        "name": "Floor 4: HEL",
        0: "A Diver",
        3: "1d10 Escaped Child Androids",
        6: "1d5 former CLOUDBANK Research Scientists",
        8: "1d5 Security Androids",
        9: "Ghost in the Machine",
    },
    "5": {
        "name": "FLOOR 5: THE AI CORE",
        9: "Monarch",
    },
    "6": {
        "name": "floor 6: engineering & support",
        0: "A Diver",
        3: "1d5 Forgotten Androids",
        6: "1d5 Security Androids",
        8: "The Hunter (p57)",
        9: "1d10 Troubleshooters (p14)",
    },
}
