random_search = {
    0: "<b>Battered postcard.</b> Image is where you were born. Dated to the exact day. +1d5 Bends.",
    4: "<b>Grimy map</b> of a random floor of THE DEEP.",
    9: "<b>1d5 EMP grenades.</b> 5% chance they instead summon 1d5 Security Androids (pg. 10).",
    13: "<b>Emergency Vaccsuit repair gel.</b> Gel is dayglo green and highly reflective of IR and UV wavelengths.",
    17: "<b>Loaded revolver.</b> Each round has the name of a crew member carved into it. Crew gains +1d5 Bends.",
    21: "<b>A corpse.</b> It's a member of your crew, aged 1d10 years older than they currently are. +2d10 Bends.",
    25: "<b>Chibi-figurine datastick.</b> Contains a 5s video showing a glimpse of the Minotaur/screams. Fear Save.",
    29: "<b>Plastic bag of Pseudoflesh tongues.</b> In the presence of strong radio signals they all quiver and waggle.",
    33: "<b>Gift shop plastic toy.</b> 1 day study: hyper-detailed model of THE DEEP. Reveals all external entrances.",
    37: "<b>Small cache of microcassettes.</b> Contains breathy stalker footage of the area you're in.",
    41: "<b>Dirty, aged ID badge.</b> Belongs to next Ghost (pg. 12) encountered. Giving it to them soothes them.",
    45: "<b>Tattered remains of a book.</b> Only the author byline is legible: you wrote it. +1d10 Bends.",
    49: "<b>Plastic clamshell mirror.</b> The mirror has the word <em>ANDROID</em> etched around the outside edge like a halo.",
    55: "<b>Glass bottle.</b> Label reads: <em>ELIXIR OF FORGETFULNESS.</em> A sniff or taste confirms whisky. Half full.",
    61: "<b>2 Dead Troubleshooters (pg. 14)</b> nailed to the wall with synthetic fingers. All gear looted/useless.",
    65: "<b>Photojournalist essay materials</b> on the Divers, Troubleshooters and corruption at the Blockade.<br>Reading materials reveals you were interviewed 3 years ago. Bends Check.",
    69: "<em>2d10 PSEUDO-YUM SYNTHSTEAKS.</em> Made of Pseudoflesh. Each packet has the name of a crew<br>member written on the back. +1d5 Bends, +1d10 if eaten before reading.",
    70: "<b>A tooth.</b> It's yours. All your other teeth are accounted for. +1d5 Bends.",
    74: "<b>Scraps of poetry</b> featuring a talking dog and a genetics laboratory.",
    76: "<b>Teenager's diary.</b> Reading a few pages reveals it belongs to someone else in the crew.",
    78: "<b>Alien-truther conspiracy theory materials.</b> Reams and reams of the stuff.",
    80: "<b>Revolver</b> with one spent shell still in the cylinder.",
    82: "<b>Ammunition</b> for everyone in your party. Exactly 1 per person. The exact kind they need. Exactly.",
    84: "<b>Video Cassette.</b> Contains footage of the last dream you had. Bends Check.",
    86: "<b>Pristine map</b> of the floor you're currently on. Directions to where you're going drawn on it.",
    88: "<b>Photograph of you as a child.</b> You don't remember the event pictured. Bends Check.",
    91: "<b>Comms device.</b> When activated: a familiar voice on the other end. They're trapped in a <b>Random<br>Location (pg. 21)</b> and beg you to find them. When you find them: it's a duplicate of yourself.",
    92: "<em>“BATHSHEBA TRIUMPHANT.”</em> A paperback book you've never heard of. No one has.",
    93: "<b>Combat Shotgun.</b> “ANDROID DETECTOR” painted on the barrel. Two boxes of ammunition.",
    94: "<b>Six-pack of black spraypaint:</b> FOR EYES written on the side in yellow marker.",
    95: "<b>Map</b> to location 1d10 rooms away: Contains an Artifact (pg. 62). 50% chance of encounter.",
    96: "<b>Android head,</b> eyes dim, mouth moving near-silently. It's saying your name as it dies. +1d5 Bends.",
    97: "<b>Audio cassette.</b> Argument between you and the crew about leaving THE DEEP amid fears of Infiltrator Androids<br>being among your ranks. Gunfire. Screaming. Silence. All crew: +1d10 Bends.",
    98: "<b>Your cousin, sleeping.</b> Kitted up as a Troubleshooter. +2d10 Bends.",
    99: "A random <b>Artifact</b> (pg. 62).",
}
