# Generated by Django 4.2.4 on 2025-08-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('bounty_level', models.IntegerField(default=1)),
                ('advert', models.TextField(blank=True)),
                ('briefing', models.TextField(blank=True)),
                ('warden_info', models.TextField(blank=True)),
            ],
        ),
    ]
