# Generated by Django 4.2.4 on 2025-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='last_known_location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bounty',
            name='point_of_collection',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bounty',
            name='wanted',
            field=models.CharField(choices=[(1, 'Alive'), (2, 'Dead or Alive'), (3, 'Dead')], default=1, max_length=1),
        ),
    ]
