# Generated by Django 4.2.4 on 2025-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0002_bounty_last_known_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='crime',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
