# Generated by Django 4.2.4 on 2025-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0003_bounty_crime_alter_bounty_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='wanted',
            field=models.CharField(choices=[('1', 'Alive'), ('2', 'Dead or Alive'), ('3', 'Dead')], default='1', max_length=1),
        ),
    ]
