# Generated by Django 4.2.4 on 2025-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0004_alter_bounty_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='bonus',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bounty',
            name='client',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bounty',
            name='known_associates',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
