# Generated by Django 4.2.4 on 2025-08-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0005_bounty_bonus_bounty_client_bounty_known_associates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='wanted',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
