# Generated by Django 4.2.4 on 2025-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0006_alter_bounty_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
