# Generated by Django 4.2.4 on 2025-08-15 12:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0007_bounty_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='briefing',
            field=tinymce.models.HTMLField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='warden_info',
            field=tinymce.models.HTMLField(blank=True, max_length=10000),
        ),
    ]
