# Generated by Django 4.2.4 on 2025-08-26 14:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0008_alter_bounty_briefing_alter_bounty_warden_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='warden_info',
            field=tinymce.models.HTMLField(blank=True, max_length=20000),
        ),
    ]
