bastion_spark_table = {
    "spark_1": [
        "Pastry",
        "High-rise",
        "Smoked",
        "Bombed",
        "Fat",
        "Luxury",
        "Wild",
        "Broken",
        "Prototype",
        "Artisan",
        "Paper",
        "Murder",
        "Electric",
        "Glass",
        "Dirty",
        "Repurposed",
        "Disputed",
        "Burnt",
        "Overgrown",
        "Loud",
    ],
    "spark_2": [
        "Society",
        "Factory",
        "Art",
        "Canal",
        "Tourism",
        "Lizard",
        "Graveyard",
        "Council",
        "Slum",
        "Music",
        "Distillery",
        "Youth",
        "Office",
        "University",
        "Museum",
        "Crowd",
        "Debt",
        "Chimney",
        "Heap",
        "Tonic",
    ],
    "spark_1_name": "Spark 1",
    "spark_2_name": "Spark 2",
}

cocktails_spark_table = {
    "spark_1": [
        "Gin",
        "Smoked Whisky",
        "Dark Rum",
        "Cane Rum",
        "Corn Whisky",
        "Moonshine",
        "Potato Vodka",
        "Apple Brandy",
        "Pear Brandy",
        "Grape Brandy",
        "Mezcal",
        "Cherry Spirit",
        "Honey Spririt",
        "Industrial Rum",
        "Clear Spirit",
        "Grass Spirit",
        "Berry Brandy",
        "White Malt",
        "Nut Spirit",
        "Coconut Rum",
    ],
    "spark_2": [
        "Herbal Wine",
        "Molasses",
        "Bitters",
        "Cherry Wine",
        "Absinthe",
        "Spiced Syrup",
        "Lemon",
        "Anisette",
        "Mint Oil",
        "Bark Extract",
        "Orange Liqueur",
        "Anchovy Sauce",
        "Cold Coffee",
        "Port Wine",
        "Cocoa Beans",
        "Strawberry Jam",
        "Beef Stock",
        "Tomato Press",
        "Rose Water",
        "Stout",
    ],
    "spark_1_name": "Spirit",
    "spark_2_name": "Modifier",
}

parlour_games = {
    "spark_1": [
        "Liar’s",
        "Blushing",
        "Speed",
        "Couple’s",
        "Silent",
        "Soldier’s",
        "Hot",
        "Cold",
        "Slippery",
        "Soggy",
        "Queen’s",
        "Squeaky",
        "Country",
        "Smoking",
        "Dummy’s",
        "Carrot",
        "Sticky",
        "Baby’s",
        "Lucky",
    ],
    "spark_2": [
        "Smash",
        "Story",
        "Quiz",
        "Grapple",
        "Trick",
        "Bluff",
        "Ball",
        "Murder",
        "Grab",
        "Wink",
        "Pudding",
        "Bullet",
        "Dragon",
        "Bell",
        "Piggy",
        "Gambit",
        "War",
        "Looky",
        "Slipper",
        "Smile",
    ],
    "spark_1_name": "Word 1",
    "spark_2_name": "Word 2",
}


deep_country = {
    "spark_1": [
        "Soil",
        "Rain",
        "Slow",
        "Failed",
        "Rock",
        "Lost",
        "Birds",
        "Forgotten",
        "Blood",
        "Horse",
        "Old",
        "Feast",
        "Bog",
        "Mountain",
        "Beast",
        "River",
        "Potato",
        "Tree",
        "Milk",
        "Daughter",
    ],
    "spark_2": [
        "Harvest",
        "Hunt",
        "Fermentation",
        "Sleep",
        "Cull",
        "Travellers",
        "Raid",
        "Devil",
        "Burning",
        "Pit",
        "Funeral",
        "Rivalry",
        "Church",
        "Tower",
        "Ancestry",
        "Idol",
        "Ruins",
        "Preservation",
        "Grudge",
        "Memorial",
    ],
    "spark_1_name": "Spark 1",
    "spark_2_name": "Spark 2",
}

deep_country_places = {
    "spark_1": [
        "Gigantic Tree",
        "Mountain",
        "Animal Statue",
        "Bridge",
        "Clock Tower",
        "Shipwreck",
        "Geyser",
        "Castle Ruin",
        "Great Wall",
        "Lake",
        "Church",
        "Temple Ruin",
        "Watchtower",
        "Monolith",
        "Lighthouse",
        "Boulder",
        "Monastery",
        "Great Idol",
        "Pyramid",
        "Steam Vents",
    ],
    "spark_2": [
        "Crumbling Cliffs",
        "Stink Bog",
        "Dead Woods",
        "Dusty Desert",
        "Hillside Farms",
        "Misty Moors",
        "Red Drylands",
        "Salt Crags",
        "Dense Jungle",
        "Endless Tundra",
        "Baked Savannah",
        "Snow Forest",
        "Bare Rock",
        "Windy Steppe",
        "Dead Scrub",
        "Sheer Mesas",
        "Wooded Mountains",
        "White Beaches",
        "Mangrove Swamp",
        "Sand Dunes",
    ],
    "spark_1_name": "Landmark",
    "spark_2_name": "Surroundings",
}


underground = {
    "spark_1": [
        "Dark",
        "Decaying",
        "Scaled",
        "Preserved",
        "Rock",
        "Ornate",
        "Pale",
        "Corrosive",
        "Glowing",
        "Duplicating",
        "Twisted",
        "Impossible",
        "Tiny",
        "Dead",
        "False",
        "Distant",
        "Forgotten",
        "Trick",
        "Absorbing",
        "Merged",
    ],
    "spark_2": [
        "Skeleton",
        "Eye",
        "Worm",
        "Ghost",
        "Blob",
        "Spiral",
        "Spike",
        "Mouth",
        "Tribe",
        "Mirror",
        "Machine",
        "Pool",
        "Door",
        "Chain",
        "Husk",
        "Clock",
        "Mole",
        "Shadow",
        "Box",
        "Chute",
    ],
    "spark_1_name": "Spark 1",
    "spark_2_name": "Spark 2",
}

tunnel_aesthetic = {
    "spark_1": [
        "Screaming Winds",
        "Disgusting Smell",
        "Metal Vermin",
        "Sheer Drop",
        "Freezing Cold",
        "Time Dilation",
        "Unbreakable Silence",
        "Unlightable Dark",
        "Guillotine Blades",
        "Argumentative Door",
        "Totally Flooded",
        "Deafening Noise",
        "Nerve Gas",
        "Unbearable Heat",
        "Spatial Loop",
        "Acid Waterfall",
        "Unyielding Webs",
        "Preserved Corpses",
        "Coal and Smoke",
        "Dehydrating Air",
    ],
    "spark_2": [
        "Dark Tiles",
        "Wood Panelling",
        "Red Marble",
        "Insect Hive",
        "Clinical White",
        "Carved Sandstone",
        "Oily Machinery",
        "Luxurious Interior",
        "Padded Walls",
        "White Tiles",
        "Mirror Maze",
        "Polished Obsidian",
        "Iron Coral",
        "Copper and Jade",
        "Granite and Moss",
        "Bare Brick Walls",
        "Bloody Wallpaper",
        "Metal Grates",
        "Tangle of Pipes",
        "Giant Tree Roots",
    ],
    "spark_1_name": "Obstacle",
    "spark_2_name": "Look",
}


hazards_in_the_dark = {
    "spark_1": [
        "Murmuring",
        "Grinding",
        "Hissing",
        "Laughing",
        "Crunching",
        "Screaming",
        "Clacking",
        "Fluttering",
        "Growling",
        "Tuneless Whistling",
        "Tiny Voice",
        "Hundreds of Feet",
        "Crackling",
        "Babbling",
        "Deep Singing",
        "Croaking",
        "Chewing",
        "Hooting",
        "Chirping",
        "Sharpening",
    ],
    "spark_2": [
        "Abduction",
        "Devouring",
        "Parasite",
        "Misery",
        "Imprisonment",
        "Constriction",
        "Slavery",
        "Experimentation",
        "Staining",
        "Disgust",
        "Inebriation",
        "Obligation",
        "Absorption",
        "Humiliation",
        "Commitment",
        "Assimilation",
        "Shame",
        "Hunger",
        "Preservation",
        "Transformation",
    ],
    "spark_1_name": "Warning",
    "spark_2_name": "Danger",
}

bastion_npc = {
    "spark_1": [
        "Blunt",
        "Detailed",
        "Silky Smooth",
        "Rambling",
        "Monotone",
        "Breathy Wisp",
        "Timid",
        "Booming",
        "Sheltered",
        "Stuttering",
        "Insincere",
        "Dramatic",
        "Intense",
        "Cynical",
        "Faint",
        "Gentle",
        "Drawling",
        "Crude",
        "Slow",
        "Contrary",
    ],
    "spark_2": [
        "Base Pleasure",
        "Safety",
        "Domination",
        "Truth",
        "Service",
        "Astral Enlightenment",
        "Peace and Quiet",
        "Petty Revenge",
        "Justice",
        "Legacy",
        "Wealth",
        "Envy",
        "Approval",
        "Charity",
        "Entertainment",
        "Power and Influence",
        "Freedom",
        "Creativity",
        "Modernity",
        "Laziness",
    ],
    "spark_1_name": "Manner",
    "spark_2_name": "Drive",
}


mockeries = {
    "spark_1": [
        "Otter",
        "Lobster",
        "Heron",
        "Toad",
        "Rhino",
        "Mole",
        "Goat",
        "Spider",
        "Crow",
        "Mallard",
        "Dolphin",
        "Crocodile",
        "Hog",
        "Bear",
        "Rooster",
        "Whale",
        "Mammoth",
        "Bunny",
        "Oyster",
        "Anaconda",
    ],
    "spark_2": [
        "Forensics",
        "Cooking",
        "Sprinting",
        "Eating",
        "Seduction",
        "Puzzles",
        "Burglary",
        "Performance",
        "Bureaucracy",
        "Vision",
        "Memory",
        "Law",
        "Academia",
        "Strategy",
        "Spying",
        "Interrogation",
        "Trivia",
        "Engineering",
        "Scuplture",
        "Grooming",
    ],
    "spark_1_name": "Type",
    "spark_2_name": "Talent",
}
machines = {
    "spark_1": [
        "Many Terminals",
        "Colossal Vehicle",
        "Huge Display",
        "Reels of Tape",
        "Metal Brain in Jar",
        "Telephone Booth",
        "Steam Shrine",
        "Pipe Organ",
        "Hanging Orbs",
        "Steel Jaws",
        "Lenses and Light",
        "Suspended Claw",
        "PA System",
        "Golden Tree",
        "Wired-up Corpse",
        "Mirror with Hands",
        "Brass Lizard",
        "Silver Face",
        "Mouth in the Wall",
        "Copper Snake",
    ],
    "spark_2": [
        "Old and Grumpy",
        "Overly Theatrical",
        "Amoral Pragmatism",
        "Twisted Logic",
        "Menacing Survivalist",
        "Devil's Advocate",
        "Insincerely Motherly",
        "Childlike Curiosity",
        "Oblivious Savant",
        "Stuffy and Formal",
        "Robotic Humourist",
        "Cryptic Teacher",
        "Dramatic Narrator",
        "Slow and Dependable",
        "Proud and Vain",
        "Jealous and Bitter",
        "Insecure Bully",
        "Petty Gossip",
        "Impatient Fast-Talker",
        "Serene Pacifist",
    ],
    "spark_1_name": "Visual Prompt",
    "spark_2_name": "Character",
}

aliens = {
    "spark_1": [
        "Word",
        "Void",
        "Pleasure",
        "Blood",
        "Mercy",
        "Golden",
        "Flesh",
        "War",
        "Light",
        "Rage",
        "Smoke",
        "Horned",
        "Royal",
        "Knife",
        "Divine",
        "Perfect",
        "Ice",
        "Immortal",
        "Diamond",
        "Imitation",
    ],
    "spark_2": [
        "Saints",
        "Pilgrims",
        "Workers",
        "Locusts",
        "Beasts",
        "Imps",
        "Vessels",
        "Ghosts",
        "Hounds",
        "Beacons",
        "Serpents",
        "Titans",
        "Forgers",
        "Guardians",
        "Engineers",
        "Breakers",
        "Spiders",
        "Thieves",
        "Tyrants",
        "Eyes",
    ],
    "spark_1_name": "Prefix",
    "spark_2_name": "Suffix",
}


monstrosity = {
    "spark_1_name": "Origin",
    "spark_2_name": "Modifier",
    "spark_1": [
        "Human (Bastion)",
        "Human (Country)",
        "Mammal (small)",
        "Mammal (large)",
        "Fish",
        "Reptile",
        "Bird",
        "Insect",
        "Tree",
        "Fungus",
        "Invertebrate",
        "Multiple People",
        "Artwork",
        "Alien (humanoid)",
        "Alien (beastly)",
        "Machine (mobile)",
        "Machine (structural)",
        "Mockery (person)",
        "Mockery (beast)",
        "Mockery (critter)",
    ],
    "spark_2": [
        "Human Science",
        "Alien Science",
        "Machine Science",
        "Mock Science",
        "Urban Religion",
        "Country Religion",
        "Alien Religion",
        "Alien Environment",
        "Underground Warping",
        "Time Dilation",
        "Industrial Accident",
        "Another Monstrosity",
        "Selective Breeding",
        "Weaponisation",
        "Chemical Exposure",
        "Union Ritual",
        "An Ancient Oddity",
        "Failed Medicine / Repair",
        "Weird Comet",
        "Attempted Destruction",
    ],
}


monstrosity2 = {
    "spark_1_name": "Theme",
    "spark_2_name": "Danger",
    "spark_1": [
        "Hunger",
        "Death",
        "Greed",
        "Destruction",
        "Gluttony",
        "Stupidity",
        "Rage",
        "Knowledge",
        "Ambition",
        "Sloth",
        "Envy",
        "Purity",
        "Lust",
        "Chaos",
        "Fear",
        "Amorality",
        "Pride",
        "Hedonism",
        "Vanity",
        "Obedience",
    ],
    "spark_2": [
        "Organised Cult of Followers",
        "Dangerous Animals",
        "Twisted Creatures",
        "Space Manipulation",
        "Time Manipulation",
        "Reality Manipulation",
        "Collection of Oddities",
        "Strange Charisma",
        "Mind Control",
        "Corrupting Presence",
        "Destructive Abilities",
        "Colossal Size",
        "Manipulate Objects",
        "Manipulate Flesh",
        "Weaponise Environment",
        "Creates Oddities",
        "Creates Monstrosities",
        "Mystic Abilities",
        "Vast Intelligence",
        "Physical Power",
    ],
}

random_game_inspiration_1 = {
    "spark_1_name": "Place",
    "spark_2_name": "Person",
    "spark_1": [
        "Council Offices",
        "Military Fort",
        "Garden District",
        "Feral Park",
        "Slum Festival",
        "Riverboat",
        "Science Academy",
        "Abandoned Factory",
        "Swamp Village",
        "Desert Town",
        "Coastal Resort",
        "Mining Colony",
        "Distant Island",
        "Observatory Outpost",
        "Rail Tunnels",
        "Catacombs",
        "Secure Vaults",
        "Underground Prison",
        "Ruined Castle",
        "Luxury Hotel",
    ],
    "spark_2": [
        "Professor",
        "Philanthropist",
        "Cat Burglar",
        "Mystic Sage",
        "Entrepreneur",
        "Cult Leader",
        "Sporting Hero",
        "Revolutionary",
        "Obsolete Aristocrat",
        "Bodyguard",
        "Bounty Hunter",
        "Explorer",
        "Star-Crossed Lovers",
        "Travelling Student",
        "Pushy Journalist",
        "Archaeologist",
        "Band of Musicians",
        "Tortured Artist",
        "Wealthy Recluse",
        "Vengeful Survivor",
    ],
}

random_game_inspiration_2 = {
    "spark_1_name": "Object",
    "spark_2_name": "Looming Threat",
    "spark_1": [
        "Worthless Crown",
        "Strange Weapon",
        "Book of Names",
        "Photograph",
        "Retired Train",
        "Lost Key",
        "Electric Armour",
        "Brass Statue",
        "Legendary Recipe",
        "Antidote",
        "Tropical Fruit",
        "Prototype Vehicle",
        "Vial of Blood",
        "Scientific Theory",
        "Telescope",
        "Fine Clothes",
        "Wedding Ring",
        "Holy Relic",
        "Historic Dagger",
        "Huge Jewel",
    ],
    "spark_2": [
        "Star Invasion",
        "Populist Uprising",
        "Geological Instability",
        "Despot Elected",
        "Assassination Plot",
        "Monstrosity Nearby",
        "Approaching Storm",
        "Industrial Disaster",
        "Cult Ritual",
        "Swelling Riots",
        "Bomb Plot",
        "Machine Insurrection",
        "Rising Evangelist",
        "Incoming Meteor",
        "Resurrection",
        "Deep Country Raiders",
        "Famine",
        "Plague",
        "Heatwave",
        "Deadly Freeze",
    ],
}

spark_tables = {
    "Random Game Inspiration: Place and Person": random_game_inspiration_1,
    "Random Game Inspiration: Object and Looming threat": random_game_inspiration_2,
    "Bastion": bastion_spark_table,
    "Cocktails": cocktails_spark_table,
    "Parlour Games": parlour_games,
    "Deep Country": deep_country,
    "Deep Country Places": deep_country_places,
    "The Underground": underground,
    "Tunnel Aesthetic": tunnel_aesthetic,
    "Hazards in the Dark": hazards_in_the_dark,
    "A Bastion Dweller": bastion_npc,
    "Mockery": mockeries,
    "Machines": machines,
    "Aliens": aliens,
    "Monstrosity": monstrosity,
    "Monstrosity 2": monstrosity2,
}
