# Generated by Django 4.2.4 on 2024-10-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('HP', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('WIL', models.IntegerField()),
                ('armor', models.IntegerField(blank=True, null=True)),
                ('attack1', models.CharField(blank=True, max_length=60)),
                ('attack2', models.CharField(blank=True, max_length=60)),
                ('crit', models.TextField(blank=True)),
                ('special', models.TextField(blank=True)),
                ('spells', models.CharField(blank=True, max_length=60)),
                ('wants', models.TextField(blank=True)),
                ('variation_name', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_part', models.CharField(max_length=200)),
                ('last_part', models.CharField(max_length=200)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mausritter.creature')),
            ],
        ),
    ]
