# Generated by Django 4.2.4 on 2025-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('ac', models.CharField(max_length=20)),
                ('hit_dice', models.CharField(max_length=20)),
                ('attacks', models.CharField(max_length=200)),
                ('thac0', models.CharField(max_length=12)),
                ('movement', models.CharField(max_length=200)),
                ('saving_throws', models.CharField(max_length=200)),
                ('morale', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=100)),
                ('xp', models.CharField(max_length=100)),
                ('number_appearing', models.CharField(max_length=100)),
                ('treasure_type', models.CharField(max_length=100)),
                ('extra_info', models.TextField(blank=True, max_length=2000, null=True)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
