# Generated by Django 4.2.4 on 2025-07-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='treasure_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
