import re
from .dice import roll
from .constants import REGIONS, ENCOUNTER_CIRCUMSTANCES

table = {
    "Animal": {
        1: "Bat, Giant* (1d10)",
        2: "Bear* (1d4)",
        3: "Boar* (1d6)",
        4: "Burrowing Beetle* (2d4)",
        5: "Carrion Worm* (1d3)",
        6: "Centipede, Giant* (1d8)",
        7: "False Unicorn* (3d4)",
        8: "Fire Beetle, Giant* (2d6)",
        9: "Fly, Giant* (2d6)",
        10: "Insect Swarm* (1d3)",
        11: "Rapacious Beetle* (2d4)",
        12: "Rat, Giant* (3d6)",
        13: "Red Deer* (3d10)",
        14: "Shaggy Mammoth* (2d8)",
        15: "Snake—Adder* (1d8)",
        16: "Stirge* (2d6)",
        17: "Toad, Giant* (1d4)",
        18: "Weasel, Giant* (1d6)",
        19: "Wolf* (3d6)",
        20: "Yegril* (3d8)",
    },
    "Monster": {
        1: "Ant, Giant* (3d4)",
        2: "Centaur—Bestial (1)",
        3: "Cockatrice (1d4)",
        4: "Ghoul (2d4)",
        5: "Griffon* (2d8)",
        6: "Headless Rider (1d4)",
        7: "Mogglewomp (1)",
        8: "Mugwudge (1d4)",
        9: "Ogre (1d6)",
        10: "Owlbear* (1d4)",
        11: "Root Thing (1d4)",
        12: "Snail, Giant—Mutant (1d3)",
        13: "Spinning Spider, Giant* (1d3)",
        14: "Stirge* (2d6)",
        15: "Treowere (1d8)",
        16: "Werewolf (1d6)",
        17: "Wolf, Dire* (2d4)",
        18: "Wyrm—Black Bile (1)",
        19: "Wyrm—Blood (1)",
        20: "Yickerwill (1d6)",
    },
    "Mortal": {
        1: "Adventuring Party",
        2: "Cleric† (1d20)",
        3: "Crier‡ (1d6)",
        4: "Drune—Cottager (1d4)",
        5: "Fighter† (2d6)",
        6: "Fortune-Teller‡ (1d3)",
        7: "Friar† (1d6)",
        8: "Hunter† (3d6)",
        9: "Knight† (2d6)",
        10: "Lost Soul‡ (1d4)",
        11: "Magician† (1d4)",
        12: "Merchant‡ (1d20)",
        13: "Pedlar‡ (1d4)",
        14: "Pedlar‡ (1d4)",
        15: "Pilgrim‡ (4d8)",
        16: "Priest‡ (1d6)",
        17: "Thief (Bandit)† (3d10)",
        18: "Thief (Bandit)† (3d10)",
        19: "Villager‡ (2d10)",
        20: "Witch (1d6)",
    },
    "Sentient": {
        1: "Barrowbogey (2d6)",
        2: "Breggle—Shorthorn (3d10)",
        3: "Crookhorn (3d10)",
        4: "Deorling—Stag (1d6)",
        5: "Elf—Courtier or Knight (1d4)",
        6: "Elf—Wanderer (1d6)",
        7: "Goblin (2d6)",
        8: "Grimalkin (1d4)",
        9: "Mossling (2d8)",
        10: "Nutcap (2d6)",
        11: "Redcap (2d6)",
        12: "Scarecrow (1d4)",
        13: "Scrabey (1d6)",
        14: "Shape-Stealer (1d6)",
        15: "Sprite (3d6)",
        16: "Talking Animal (1d4)",
        17: "Treowere (1d8)",
        18: "Troll (1d3)",
        19: "Wodewose (1d6)",
        20: "Woodgrue (3d6)",
    },
}

region_dicts = (
    {
        1: "Antler Wraith (2d4)",
        2: "Breggle—Shorthorn (3d10)",
        3: "Centaur—Sylvan (2d6)",
        4: "Deorling—Doe (4d4)",
        5: "Elf—Knight (1d4)",
        6: "Elf—Wanderer (1d6)",
        7: "Fairy Horse (1)",
        8: "Gelatinous Hulk (1d4)",
        9: "Gloam (1)",
        10: "Goblin (2d6)",
        11: "Grimalkin (1d4)",
        12: "Pedlar‡ (1d4)",
        13: "Redcap (2d6)",
        14: "Snail, Giant—Psionic (1)",
        15: "Sprite (3d6)",
        16: "Thief (Bandit)† (3d10)",
        17: "Unicorn—Blessed (1d6)",
        18: "Wild Hunt (see p355)",
        19: "Witch (1d6)",
        20: "Woodgrue (3d6)",
    },
    {
        1: "Adventuring Party",
        2: "Angler‡ (2d4)",
        3: "Boggin (1d6)",
        4: "Catfish, Giant* (1d2)",
        5: "Crab, Giant* (1d6)",
        6: "Fly, Giant* (2d6)",
        7: "Insect Swarm* (1d3)",
        8: "Kelpie (1)",
        9: "Killer Bee* (2d6)",
        10: "Leech, Giant* (1d4)",
        11: "Madtom (1d12)",
        12: "Merchant‡ (1d20)",
        13: "Merfaun (2d6)",
        14: "Pedlar‡ (1d4)",
        15: "Pike, Giant* (1d4)",
        16: "Stirge* (2d6)",
        17: "Thief (Pirate)† (3d10)",
        18: "Toad, Giant* (1d4)",
        19: "Water Termite, Giant* (1d3)",
        20: "Wyrm—Phlegm (1)",
    },
    {
        1: "Antler Wraith (2d4)",
        2: "Basilisk (1d6)",
        3: "Brambling (1d4)",
        4: "Centipede, Giant* (1d8)",
        5: "Crookhorn (3d10)",
        6: "Drune—Audrune (1)",
        7: "Drune—Braithmaid (1d4)",
        8: "Drune—Cottager (1d4)",
        9: "Drune—Cottager (2d6)",
        10: "Drune—Drunewife (1)",
        11: "Lost Soul‡ (1d4)",
        12: "Shadow (1d8)",
        13: "Skeleton (3d6)",
        14: "Spinning Spider, Giant* (1d3)",
        15: "Sprite (3d6)",
        16: "Thief (Bandit)† (3d10)",
        17: "Wicker Giant (1)",
        18: "Wight (1d6)",
        19: "Witch (1d6)",
        20: "Wyrm—Yellow Bile (1)",
    },
    {
        1: "Bat, Vampire* (1d10)",
        2: "Black Tentacles (1d4)",
        3: "Bog Salamander (1d3)",
        4: "Centaur—Bestial (1)",
        5: "Crookhorn (3d10)",
        6: "Fly, Giant* (2d6)",
        7: "Galosher (2d6)",
        8: "Gelatinous Hulk (1d4)",
        9: "Harridan (1d3)",
        10: "Insect Swarm* (1d3)",
        11: "Jack-o’-Lantern (1d8)",
        12: "Leech, Giant* (1d4)",
        13: "Madtom (1d12)",
        14: "Marsh Lantern (1d12)",
        15: "Mugwudge (1d4)",
        16: "Redcap (2d6)",
        17: "Shadow (1d8)",
        18: "Toad, Giant* (1d4)",
        19: "Troll (1d3)",
        20: "Wyrm—Phlegm (1)",
    },
    {
        1: "Banshee (1)",
        2: "Bat, Giant* (1d10)",
        3: "Black Tentacles (1d4)",
        4: "Bog Corpse (2d4)",
        5: "Bog Salamander (1d3)",
        6: "Boggin (1d6)",
        7: "Galosher (2d6)",
        8: "Ghoul (2d4)",
        9: "Gloam (1)",
        10: "Leech, Giant* (1d4)",
        11: "Marsh Lantern (1d12)",
        12: "Mugwudge (1d4)",
        13: "Shadow (1d8)",
        14: "Swamp Sloth* (1d6)",
        15: "Swamp Spider, Giant* (1d3)",
        16: "The Hag (see p82)",
        17: "Toad, Giant* (1d4)",
        18: "Troll (1d3)",
        19: "Unicorn—Corrupt (1d6)",
        20: "Wronguncle (1)",
    },
    {
        1: "Barrowbogey (2d6)",
        2: "Breggle—Longhorn (2d4)",
        3: "Breggle—Shorthorn (3d10)",
        4: "Breggle—Shorthorn (3d10)",
        5: "Crier‡ (1d6)",
        6: "Devil Goat (1d4)",
        7: "Drune—Braithmaid (1d4)",
        8: "Drune—Cottager (1d4)",
        9: "Elf—Knight (1d4)",
        10: "Goblin (2d6)",
        11: "Grimalkin (1d4)",
        12: "Knight† (2d6)",
        13: "Merchant‡ (1d20)",
        14: "Pedlar‡ (1d4)",
        15: "Priest‡ (1d6)",
        16: "Scrabey (1d6)",
        17: "Thief (Bandit)† (3d10)",
        18: "Witch (1d6)",
        19: "Witch Owl (1d6)",
        20: "Woodgrue (3d6)",
    },
    {
        1: "Bat, Vampire* (1d10)",
        2: "Bog Corpse (2d4)",
        3: "Bog Salamander (1d3)",
        4: "Brainconk (1d8)",
        5: "Gelatinous Hulk (1d4)",
        6: "Jack-o’-Lantern (1d8)",
        7: "Mossling (2d8)",
        8: "Mossling (2d8)",
        9: "Mossling (2d8)",
        10: "Mossling (4d8)",
        11: "Mould Oracle (1d3)",
        12: "Ochre Slime-Hulk (1)",
        13: "Ochre Slime-Hulk (1)",
        14: "Onyx Blob (1)",
        15: "Pook Morel (2d10)",
        16: "Pook Morel (2d10)",
        17: "Redslob (1d4)",
        18: "Redslob (1d4)",
        19: "Wodewose (1d6)",
        20: "Wronguncle (1)",
    },
    {
        1: "Atanuwë (see p45)",
        2: "Bat, Vampire* (1d10)",
        3: "Bog Corpse (2d4)",
        4: "Centaur—Bestial (1)",
        5: "Crookhorn (3d10)",
        6: "Crookhorn (3d10)",
        7: "Crookhorn (6d10)",
        8: "Harpy (2d4)",
        9: "Harridan (1d3)",
        10: "Manticore (1d4)",
        11: "Ochre Slime-Hulk (1)",
        12: "Ogre (1d6)",
        13: "Ogre (1d6)",
        14: "Owlbear* (1d4)",
        15: "Snail, Giant—Mutant (1d3)",
        16: "Spinning Spider, Giant (1d4)",
        17: "Treowere (Chaotic) (1d8)",
        18: "Unicorn—Corrupt (1d6)",
        19: "Wolf, Dire* (2d4)",
        20: "Wyrm—Black Bile (1)",
    },
    {
        1: "Banshee (1)",
        2: "Bat, Vampire* (1d10)",
        3: "Black Tentacles (1d4)",
        4: "Bog Corpse (2d4)",
        5: "Bog Salamander (1d3)",
        6: "Deorling—Stag (1d6)",
        7: "Fomorian (1d3)",
        8: "Galosher (2d6)",
        9: "Gloam (1)",
        10: "Harridan (1d3)",
        11: "Leech, Giant* (1d4)",
        12: "Madtom (1d12)",
        13: "Marsh Lantern (1d12)",
        14: "Mugwudge (1d4)",
        15: "Redcap (2d6)",
        16: "Scarecrow (1d4)",
        17: "Shadow (1d8)",
        18: "Spectre (1d4)",
        19: "Wight (1d6)",
        20: "Witch Owl (1d6)",
    },
    {
        1: "Banshee (1)",
        2: "Crookhorn (3d10)",
        3: "Deorling—Doe (4d4)",
        4: "Drune—Cottager (1d4)",
        5: "Elf—Wanderer (1d6)",
        6: "Fly, Giant* (2d6)",
        7: "Ghoul (2d4)",
        8: "Gloam (1)",
        9: "Harpy (2d4)",
        10: "Headless Rider (1d4)",
        11: "Lost Soul‡ (1d4)",
        12: "Peryton (2d4)",
        13: "Peryton (2d4)",
        14: "Shadow (1d8)",
        15: "Shape-Stealer (1d6)",
        16: "Skeleton (3d6)",
        17: "Spectre (1d4)",
        18: "Wight (1d6)",
        19: "Witch (1d6)",
        20: "Woodgrue (3d6)",
    },
    {
        1: "Breggle—Shorthorn (3d10)",
        2: "Cleric† (1d20)",
        3: "Elf—Wanderer (1d6)",
        4: "Fighter† (2d6)",
        5: "Friar† (1d6)",
        6: "Gloam (1)",
        7: "Goblin (2d6)",
        8: "Griffon (2d8)",
        9: "Grimalkin (1d4)",
        10: "Killer Bee* (2d6)",
        11: "Knight† (2d6)",
        12: "Merchant‡ (1d20)",
        13: "Mossling (2d8)",
        14: "Pilgrim‡ (4d8)",
        15: "Pook Morel (2d10)",
        16: "Scrabey (1d6)",
        17: "Sprite (3d6)",
        18: "Villager‡ (2d10)",
        19: "Witch (1d6)",
        20: "Woodgrue (3d6)",
    },
    {
        1: "Cobbin (1d4)",
        2: "Cobbin (1d4)",
        3: "Cobbin (1d4)",
        4: "Cobbin (3d8)",
        5: "Crookhorn (3d10)",
        6: "Crookhorn (3d10)",
        7: "Crookhorn (3d10)",
        8: "Deorling—Stag (1d6)",
        9: "Goblin (2d6)",
        10: "Grimalkin (1d4)",
        11: "Lost Soul‡ (1d4)",
        12: "Mossling (2d8)",
        13: "Ochre Slime-Hulk (1)",
        14: "Ogre (1d6)",
        15: "Owlbear* (1d4)",
        16: "Redslob (1d4)",
        17: "Sprite (3d6)",
        18: "Troll (1d3)",
        19: "Wodewose (1d6)",
        20: "Woodgrue (3d6)",
    },
    # fairy roads
    {
        1: "Adventuring Party",
        2: "Barrowbogey (2d6)",
        3: "Centaur—Sylvan (2d6)",
        4: "Drune—Braithmaid (1d3) 14",
        5: "Drune—Cottager (1d3)",
        6: "Elf—Courtier (1d3)",
        7: "Elf—Knight (1d8)",
        8: "Elf—Wanderer (1d6)",
        9: "Fairy Horse (1)",
        10: "Goblin (2d6)",
        11: "Grimalkin (1d4)",
        12: "Lost Soul ‡ (1d4)",
        13: "Redcap (2d6)",
        14: "Redcap (2d6)",
        15: "Scrabey (1d6)",
        16: "Shape-Stealer (1d6)",
        17: "Snail, Giant—Psionic (1)",
        18: "Sprite (2d6)",
        19: "Witch (1d6)",
        20: "Woodgrue (3d6)",
    },
)

region_table = {r: d for r, d in zip(REGIONS, region_dicts)}


def type_roller(situation):
    type_results = (
        {
            1: "Animal",
            2: "Monster",
            3: "Mortal",
            4: "Mortal",
            5: "Sentient",
            6: "Sentient",
            7: "Regional",
            8: "Regional",
        },
        {
            1: "Animal",
            2: "Monster",
            3: "Mortal",
            4: "Sentient",
            5: "Regional",
            6: "Regional",
            7: "Regional",
            8: "Regional",
        },
        {
            1: "Monster",
            2: "Monster",
            3: "Mortal",
            4: "Mortal",
            5: "Sentient",
            6: "Sentient",
            7: "Regional",
            8: "Regional",
        },
        {
            1: "Animal",
            2: "Animal",
            3: "Monster",
            4: "Monster",
            5: "Monster",
            6: "Regional",
            7: "Regional",
            8: "Regional",
        },
    )
    table = {cir: result for cir, result in zip(ENCOUNTER_CIRCUMSTANCES, type_results)}
    return table.get(situation).get(roll("1d8"))


activities = {
    1: "Celebrating",
    2: "Lost / exploring",
    3: "Chasing ?",
    4: "Marking territory",
    5: "Constructing",
    6: "Mating / courting",
    7: "Defecating",
    8: "Negotiating with ?",
    9: "Dying / wounded",
    10: "Patrolling / guarding",
    11: "Fleeing from ?",
    12: "Resting / camping",
    13: "Hallucinating",
    14: "Ritual / magic",
    15: "Hunting / foraging",
    16: "Sleeping",
    17: "In combat with ?",
    18: "Trapped / imprisoned",
    19: "Journey / pilgrimage",
    20: "Washing",
}


class Encounter:
    def roll_quantity(self):
        dice_expr = re.compile(r"\dd\d")

        if re.search(dice_expr, self.being):
            dice = re.search(dice_expr, self.being).group(0)
            num = roll(dice)
            self.being = self.being.replace(dice, str(num))

    def __init__(self, type_, region=None):
        self.type_ = type_
        if self.type_ != "Regional":
            self.being = table[self.type_][roll("1d20")]
        else:
            self.being = region_table[region][roll("1d20")]
        if region == REGIONS[-1]:  # fairy roads case
            self.being = region_table[region][roll("1d20")]
        self.roll_quantity()
        self.activity = activities.get(roll("1d20"))
        self.surprise = roll("1d6") <= 2
        self.distance = f"{roll('2d6') * 30}’"
        self.reaction = roll("2d6")

    def __repr__(self):
        return self.being
