archetypes = [
    "Adventurous lad ",
    "Lovable drunk",
    "Airhead scholar ",
    "Lovestruck youth",
    "Ambitious novice ",
    "Loyal squire",
    "Animal whisperer ",
    "Mad inventor",
    "Annoying urchin ",
    "Melancholy queen",
    "Arrogant doctor ",
    "Misfit outlander",
    "Austere priest",
    "Musical prodigy",
    "Beloved general ",
    "Mysterious figure",
    "Blunt farmer",
    "Narcissist actor",
    "Classy courtesan ",
    "Noble prince",
    "Cold governess ",
    "Nosy innkeeper",
    "Corrupt guard",
    "Oafish earl",
    "Crafty eunuch",
    "Old fool",
    "Criminal genius ",
    "Overeager bard",
    "Cruel count",
    "Pathetic gambler",
    "Daring explorer ",
    "Penniless writer",
    "Dashing poet",
    "Pious pilgrim",
    "Desperate bandit ",
    "Pitiful orphan",
    "Disguised beggar ",
    "Plucky princess",
    "Doughty fighter ",
    "Raging barbarian",
    "Dumb thug",
    "Rash occultist",
    "Edgy artist",
    "Righteous paladin",
    "Enigmatic oracle ",
    "Roguish smuggler",
    "Evil sorcerer",
    "Ruthless assassin",
    "Exiled politician ",
    "Salty mariner",
    "Fallen knight",
    "Sarcastic jester",
    "Fanatical cultist ",
    "Senile monarch",
    "Fearless daredevil ",
    "Serene hermit",
    "Femme fatale",
    "Silent headsman",
    "Flamboyant tailor ",
    "Sinister vizier",
    "Foppish courtier ",
    "Sleazy lawyer",
    "Gentleman thief ",
    "Sleepy jailer",
    "Glib merchant",
    "Slimy henchman",
    "Gossiping servant ",
    "Sly trickster",
    "Greedy pirate",
    "Solitary composer",
    "Grim undertaker ",
    "Sour bureaucrat",
    "Grizzled ranger ",
    "Spirited rebel",
    "Gruff blacksmith ",
    "Spoiled heir",
    "Hardboiled sleuth ",
    "Starving poacher",
    "Harried student ",
    "Strict officer",
    "Heartless landlord ",
    "Suspicious spy",
    "Hedonist duke",
    "Swashbuckler",
    "Hippy herbalist ",
    "Talkative peddler",
    "Honest laborer ",
    "Tyrannical leader",
    "Hotheaded duelist ",
    "Wealthy patron",
    "Idealistic recruit ",
    "Wild druid",
    "Irritable cook",
    "Wise wizard",
    "Jaded veteran",
    "Wizened crone",
    "Jolly monk",
    "Worn-out boxer",
    "Learned sage",
    "Zealous inquisitor",
]

archetypes.sort()
