assets = [
    "Agile",
    "Natural leader",
    "Assassin leader ",
    "Noble",
    "Bodyguards",
    "Nothing to lose",
    "Book expert (p. 40) ",
    "Owed favors",
    "Building (p. 47)",
    "Owed money",
    "Building access ",
    "Owns armory",
    "Card shark",
    "Owns army",
    "Charming",
    "Owns castle",
    "Contortionist",
    "Owns factory",
    "Cooks books",
    "Owns fleet",
    "Cult leader",
    "Owns library",
    "Demigod",
    "Owns manor",
    "Disciples",
    "Owns press",
    "Disguises",
    "Owns relics",
    "Dungeon access ",
    "Owns ship",
    "Elite archer",
    "Owns stables",
    "Elite fighter",
    "Owns the guards",
    "Erases evidence ",
    "Owns tower",
    "Excellent liar",
    "Owns warband",
    "Extremely rich ",
    "Political leader",
    "Faction leader",
    "Potion (p. 35)",
    "Faction member ",
    "Potion stockpile",
    "Famous actor",
    "Power (p. 65)",
    "Famous artist",
    "Powerful ex",
    "Famous cleric",
    "Powerful friend",
    "Famous composer",
    "Powerful lover",
    "Famous explorer ",
    "Powerful parent",
    "Famous general ",
    "Powerful spouse",
    "Famous poet",
    "Procures gear",
    "Fast",
    "Profession (p. 57)",
    "Feared",
    "Religious leader",
    "Fence",
    "Respected",
    "Forges papers",
    "Saboteur",
    "Gorgeous",
    "Secret base",
    "Hears rumors",
    "Secret lab",
    "Heir to a fortune ",
    "Secret weapon",
    "Huge family",
    "Sells contraband",
    "Impersonator",
    "Servants",
    "Instructor",
    "Shapeshifter",
    "Intimidating",
    "Smuggles goods",
    "Knows buyers",
    "Spell (pp. 22-25)",
    "Knows shortcut ",
    "Spy network",
    "Launders money ",
    "Stage magician",
    "Local knowledge ",
    "Stealthy",
    "Loremaster",
    "Strong",
    "Loyal henchmen ",
    "Structure (p. 11)",
    "Master mage",
    "Trained animals",
    "Mechanical expert",
    "Trained monsters",
    "Military leader ",
    "Unbreakable",
    "Multilingual",
    "War hero",
]

assets.sort()
