books = [
    "Adventure novel",
    "Laws",
    "Agriculture",
    "Letters",
    "Almanac",
    "Libraries",
    "Anatomy",
    "Logic",
    "Ancient history",
    "Lost empires",
    "Archaeology",
    "Lost places",
    "Architecture",
    "Love poems",
    "Astrology",
    "Magic school (p. 31)",
    "Bestiary",
    "Mathematics",
    "Biography",
    "Medicine",
    "Blackmail",
    "Modern history",
    "Botany",
    "Monster (p. 61)",
    "Calendars",
    "Music",
    "City theme (p. 46)",
    "Mystery novel",
    "Comedic novel",
    "Mythology",
    "Commerce",
    "Nation",
    "Condemnation",
    "Navigation",
    "Confession",
    "Oceanography",
    "Conspiracies",
    "Painting",
    "Cookbook",
    "Planar studies",
    "Criminal secrets",
    "Politics",
    "Cryptography",
    "Potion recipe (p. 35)",
    "Culture",
    "Prayers",
    "Customs",
    "Profession (p. 57)",
    "Diplomacy",
    "Propaganda",
    "Disaster (p. 31)",
    "Prophecies",
    "Divination",
    "Psychology",
    "Domain (p. 33)",
    "Region",
    "Dungeon (p. 16)",
    "Religion",
    "Epic poems",
    "Rhetoric",
    "Espionage",
    "Romantic novel",
    "Ethics",
    "Room theme (p. 15)",
    "Etiquette",
    "Sages",
    "faction (p. 50)",
    "Sayings",
    "Fashion",
    "Sculpture",
    "Finance",
    "Secret societies",
    "Fishing",
    "Shipbuilding",
    "Folklore",
    "Shrines",
    "Genealogy",
    "Siegecraft",
    "Geography",
    "Songs",
    "Geology",
    "Spell (pp. 22-25)",
    "Ghosts",
    "State secrets",
    "Gods",
    "Sword fighting",
    "Hagiography",
    "Theology",
    "Heraldry",
    "Traps (pp. 16-17)",
    "Horror stories",
    "Treasures",
    "Hunting",
    "Utopian novel",
    "Husbandry",
    "War chronicle",
    "Journal",
    "Who’s who",
    "Language",
    "Witch-hunting",
]

books.sort()
