city_themes = [
    "Alchemy",
    "Inventions",
    "Animal (p. 64)",
    "Leisure",
    "Aristocracy",
    "Libraries",
    "Art",
    "Livestock",
    "Asylums",
    "Magic school (p. 31)",
    "Activity (p. 19)",
    "Marketplaces",
    "Banking",
    "Mausoleums",
    "Baths",
    "Medicine",
    "Begging",
    "Mercenaries",
    "Bells",
    "Military",
    "Brewing",
    "Monasteries",
    "Bridges",
    "Monuments",
    "Building (p. 47)",
    "Museums",
    "Bureaucracy",
    "Music",
    "Business",
    "Mutation (p. 30)",
    "Canals",
    "Opulence",
    "Catacombs",
    "Perfume",
    "Cats",
    "Printing",
    "City event (p. 46) ",
    "Prisons",
    "Courts",
    "Profession (p. 57)",
    "Crime families ",
    "Punishment",
    "Cults",
    "Rats",
    "Dancing",
    "Ravens",
    "Delusion (p. 30)",
    "Refuse",
    "Dining",
    "Rituals",
    "Disaster (p. 31)",
    "Room theme (p. 15)",
    "Domain (p. 33)",
    "Ruins",
    "Drinking",
    "Sacrifices",
    "Dueling",
    "Science",
    "Dungeon (p. 16)",
    "Shipyards",
    "Element (p. 29)",
    "Slavery",
    "faction (p. 50)",
    "Slums",
    "Faction trait (p. 50) ",
    "Smithing",
    "Fashion",
    "Smoke",
    "Festivals",
    "Song",
    "Feuds",
    "Spices",
    "Fishing",
    "Spores",
    "Flowers",
    "Steam power",
    "Food (p. 49)",
    "Structure (p. 11)",
    "Fortifications",
    "Temples",
    "Fountains",
    "Textiles",
    "Gambling",
    "Theaters",
    "Gangs",
    "Thievery",
    "Gardens",
    "Towers",
    "Government",
    "Training",
    "Guilds",
    "Travel shift (p. 9)",
    "Hazard (p. 17)",
    "Treasure (p. 42)",
    "Horses",
    "Trees",
    "Hunger",
    "Universities",
    "Industry",
    "Wizardry",
]

city_themes.sort()
