city_events = [
    "Activity (p. 19)",
    "Manhunt",
    "Alcohol ban",
    "Mass arrests",
    "Art trend",
    "Mass conversion",
    "Assassination",
    "Mass execution",
    "Beggar crowds ",
    "Mass expulsion",
    "Blessing",
    "Mass pardon",
    "Building collapse ",
    "Meat shortage",
    "Carnival",
    "Military parade",
    "Conscription",
    "Missionaries",
    "Consecration",
    "Mourning",
    "Construction",
    "Mud",
    "Coronation",
    "Mutation (p. 30)",
    "Coup",
    "New invention",
    "Crime wave",
    "Patrols",
    "Curfew",
    "Peace talks",
    "Delegation",
    "Pilgrims",
    "Delusion (p. 30)",
    "Plague",
    "Demolition",
    "Political scandal",
    "Disaster (p. 31)",
    "Preaching",
    "Discovery",
    "Procession",
    "Dueling trend",
    "Proclamation",
    "Earthquake",
    "Protests",
    "Election",
    "Public debate",
    "Excavation",
    "Public games",
    "Execution",
    "Public prayer",
    "Exodus",
    "Refugees",
    "Faction war (p. 50) ",
    "Religious council",
    "Fashion ban",
    "Religious scandal",
    "Fashion trend",
    "Religious war",
    "Fasting",
    "Rioting",
    "Feasting",
    "Sacrifice",
    "Fire",
    "Schism",
    "Flood",
    "Serial killer",
    "Funeral",
    "Siege",
    "Gambling ban",
    "Sinkhole",
    "Gang war",
    "Smoke",
    "Grain shortage ",
    "Social scandal",
    "Heresy",
    "Stench",
    "Holy day",
    "Street racing",
    "House war",
    "Summoning",
    "Hysteria",
    "Surrender",
    "Iconoclasm",
    "Taxation",
    "Immigration",
    "Textile shortage",
    "Inquisition",
    "Tournament",
    "Insurrection",
    "Travel shift (p. 9)",
    "Invasion",
    "Trial",
    "Jailbreak",
    "Vandalism",
    "Kidnapping",
    "Vermin",
    "Landslide",
    "Weapons ban",
    "Magic ban",
    "Wedding",
]

city_events.sort()
