clothing = [
    "Alb",
    "Hood",
    "Arm wrap",
    "Hose",
    "Arming doublet ",
    "Hounskull helm",
    "Bascinet",
    "Houppeland",
    "Belt",
    "Jacket",
    "Beret",
    "Jerkin",
    "Bicorne Hat",
    "Kerchief",
    "Blouse",
    "Kilt",
    "Bodice",
    "Kirtle",
    "Bonnet",
    "Leg wrap",
    "Boots",
    "Maniple",
    "Bracelet",
    "Mask",
    "Braies",
    "Mitre",
    "Breastplate",
    "Nasal helm",
    "Breeches",
    "Necklace",
    "Buckler",
    "Nightcap",
    "Cap",
    "Pauldron",
    "Cape",
    "Petticoat",
    "Cassock",
    "Pocket",
    "Chaperon",
    "Pointed hat",
    "Chasuble",
    "Purse",
    "Cincture",
    "Rerebrace",
    "Cloak",
    "Robe",
    "Clogs",
    "Sabatons",
    "Coat",
    "Salet",
    "Codpiece",
    "Sandals",
    "Corset",
    "Sash",
    "Cotte",
    "Scarf",
    "Cowl",
    "Shield",
    "Cravat",
    "Shirt",
    "Curiass",
    "Shoes",
    "Dalmatic",
    "Skirt",
    "Doublet",
    "Sleeves",
    "Dress",
    "Slippers",
    "Earing",
    "Smock",
    "Eyepatch",
    "Socks",
    "Fez",
    "Stockings",
    "Frog mouth helm ",
    "Stole",
    "Gambeson",
    "Surcoat",
    "Gauntlet",
    "Surplice",
    "Girdle",
    "Tabard",
    "Gloves",
    "Tower shield",
    "Gorget",
    "Tricorn hat",
    "Gown",
    "Trousers",
    "Great helm",
    "Tunic",
    "Greaves",
    "Turban",
    "Hat",
    "Vambrace",
    "Hauberk",
    "Veil",
    "Headdress",
    "Vest",
    "Helmet",
    "Wimple",
]

clothing.sort()
