colors = [
    "Acid Green",
    "Alabaster",
    "Amber",
    "Amethyst",
    "Apricot",
    "Aquamarine",
    "Asparagus",
    "Auburn",
    "Aureolin",
    "Avocado",
    "Azure",
    "Baby Blue",
    "Beige",
    "Bone",
    "Bottle Green",
    "Bronze",
    "Bubblegum",
    "Carmine",
    "Carrot",
    "Acid Green",
    "Cerise",
    "Cerulean",
    "Champagne",
    "Charcoal",
    "Chartreuse",
    "Chestnut",
    "Cinnamon",
    "Colorless",
    "Coppery",
    "Coral Pink",
    "Creamy",
    "Crimson",
    "Cyan",
    "Dove Grey",
    "Dun",
    "Eggshell",
    "Electric Blue",
    "Emerald",
    "Flesh",
    "Fuchsia",
    "Fuligin",
    "Golden",
    "Grape Juice",
    "Heliotrope",
    "Ice Blue",
    "Indigo",
    "Inky",
    "Invisible",
    "Ivory",
    "Kelly Green",
    "Lavender",
    "Lilac",
    "Lime",
    "Magenta",
    "Mahogany",
    "Maroon",
    "Mauve",
    "Milk White",
    "Moss Green",
    "Mustard",
    "Ochre",
    "Olive",
    "Opalescent",
    "Oxblood",
    "Pea Green",
    "Peach",
    "Peacock Blue",
    "Pearl",
    "Periwinkle",
    "Pine Green",
    "Plum",
    "Primrose",
    "Pumpkin",
    "Rainbow",
    "Rose",
    "Ruby",
    "Russet",
    "Rusty",
    "Saffron",
    "Salmon",
    "Sapphire",
    "Scarlet",
    "Sepia",
    "Shocking Pink",
    "Silver",
    "Slate Blue",
    "Smokey Grey",
    "Tangerine",
    "Teal",
    "Terracotta",
    "Titian Red",
    "Tomato",
    "Turquoise",
    "Tyrian",
    "Ultramarine",
    "Umber",
    "Verdigris",
    "Vermilion",
    "Violet",
    "Viridian",
]
