decorations = [
    "Antique",
    "Oversized",
    "Beaded",
    "Padded",
    "Beast motif",
    "Paisley",
    "Bells",
    "Patches",
    "Bird motif",
    "Pearls",
    "Bloody",
    "Perfumed",
    "Bones",
    "Plated",
    "Buckles",
    "Pockets",
    "Buttons",
    "Punctured",
    "Chains",
    "Reeking",
    "Chimes",
    "Rhinestones",
    "Cloud motif",
    "Ribbed",
    "Coat of arms",
    "Ribbons",
    "Color (p. 37)",
    "Ruffles",
    "Cords",
    "Satin bows",
    "Decorative coins ",
    "Scandalous",
    "Distressed",
    "Scent (p. 66)",
    "Down-stuffed",
    "Secret pocket",
    "Emblem",
    "Sequins",
    "Embroidered",
    "Shimmering",
    "Enamel pins",
    "Sigils",
    "Feathers",
    "Silver studs",
    "Flamboyant",
    "Silver thread",
    "Flame motif",
    "Skintight",
    "Flower motif",
    "Skull motif",
    "Flowers",
    "Slashed",
    "Food-stained",
    "Sparkling",
    "Formal",
    "Spiked",
    "Fringe",
    "Spot pattern",
    "Fur lined",
    "Star motif",
    "Fur trim",
    "Starched",
    "Gold studs",
    "Stonewashed",
    "Gold thread",
    "Striped",
    "Harlequin",
    "Studded",
    "Heavyweight",
    "Sun designs",
    "Heraldry",
    "Sun-faded",
    "Horns",
    "Symbol (p. 33)",
    "Ink-stained",
    "Tassels",
    "Item trait (p. 43) ",
    "Taxidermy",
    "Jewels",
    "Threadbare",
    "Lace trim",
    "Tie-died",
    "Laced up",
    "Torn",
    "Medallions",
    "Tree motif",
    "Mold",
    "Undersized",
    "Monster motif ",
    "Unfashionable",
    "Moon motif",
    "Velvet applique",
    "Moth eaten",
    "Wave designs",
    "Muddy",
    "Wine-stained",
    "Ocean motif",
    "Wrinkled",
    "Ornate border",
    "Zigzag pattern",
]

decorations.sort()
