delusions = [
    "Activity (p. 19)",
    "Invisible",
    "Always drunk",
    "Invisible servant",
    "Always polite",
    "Invulnerable",
    "Always rude",
    "Language switch",
    "Always sleepy",
    "Liability (p. 58)",
    "Amnesia",
    "Mannerism (p. 59)",
    "Animal (p. 64)",
    "Medium",
    "Asset (p. 58)",
    "Mind controlled",
    "Aura reading",
    "Missing limb",
    "Automaton",
    "Mission (p. 51)",
    "Being followed",
    "Monster (p. 61)",
    "Cannot count",
    "Monster trait (p. 65)",
    "Cannot lie",
    "Must dance",
    "Cannot read",
    "Must lie",
    "Chosen one",
    "Must obey",
    "Clone",
    "Must shout",
    "Constant rage",
    "Must skip",
    "Dark vision",
    "Must steal",
    "Demonic",
    "Name (pp. 54-55)",
    "Divine",
    "NPC Detail (p. 56)",
    "Extra limb",
    "Organ (p. 64)",
    "Falls in love",
    "Personal army",
    "Famous",
    "Personality (p. 56)",
    "Fears birds",
    "Planar traveler",
    "Fears blood",
    "Power (p. 65)",
    "Fears dom. (p. 33) ",
    "Profession (p. 57)",
    "Fears fire",
    "Prophet",
    "Fears gold",
    "Reincarnated",
    "Fears iron",
    "Rich",
    "Fears music",
    "Says thoughts",
    "Fears own hand ",
    "Secret monarch",
    "Fears PC",
    "Sees dead people",
    "Fears rain",
    "Shapeshifter",
    "Fears rivers",
    "Silent",
    "Fears sleep",
    "Skin texture (p. 36)",
    "Fears sunlight",
    "Sound (p. 66)",
    "Fears symbol (p. 33) ",
    "Spy",
    "Fears the moon ",
    "Super strength",
    "Flight",
    "Talks to animals",
    "Genius",
    "Talks to plants",
    "Gets lost",
    "Telekinetic",
    "Goal (p. 57)",
    "Telepathic",
    "Gorgeous",
    "Time traveler",
    "Hates violence",
    "Vampire",
    "Healing touch",
    "Weakness (p. 67)",
    "Hideous",
    "Weather control",
    "Illuminati",
    "Werewolf",
    "Immortal",
    "Whispers",
    "In an RPG",
    "Wiz. name (p. 27)",
    "Infamous",
    "X-Ray Vision",
]

delusions.sort()
