delve_shifts = [
    "Alarm",
    "Incense",
    "Animal sounds",
    "Increased patrols",
    "Apparition",
    "Invasion",
    "Awakening",
    "Lava flow",
    "Battle",
    "Leak",
    "Blessing",
    "Liquid sounds",
    "Blood scent",
    "Machine sounds",
    "Ceilings moves",
    "Manure scent",
    "Ceremony",
    "Monster scent",
    "City event (p. 46)",
    "Monster sounds",
    "Cleaning",
    "Mud flow",
    "Cloud of flies",
    "Music",
    "Combat sounds",
    "Nesting",
    "Construction",
    "New faction",
    "Crystal growth",
    "New monster",
    "Curse",
    "New rooms",
    "Dead rise",
    "Oil flow",
    "Decay scent",
    "Passages close",
    "Decreased patrols",
    "Passages open",
    "Delusion (p. 30)",
    "Plague",
    "Device activates",
    "Planar overlay",
    "Disaster (p. 31)",
    "Plants bloom",
    "Doors close",
    "Plants grow",
    "Doors open",
    "Plants wither",
    "Draining",
    "Repairs",
    "Dungeon rotates",
    "Rift opens",
    "Dungeon slides",
    "Room revolves",
    "Dungeon tilts",
    "Room slides",
    "Dust cloud",
    "Room tilts",
    "Earthquake",
    "Rooms filled in",
    "Element flow (p.29)",
    "Rooms rearrange",
    "Eruption",
    "Sand flow",
    "Excavation",
    "Scent (p. 66)",
    "Faction alliance",
    "Singing",
    "Faction truce",
    "Sleep",
    "Faction war",
    "Smoke",
    "Feast",
    "Sound (p. 66)",
    "Fire",
    "Static charge",
    "Flammable gas",
    "Summoning",
    "Flooding",
    "Total silence",
    "Floors move",
    "Trap effect (p. 28)",
    "Fog",
    "Traps rearm",
    "Food scent",
    "Vermin swarm",
    "Foraging",
    "Voices",
    "Freezing",
    "Walls close in",
    "Gravel flow",
    "Walls move",
    "Hatching",
    "Walls widen",
    "Hot",
    "Water flow",
    "Humid",
    "Wind",
    "Hunt",
    "Worship",
]

delve_shifts.sort()
