disasters = [
    "Acid rain",
    "51 Luage loss",
    "Aging accelerates",
    "Lightning storm",
    "Aging reverses",
    "Living nightmare",
    "All iron rusts",
    "Locusts",
    "Amnesia",
    "Maggots",
    "Animal revolt",
    "Magic barrier",
    "Animals die",
    "Mass blindness",
    "Animals mutate",
    "Mass hypnosis",
    "Animals speak",
    "Mass insanity",
    "Birds attack",
    "Mass possession",
    "Birds die",
    "Mass slumber",
    "Body swaps",
    "Mass telepathy",
    "Cities move",
    "Meteor strike",
    "City appears",
    "Mirages",
    "City changes",
    "Mirrors speak",
    "Deadly fog",
    "Mutation (p. 30)",
    "Delusion (p. 30)",
    "No stars",
    "Demon invasion",
    "Objects animate",
    "Doors lock",
    "Outsider enters",
    "Dragon wakes",
    "People shrink",
    "Dream plague",
    "People vanish",
    "Drought",
    "Pits open",
    "Earth to sand",
    "Plague",
    "Earthquake",
    "Planar overlay",
    "Effect rain (p. 28)",
    "Plants wither",
    "Element rain (p. 29)",
    "Portal opens",
    "Endless day",
    "Rage epidemic",
    "Endless night",
    "Rampant growth",
    "Endless rain",
    "Rifts open",
    "Endless storm",
    "Rivers move",
    "Endless twilight",
    "Rivers reverse",
    "Endless winter",
    "Roads move",
    "Eruption",
    "Shadows detach",
    "Fae return",
    "Shadows speak",
    "Famine",
    "Smoke",
    "Fear epidemic",
    "Space distorts",
    "Firestorm",
    "Stone to flesh",
    "Fish die",
    "Stones speak",
    "Fish speak",
    "Texture rain (p. 36)",
    "Flesh to stone",
    "Time loop",
    "Flood",
    "Time slows",
    "Forest appears",
    "Time warp",
    "Forgetfulness",
    "Tornado",
    "Giants march",
    "Total silence",
    "Gold to tin",
    "Tower appears",
    "Graves open",
    "Trees march",
    "Gravity decrease",
    "Voices of dead",
    "Gravity increase",
    "Water to blood",
    "Hills move",
    "Weapon rain (p. 43)",
    "Iron to cloth",
    "Windstorm",
]

disasters.sort()
