domains = [
    "Acid",
    "Mountains",
    "Alchemy",
    "Murderers",
    "Beauty",
    "Music",
    "Bees",
    "Oratory",
    "Beggars",
    "Performance",
    "Betrayal",
    "Poison",
    "Birds",
    "Priests",
    "Blades",
    "Prisoners",
    "Blood",
    "Rage",
    "Blossoms",
    "Rain",
    "Book (p. 40)",
    "Revenge",
    "Clay",
    "Revolution",
    "Clouds",
    "Roads",
    "Commerce",
    "Room theme (p. 15)",
    "Courage",
    "Royalty",
    "Cowards",
    "Rust",
    "Craftsmanship",
    "Sand",
    "Crows",
    "Secrets",
    "Darkness",
    "Serpents",
    "Deserts",
    "Silence",
    "Destruction",
    "Slaves",
    "Disease",
    "Sleep",
    "Doors",
    "Smoke",
    "Dreams",
    "Soldiers",
    "Duels",
    "Spiders",
    "Eagles",
    "Swamps",
    "Earthquakes",
    "Tailors",
    "Fire",
    "The Blind",
    "Fish",
    "The Elderly",
    "Forge",
    "The Future",
    "Fungi",
    "The Grave",
    "Gluttony",
    "The Harvest",
    "Greed",
    "The Hearth",
    "Healing",
    "The Hunt",
    "Horses",
    "The Law",
    "Hunger",
    "The Sea",
    "Illusions",
    "Thieves",
    "Jealousy",
    "Thorns",
    "Language",
    "Travelers",
    "Lava",
    "Trees",
    "Libraries",
    "Trickery",
    "Light",
    "Truth",
    "Lightning",
    "Tundra",
    "Love",
    "Tunnels",
    "Luck",
    "Vermin",
    "Machines",
    "Walls",
    "Madness",
    "Wind",
    "Magic school (p. 31)",
    "Wine",
    "Mazes",
    "Winter",
    "Mirrors",
    "Wolves",
]

domains.sort()
