liabilities = [
    "Alcoholic",
    "Many exes",
    "Arthritis",
    "Migraines",
    "Bad leader",
    "Military enemy",
    "Bad liar",
    "Mind-controlled",
    "Bankrupt",
    "Misinformed",
    "Beholden",
    "Money trail",
    "Blackmailed",
    "Monster trait (p. 65)",
    "Blind",
    "Mutation (p. 30)",
    "Cannot count",
    "Narcissist",
    "Cannot read",
    "Needs flattery",
    "Clumsy",
    "Needs medicine",
    "Condescending ",
    "No rights",
    "Coward",
    "Non-human",
    "Crippled",
    "Obese",
    "Cursed",
    "Obnoxious",
    "Deaf",
    "OCD",
    "Decadent",
    "Outcast",
    "Delusion (p. 30)",
    "Paranoid",
    "Disloyal followers ",
    "Pariah",
    "Disobeys orders ",
    "Party animal",
    "Drug addict",
    "Political enemy",
    "Evil lineage",
    "Poor equipment",
    "Exiled",
    "Prison record",
    "Faction enemy ",
    "Reckless",
    "Faints",
    "Religious enemy",
    "Family enemy",
    "Scandalous birth",
    "Flirts constantly ",
    "Scent (p. 66)",
    "Food addict (p. 49) ",
    "Secret lover",
    "Fragile",
    "Seizures",
    "Gambling addict ",
    "Senile",
    "Gets in fights",
    "Softhearted",
    "Glutton",
    "Sound (p. 66)",
    "Greedy",
    "Strict routines",
    "Gullible",
    "Stupid",
    "Hemophilia",
    "Superstitious",
    "Hideous",
    "Surveilled",
    "Huge debts",
    "Suspicious",
    "Insurrectionist ",
    "Too generous",
    "Jealous",
    "Transformed",
    "Known con artist ",
    "Uncool",
    "Known murderer ",
    "Undead",
    "Known thief",
    "Unpopular",
    "Known traitor ",
    "Vampire",
    "Known vandal ",
    "Very short",
    "Laughingstock ",
    "Wanted",
    "Lazy",
    "War criminal",
    "Leaves evidence ",
    "Weak-willed",
    "Loud",
    "Weakness (p. 67)",
    "Lowborn",
    "Werewolf",
    "Many enemies",
    "Widely despised",
]
