locations = [
    "Ashland",
    "Lava field",
    "Badland",
    "Lava tube",
    "Bamboo forest ",
    "Loch",
    "Basalt columns ",
    "Mangrove swamp",
    "Bay",
    "Marsh",
    "Beach",
    "Meadow",
    "Bluff",
    "Mesa",
    "Bog",
    "Mire",
    "Boulder field",
    "Moor",
    "Brook",
    "Mountain",
    "Butte",
    "Mud plain",
    "Caldera",
    "Oasis",
    "Canyon",
    "Oil seep",
    "Cave",
    "Pass",
    "Cliff",
    "Pasture",
    "Cloud forest",
    "Petrified forest",
    "Coniferous forest ",
    "Pit",
    "Copse",
    "Plateau",
    "Crag",
    "Pond",
    "Crater",
    "Prairie",
    "Creek",
    "Quicksand",
    "Crossing",
    "Rainforest",
    "Crystals",
    "Rapids",
    "Deciduous forest ",
    "Ravine",
    "Delta",
    "Ridge",
    "Dunes",
    "River",
    "Dust bowl",
    "Riverland",
    "Element field (p. 35)",
    "Rockslide",
    "Fen",
    "Salt Flat",
    "Fjord",
    "Salt Marsh",
    "Floodplain",
    "Savanna",
    "Gas vent",
    "Scree Slope",
    "Geyser",
    "Scrubland",
    "Glacier",
    "Sinkhole",
    "Gorge",
    "Spring",
    "Grotto",
    "Steppe",
    "Grove",
    "Stream",
    "Gulch",
    "Sulfur Spring",
    "Heath",
    "Swamp",
    "Highland",
    "Taiga",
    "Hollow",
    "Tar Pit",
    "Hoodoo",
    "Thicket",
    "Hot Spring",
    "Tundra",
    "Ice Sheet",
    "Valley",
    "Jungle",
    "Volcanic Plain",
    "Knoll",
    "Volcano",
    "Lagoon",
    "Wasteland",
    "Lair",
    "Waterfall",
    "Lake",
    "Wetlands",
    "Lakebed",
    "Whirlpool",
]

locations.sort()
