miscellaneous_items = [
    "Amulet",
    "Arrow",
    "Arrowhead",
    "Axe",
    "Bell",
    "Belt",
    "Book (p. 40)",
    "Boots",
    "Bottle",
    "Bow",
    "Bowl",
    "Box",
    "Bracelet",
    "Breastplate",
    "Brooch",
    "Candle",
    "Card",
    "Censer",
    "Circlet",
    "Cloak",
    "Clothing (p. 40)",
    "Coin",
    "Comb",
    "Compass",
    "Crown",
    "Cup",
    "Doll",
    "Eye",
    "Eye patch",
    "Fabric (p. 41)",
    "Feather",
    "Figurine",
    "Flute",
    "Food (p. 49)",
    "Gauntlet",
    "Gem",
    "Glove",
    "Hammer",
    "Handkerchief",
    "Hat",
    "Helm",
    "Horn",
    "Hourglass",
    "Ingredient (p. 37)",
    "Jar",
    "Key",
    "Knife",
    "Lamp",
    "Lens",
    "Locket",
    "Lute",
    "Lyre",
    "Mace",
    "Machine",
    "Mask",
    "Material (p. 42)",
    "Mirror",
    "Necklace",
    "Needle",
    "Net",
    "Orb",
    "Organ (p. 64)",
    "Painting",
    "Pearl",
    "Pen",
    "Phial",
    "Pipe",
    "Pipes",
    "Potion (p. 35)",
    "Purse",
    "Puzzle box",
    "Pyramid",
    "Razor",
    "Ring",
    "Rope",
    "Salve",
    "Scarf",
    "Scissors",
    "Scroll",
    "Shield",
    "Shoe",
    "Signet ring",
    "Skull",
    "Slippers",
    "Snuffbox",
    "Spear",
    "Staff",
    "Strand of hair",
    "Sword",
    "Tool (p. 39)",
    "Treasure (p. 42)",
    "Tooth",
    "Torch",
    "Tuning fork",
    "Turnip",
    "Wand",
    "Weapon (p. 43)",
    "Whetstone",
    "Whistle",
    "Wine",
]
