monster_traits = [
    "Acid blood",
    "Many heads",
    "Amphibious",
    "Many legs",
    "Ancient",
    "Many mouths",
    "Anim. form (p. 29) ",
    "Mechanical",
    "Animated",
    "Metallic",
    "Asymmetrical",
    "Mismatched limbs",
    "Bloated",
    "Molting",
    "Bloodless",
    "Muscular",
    "Brittle",
    "Mutation (p. 30)",
    "Burning",
    "No neck",
    "Charged",
    "One eye",
    "Clay-like",
    "Ooze-form",
    "Color (p. 37)",
    "Organ (p. 64)",
    "Colossal",
    "Personality (p. 56)",
    "Crystalline",
    "Poisonous",
    "Decaying",
    "Potion (p. 35)",
    "Delusion (p. 30)",
    "Powdery",
    "Element skin (p. 29) ",
    "Power (p. 65)",
    "Elongated",
    "Pulsing",
    "Ethereal",
    "Radioactive",
    "Ever-young",
    "Reflective",
    "Eyeless",
    "Rubbery",
    "Faceless",
    "Scent (p. 66)",
    "Flaking",
    "Shadowy",
    "Flammable",
    "Sharp",
    "Flexible",
    "Short limbs",
    "Fluffy",
    "Shriveled",
    "Foaming",
    "Skeletal",
    "Fungal",
    "Skin shedding",
    "Fuzzy",
    "Slimy",
    "Gaseous",
    "Smoking",
    "Gelatinous",
    "Soft",
    "Geometric",
    "Sooty",
    "Hair shedding",
    "Sound (p. 66)",
    "Hairless",
    "Sparking",
    "Hairy",
    "Steaming",
    "Hardened",
    "Sticky",
    "Headless",
    "Stinking",
    "Ice-cold",
    "Stone-like",
    "Illusory",
    "Stretchy",
    "Iridescent",
    "Tactic (p. 67)",
    "Large head",
    "Texture (p. 36)",
    "Legless",
    "Tiny",
    "Liquid",
    "Translucent",
    "Luminous",
    "Tree-like",
    "Lumpy",
    "Two-dimensional",
    "Mannerism (p. 59) ",
    "Venomous",
    "Many arms",
    "Vibrating",
    "Many eyes",
    "Waxy",
    "Many faces",
    "Weakness (p. 67)",
]

monster_traits.sort()
