mutations = [
    "Ages backwards ",
    "Head swells",
    "Ages faster",
    "Horns",
    "Animal body (p. 64) ",
    "Invisible head",
    "Animal ears (p. 64) ",
    "Jelly arms",
    "Animal eyes (p. 64) ",
    "Legs grow",
    "Animal form (p. 64) ",
    "Long tongue",
    "Animal head (p. 64) ",
    "Lose d20 inches",
    "Animal limb (p. 64) ",
    "Mannerism (p. 59)",
    "Animal scent (p. 64) ",
    "Mon. trait (p. 65)",
    "Animal skin (p. 64) ",
    "No eyes",
    "Animal tail (p. 64) ",
    "No nose",
    "Animal teeth (p. 64) ",
    "No teeth",
    "Animal voice (p. 64) ",
    "NPC detail (p. 56)",
    "Antennae",
    "One arm",
    "Antlers",
    "One eye",
    "Arms grow",
    "One leg",
    "Bat wings",
    "Organ (p. 64)",
    "Beak",
    "Personality (p. 56)",
    "Bird wings",
    "Pig snout",
    "Bleeds acid",
    "Power (p. 65)",
    "Chameleon eyes ",
    "Rat tail",
    "Claws",
    "Scales",
    "Color skin (p. 37) ",
    "Scent (p. 66)",
    "Crystal growth ",
    "Scorpion tail",
    "Drooling",
    "Shaggy fur",
    "Duck bill",
    "Shell",
    "Ears grow",
    "Skin boils",
    "Elem. blood (p. 29) ",
    "Skin hardens",
    "Elem. body (p. 29) ",
    "Skin pattern",
    "Elem. breath (p. 29) ",
    "Skin sags",
    "Emits fumes",
    "Skin shedding",
    "Excretes ooze",
    "Smoke breath",
    "Extra arms",
    "Snake hair",
    "Extra eyes",
    "Sound (p. 66)",
    "Extra fingers",
    "Spines",
    "Extra heads",
    "Spinnerets",
    "Extra legs",
    "Suction cups",
    "Eye stalks",
    "Sweats blood",
    "Eyes grow",
    "Tentacles",
    "Fangs",
    "Texture body (p. 36)",
    "Feathers",
    "Totally numb",
    "Feet swell",
    "Translucent skin",
    "Fins",
    "Transparent skin",
    "Fly eyes",
    "Tusks",
    "Fungal growth ",
    "Two faces",
    "Gain d20 inches ",
    "Warts",
    "Gills",
    "Webbed hands",
    "Hair growth",
    "Weight doubles",
    "Hair loss",
    "Weight halves",
    "Hands swell",
    "Wooly",
]

mutations.sort()
