organs = [
    "Antennae",
    "Long tongue",
    "Antlers",
    "Loose skin",
    "Baleen",
    "Mandibles",
    "Bat wings",
    "Mane",
    "Beaver tail",
    "Mantis arms",
    "Blowhole",
    "Monkey tail",
    "Blubber",
    "Mouse ears",
    "Boar tusks",
    "Mucus",
    "Bushy tail",
    "Otter tail",
    "Butterfly wings ",
    "Oyster shell",
    "Carapace",
    "Pelican bill",
    "Cat tail",
    "Pig snout",
    "Chameleon eyes ",
    "Pig tail",
    "Claws",
    "Pincers",
    "Cobra hood",
    "Plates",
    "Comb",
    "Plumage",
    "Compound eyes ",
    "Proboscis",
    "Crab shell",
    "Pseudopod",
    "Crane beak",
    "Quills",
    "Crest",
    "Rat tail",
    "Cricket legs",
    "Scales",
    "Detachable tail ",
    "Scorpion tail",
    "Digging claws",
    "Segments",
    "Dragonfly wings ",
    "Shaggy hair",
    "Duck bill",
    "Short fur",
    "Eagle wings",
    "Siphon",
    "Elephant tusks ",
    "Snail shell",
    "Exoskeleton",
    "Spikes",
    "Eye stalks",
    "Spines",
    "Falcon beak",
    "Spinnerets",
    "Fangs",
    "Spotted fur",
    "Feathers",
    "Squid beak",
    "Fins",
    "Stinger",
    "Fly wings",
    "Striped fur",
    "Frog legs",
    "Stubby tail",
    "Gills",
    "Suction cups",
    "Gliding flaps",
    "Talons",
    "Hooves",
    "Tendrils",
    "Horns",
    "Tentacles",
    "Horse tail",
    "Toucan beak",
    "Humming wings ",
    "Trunk",
    "Humps",
    "Turtle shell",
    "Large ears",
    "Udder",
    "Large eyes",
    "Walrus tusks",
    "Large incisors",
    "Warts",
    "Long body",
    "Wattle",
    "Long ears",
    "Webbed feet",
    "Long legs",
    "Webbed hands",
    "Long neck",
    "Whiskers",
    "Long snout",
    "Wool",
]

organs.sort()
