potions = [
    "Age",
    "Magic-proof",
    "All languages",
    "Mannerism (p. 59)",
    "Alter body",
    "Metal-proof",
    "Alter face",
    "Might",
    "Alter voice",
    "Mind reading",
    "Animal form (p. 64)",
    "Monster trait (p. 65)",
    "Armor",
    "Mutation (p. 30)",
    "Beast-speech",
    "NPC detail (p. 56)",
    "Bird-speech",
    "Ooze form",
    "Breathlessness",
    "Paranoia",
    "Claws",
    "Personality (p. 56)",
    "Cold-proof",
    "Plant-speech",
    "Courage",
    "Poison-proof",
    "Cure disease",
    "Power (p. 65)",
    "Cure poison",
    "Profession (p. 57)",
    "Cure wounds",
    "Rage",
    "Dark vision",
    "Sense danger",
    "Dead-speech",
    "Sense direction",
    "Delusion (p. 30)",
    "Sense evil",
    "Effect (p. 28)",
    "Sense gold",
    "Elasticity",
    "Sense heat",
    "Elem. form (p. 29)",
    "Sense illusion",
    "Extra arms",
    "Sense lies",
    "False death",
    "Sense magic",
    "Fear",
    "Sense undead",
    "Fire form",
    "Shrinking",
    "Fish-speech",
    "Sleep",
    "Flight",
    "Sleeplessness",
    "Forgetfulness",
    "Smoke form",
    "Friendship",
    "Sniffing",
    "Grow organ (p. 64)",
    "Sovereign acid",
    "Grow stinger",
    "Sovereign glue",
    "Growth",
    "Sovereign grease",
    "Grub-speech",
    "Sovereign poison",
    "Hate",
    "Speed",
    "Healing",
    "Spines",
    "Hearing",
    "Stone-speech",
    "Heat-proof",
    "Swimming",
    "Hunger-proof",
    "Telekinesis",
    "Ice form",
    "Thought sending",
    "Illumination",
    "Undeath",
    "Intangibility",
    "Vampirism",
    "Invisibility",
    "Ventriloquism",
    "Invulnerability",
    "Vision",
    "Iron stomach",
    "Wall-crawling",
    "Jumping",
    "Water breathing",
    "Lightning form",
    "Water walking",
    "Lightning-proof",
    "Web-slinging",
    "Love",
    "X-ray vision",
    "Lycanthropy",
    "Youth",
]

potions.sort()
