powers = [
    "Absorb abilities",
    "Healing aura",
    "Acid aura",
    "Hypnotism",
    "Acid bolt",
    "Ice aura",
    "Acid breath",
    "Ice bolt",
    "Astral projection",
    "Ice breath",
    "Attract",
    "Ice wall",
    "Beast control",
    "Immovability",
    "Bird control",
    "Insect control",
    "Blind",
    "Iron wall",
    "Blur",
    "Laser eyes",
    "Burrow",
    "Levitation",
    "Chameleon skin",
    "Lightning bolt",
    "Clairaudience",
    "Lightning breath",
    "Clairvoyance",
    "Love aura",
    "Clone self",
    "Magnetism",
    "Create illusion",
    "Memory control",
    "Deafen",
    "Mimic sounds",
    "Drain life",
    "Mind control",
    "Dreamwalk",
    "Mold flesh",
    "Earthquake",
    "Mold metal",
    "Echolocation",
    "Mold stone",
    "Effect (p. 28)",
    "Paralyze",
    "Effect aura (p. 28)",
    "Paranoia aura",
    "Effect blast (p. 28)",
    "Petrify",
    "Effect bolt (p. 28)",
    "Plane shift",
    "Effect ray (p. 28)",
    "Plant control",
    "Electric aura",
    "Poison aura",
    "Element aura (p. 29)",
    "Poison breath",
    "Element blast (p. 29)",
    "Potion (p. 35)",
    "Element bolt (p. 29)",
    "Rage aura",
    "Elem. breath (p. 29)",
    "Raise dead",
    "Elem. control (p. 29)",
    "Remove curse",
    "Element ray (p. 29)",
    "Repulse",
    "Element wall (p. 29)",
    "Rot",
    "Entangle",
    "Shockwave",
    "Entomb",
    "Silence",
    "Explode",
    "Sleep aura",
    "Fear aura",
    "Slow enemies",
    "Fire aura",
    "Spell (pp. 22-25)",
    "Fire bolt",
    "Spirit control",
    "Fire breath",
    "Stone wall",
    "Fire control",
    "Summon",
    "Fire starting",
    "Swallow whole",
    "Fire wall",
    "Swap minds",
    "Fog breath",
    "Teleport",
    "Force wall",
    "Time control",
    "Friendship aura",
    "Travel shift (p. 9)",
    "Gravity control",
    "Undead control",
    "Grow plants",
    "Wind control",
    "Hate aura",
    "Wind wall",
]

powers.sort()
