rewards = [
    "A blind eye",
    "Location (p. 10)",
    "Alcohol",
    "Machine",
    "Animal (p. 64)",
    "Magic item",
    "Armor",
    "Magical ally",
    "Army",
    "Mansion",
    "Artwork",
    "Material (p. 42)",
    "Asset (p. 58)",
    "Meeting",
    "Blackmail",
    "Mercenaries",
    "Blessing",
    "Monster ally (p. 61)",
    "Blueprints",
    "Noble clothing",
    "Building (p. 47)",
    "Noble title",
    "Business",
    "Palace",
    "Caravel",
    "Pardon",
    "Carriage",
    "Planar portal",
    "Castle",
    "Political clout",
    "Chapel",
    "Potion (p. 35)",
    "Charter",
    "Printing press",
    "Companion",
    "Reduced sentence",
    "Contract",
    "Location map",
    "Cottage",
    "Relic",
    "Craftsmen",
    "Religious clout",
    "Cypher",
    "Renown",
    "Delivery",
    "Revenge",
    "Dungeon (p. 16)",
    "Rights",
    "Dungeon map",
    "Royal clothing",
    "Endorsement",
    "Safe passage",
    "Estate",
    "Secret",
    "Expert",
    "Servants",
    "Faction ally (p. 50) ",
    "Shortcut",
    "Familiar",
    "Sloop",
    "Farm",
    "Social clout",
    "Favor",
    "Spell (pp. 22-25)",
    "Fishing boat",
    "Spices",
    "Fleet",
    "Structure (p. 11)",
    "Forge",
    "Temple",
    "Formula",
    "Theater",
    "Galleon",
    "Time extension",
    "Gold",
    "Tower",
    "Guide",
    "Training",
    "Guildhall",
    "Transformation",
    "Healing",
    "Transport",
    "Hideout",
    "Treasure (p. 42)",
    "Hirelings",
    "Treasure map",
    "Hounds",
    "Vineyard",
    "House",
    "Wagon",
    "Influential ally",
    "Warband",
    "Inn (p. 48)",
    "Warhorse",
    "Jewels",
    "Wealthy clothing",
    "Key",
    "Weakness (p. 67)",
    "Livestock",
    "Weapon (p. 43)",
]

rewards.sort()
