room_details = [
    "Alcohol",
    "Map",
    "Alcove",
    "Material (p. 42)",
    "Altar",
    "Mechanism (p. 17)",
    "Archetype (p. 53)",
    "Message",
    "Balcony",
    "Mine cart",
    "Bars",
    "Mirror",
    "Bas-relief",
    "Misc. item (p. 39)",
    "Bath",
    "Monster (p. 61)",
    "Bed",
    "Mural",
    "Bones",
    "Nest",
    "Book (p. 40)",
    "Painting",
    "Brazier",
    "Pews",
    "Broken glass",
    "Pillar",
    "Cabinet",
    "Pipes",
    "Cage",
    "Pool",
    "Carpet",
    "Portcullis",
    "Carvings",
    "Potion (p. 35)",
    "Cauldron",
    "Refuse pile",
    "Chains",
    "Repairs",
    "Chalk marks",
    "Roots",
    "Chandelier",
    "Rubble",
    "Chest",
    "Scent (p. 66)",
    "Clothing (p. 40)",
    "Shaft",
    "Coffin",
    "Shelf",
    "Coins",
    "Sign (p. 10)",
    "Collapsed ceiling",
    "Skeletons",
    "Collapsed floor",
    "Smoke",
    "Collapsed walls",
    "Sofa",
    "Crawlspace",
    "Sound (p. 66)",
    "Crumbling ceiling",
    "Spyhole",
    "Crumbling floors",
    "Stairs",
    "Crumbling walls",
    "Stalactites",
    "Curtain",
    "Statues",
    "Dais",
    "Stove",
    "Dishes",
    "Street detail (p. 47)",
    "Display case",
    "Symbol (p. 33)",
    "Dumbwaiter",
    "Table",
    "Elevator",
    "Tapestry",
    "Fabric (p. 41)",
    "Thick dust",
    "Fireplace",
    "Throne",
    "Flowing water",
    "Toilet",
    "Food (p. 49)",
    "Tool (p. 39)",
    "Fountain",
    "Torch",
    "Fungi",
    "Torture device",
    "Graffiti",
    "Training dummy",
    "Hazard (p. 17)",
    "Trap door",
    "Incense",
    "Treasure (p. 42)",
    "Ingredient (p. 37)",
    "Vines",
    "Instrument",
    "Wardrobe",
    "Lantern",
    "Weapon (p. 43)",
]

room_details.sort()
