rooms = [
    "Alchemy room",
    "Junk room",
    "Alcohol cellar",
    "Kennel",
    "Arboretum",
    "Kitchen",
    "Archery range",
    "Laboratory",
    "Arena",
    "Lair",
    "Armory",
    "Larder",
    "Arsenal",
    "Latrine",
    "Art gallery",
    "Library",
    "Art studio",
    "Lounge",
    "Audience hall",
    "Map room",
    "Aviary",
    "Maze",
    "Ballroom",
    "Mechanism (p. 17)",
    "Banquet hall",
    "Meditation room",
    "Barracks",
    "Menagerie",
    "Baths",
    "Mess hall",
    "Bed chamber",
    "Mews",
    "Brewery",
    "Museum",
    "Building (p. 47)",
    "Music room",
    "Catacombs",
    "Nursery",
    "Cave",
    "Observatory",
    "Cell",
    "Pantry",
    "Chapel",
    "Parlor",
    "Chasm",
    "Pit",
    "Church",
    "Poison room",
    "Cistern",
    "Pool",
    "Cloakroom",
    "Prison",
    "Concert hall",
    "Record room",
    "Conjuring room",
    "Location (p. 10)",
    "Courtroom",
    "Salon",
    "Courtyard",
    "Scriptorium",
    "Crematorium",
    "Scullery",
    "Crypt",
    "Sculpture gallery",
    "Dining room",
    "Shop",
    "Divination room",
    "Shrine",
    "Dormitory",
    "Slaughterhouse",
    "Dungeon (p. 16)",
    "Smoking room",
    "Dressing room",
    "Stables",
    "Embalming room",
    "Storeroom",
    "Fighting pit",
    "Structure (p. 11)",
    "Fissure",
    "Study",
    "Forge",
    "Tapestry room",
    "Fountain room",
    "Theater",
    "Gallery",
    "Throne room",
    "Game room",
    "Torture room",
    "Garden",
    "Training hall",
    "Gatehouse",
    "Treasury",
    "Great hall",
    "Trophy room",
    "Guardroom",
    "Vault",
    "Hall",
    "Work pit",
    "Infirmary",
    "Workshop",
]

rooms.sort()
