room_themes = [
    "Activity (p. 19)",
    "Mouths",
    "Blessings",
    "Music",
    "Blindness",
    "Mutation",
    "Blood",
    "Outsiders",
    "Bones",
    "Pageantry",
    "Book (p. 40)",
    "Paranoia",
    "Brains",
    "Place trait (p. 11)",
    "Chaos",
    "Poison",
    "City theme (p. 46)",
    "Priests",
    "Collapse",
    "Prophecy",
    "Combat",
    "Rats",
    "Corpses",
    "Refugees",
    "Corruption",
    "Restless dead",
    "Creation",
    "Revenge",
    "Criminal activity",
    "Riches",
    "Crows",
    "Rituals",
    "Cults",
    "Rival factions",
    "Curses",
    "Sacrifice",
    "Death",
    "Savage fury",
    "Decay",
    "Secret knowledge",
    "Disease",
    "Serpents",
    "Divination",
    "Shadows",
    "Domain (p. 33)",
    "Skulls",
    "Dragons",
    "Slavery",
    "Drowning",
    "Slime",
    "Eyes",
    "Smoke",
    "Effect (p. 28)",
    "Songs",
    "Element (p. 29)",
    "Souls",
    "Faces",
    "Spiders",
    "Feasting",
    "Stasis",
    "Fog",
    "Statues",
    "Gateways",
    "Summoning",
    "Ghosts",
    "Survival",
    "Gods",
    "Teeth",
    "Hands",
    "Tentacles",
    "Holy war",
    "Tests and trials",
    "Hunger",
    "The moon",
    "Hunting",
    "The stars",
    "Imprisonment",
    "The sun",
    "Invasion",
    "Thorns",
    "Invention",
    "Trickery",
    "Inversion",
    "Tyranny",
    "Item trait (p. 43)",
    "Vampires",
    "Judgment",
    "Water",
    "Light",
    "Wild growth",
    "Locks",
    "Wine",
    "Madness",
    "Winter",
    "Magic school (p. 31)",
    "Wolves",
    "Memory",
    "Worms",
    "Mirrors",
    "Zealotry",
]

room_themes.sort()
