signs = [
    "Arguing",
    "Middens",
    "Ash",
    "Misc. item (p. 39)",
    "Bile",
    "Molted husk",
    "Blade marks",
    "Mounds",
    "Blood",
    "Mucus",
    "Blood tracks",
    "Mud tracks",
    "Bone fragments ",
    "Musk",
    "Bones",
    "Nest",
    "Boreholes",
    "Nesting sounds",
    "Bowers",
    "Offspring",
    "Broken branches ",
    "Organ (p. 64)",
    "Hazard (p. 17)",
    "Pellets",
    "Burrow",
    "Pheromones",
    "Carcass",
    "Polished surface",
    "Chewed plants ",
    "Pollen",
    "Claw marks",
    "Ritual remnants",
    "Clothing (p. 40)",
    "Saliva",
    "Cocoons",
    "Scales",
    "Crushed grass",
    "Scent (p. 66)",
    "Dams",
    "Scorch marks",
    "Diagrams",
    "Shadows",
    "Digging sounds ",
    "Shed skin",
    "Droppings",
    "Shells",
    "Droppings scent ",
    "Signaling sounds",
    "Eggs",
    "Singing",
    "Eggshells",
    "Slime trails",
    "Element trail (p. 29) ",
    "Sound (p. 66)",
    "Fabric scrap (p. 41) ",
    "Stalking sounds",
    "Fallen trees",
    "Stripped bark",
    "Feathers",
    "Symbols",
    "Fighting sounds ",
    "Teeth marks",
    "Fire pit",
    "Texture trail (p. 36)",
    "Flags",
    "Tool (p. 39)",
    "Fleeing prey",
    "Trails",
    "Food cache",
    "Traps",
    "Food scent",
    "Trash",
    "Food scraps (p. 49) ",
    "Tree scratches",
    "Footprints",
    "Tunnels",
    "Fruit pits",
    "Urine",
    "Fur",
    "Urine scent",
    "Graffiti",
    "Voices",
    "Graves",
    "Wallows",
    "Hives",
    "Warning scent",
    "Hunters",
    "Warning sounds",
    "Injured prey",
    "Warnings",
    "Lair",
    "Wax",
    "Lair scent",
    "Weapon (p. 43)",
    "Letters",
    "Webs",
    "Mating ground ",
    "Wings",
    "Mechanism (p. 17) ",
    "Worshipers",
]

signs.sort()
