tools = [
    "Acid flask",
    "Animal scent",
    "Antitoxin",
    "Astrolabe",
    "Backpack",
    "Bandolier",
    "Bear trap",
    "Bedroll",
    "Beeswax",
    "Bell",
    "Bellows",
    "Birdcage",
    "Blank book",
    "Blanket",
    "Block and tackle",
    "Boltcutters",
    "Bottle",
    "Bucket",
    "Bullseye lantern",
    "Caltrops",
    "Candle",
    "Chain",
    "Chalk",
    "Chisel",
    "Climbing hook",
    "Compass",
    "Copper wire",
    "Crowbar",
    "Dice",
    "Door ram",
    "Ear trumpet",
    "Ether",
    "Fire oil",
    "Fishing hook",
    "Flashbomb",
    "Flashpowder",
    "Garlic",
    "Glue",
    "Grappling hook",
    "Grease",
    "Hacksaw",
    "Hammer",
    "Hand drill",
    "Hemp rope",
    "Hog holder",
    "Hooded lantern",
    "Hound",
    "Hourglass",
    "Incense",
    "Iron pot",
    "Iron tongs",
    "Lantern",
    "Large sack",
    "Lockpicks",
    "Lodestone",
    "Magnifying lens",
    "Manacles",
    "Marbles",
    "Metal File",
    "Mortar and pestle",
    "Mule",
    "Net",
    "Padlock and key",
    "Pen and ink",
    "Perfume",
    "Pickaxe",
    "Pitchfork",
    "Piton",
    "Pliers",
    "Poison",
    "Pole (10’)",
    "Rat",
    "Rum",
    "Scissors",
    "Sealing wax",
    "Sewing needle",
    "Sextant",
    "Shovel",
    "Silk rope",
    "Sledgehammer",
    "Smokebomb",
    "Smoked goggles",
    "Soap",
    "Spikes",
    "Spyglass",
    "Stake",
    "Steel mirror",
    "Sundial",
    "Tent",
    "Thick gloves",
    "Thurible",
    "Tinderbox",
    "Torch",
    "Trumpet",
    "Twine",
    "Vial",
    "Waterskin",
    "Whetstone",
    "Whistle",
    "Wolfsbane",
]
