treasures = [
    "Alchemical device ",
    "Mural",
    "Amulet",
    "Music box",
    "Armor",
    "Necklace",
    "Arrows",
    "Organ (p. 64)",
    "Astrolabe",
    "Orrery",
    "Belt",
    "Painting",
    "Blackmail",
    "Pen",
    "Blueprints",
    "Perfume",
    "Book (p. 40)",
    "Pipe",
    "Bow",
    "Planar map",
    "Bowl",
    "Porcelain figure",
    "Bracelet",
    "Potion (p. 35)",
    "Business record ",
    "Prayer book",
    "Calligraphy",
    "Printing block",
    "Candelabra",
    "Rare coin",
    "Carpet",
    "Relic",
    "Celestial map",
    "Reward (p. 51)",
    "Chalice",
    "Ring",
    "Chandelier",
    "Royal robes",
    "Clock",
    "Scabbard",
    "Clothing (p. 40)",
    "Scientific device",
    "Codpiece",
    "Scrimshaw",
    "Comb",
    "Sextant",
    "Compass",
    "Sheet music",
    "Contract",
    "Shield",
    "Couch",
    "Shoes",
    "Crown",
    "Signet ring",
    "Crystal",
    "Silk",
    "Dagger",
    "Silverware",
    "Deed",
    "Snuffbox",
    "Doll",
    "Spear",
    "Dress",
    "Spell (pp. 22-25))",
    "Earrings",
    "Spices",
    "Embroidery",
    "Spyglass",
    "Fine china",
    "Stained glass",
    "Fine liquor",
    "State secrets",
    "Furs",
    "Stone statue",
    "Gaming set",
    "Sword",
    "Gemstone",
    "Table",
    "Helmet",
    "Tapestry",
    "Ingredient (p. 37) ",
    "Taxidermy",
    "Instrument",
    "Tea set",
    "Ivory carving",
    "Telescope",
    "Lamp",
    "Throne",
    "Letter",
    "Treasure map",
    "Material (p. 42)",
    "Trophy",
    "Medal",
    "Trunk",
    "Mirror",
    "Vase",
    "Monster skin (p. 61) ",
    "Watch",
    "Mosaic",
    "Weapon (p. 43)",
]

treasures.sort()
