weapons = [
    "Arming sword ",
    "Longsword",
    "Backsword",
    "Lucerne hammer",
    "Bardiche",
    "Mace",
    "Baton",
    "Machete",
    "Battleaxe",
    "Man catcher",
    "Beheading sword ",
    "Maul",
    "Bill hook",
    "Messer",
    "Blowgun",
    "Meteor hammer",
    "Blowpipe",
    "Military fork",
    "Boar spear",
    "Morningstar",
    "Bolas",
    "Nunchaku",
    "Boomerang",
    "Pickaxe",
    "Brass knuckles ",
    "Pike",
    "Bullet crossbow ",
    "Poleaxe",
    "Butterfly sword ",
    "Push dagger",
    "Censer flail",
    "Ranseur",
    "Cestus",
    "Rapier",
    "Chain whip",
    "Recurve bow",
    "Chakram",
    "Rondel dagger",
    "Claymore",
    "Rope dart",
    "Club",
    "Sabre",
    "Crossbow",
    "Sai",
    "Cutlass",
    "Scimitar",
    "Dagger",
    "Scourge",
    "Dao",
    "Shortbow",
    "Deer horn knives ",
    "Shortsword",
    "Dirk",
    "Shuriken",
    "Double flail",
    "Sickle",
    "Emeici",
    "Side sword",
    "Falchion",
    "Sling",
    "Flail",
    "Slingshot",
    "Flambard",
    "Spear",
    "Flying claws",
    "Staff",
    "Gauntlet sword ",
    "Stave sling",
    "Gladius",
    "Stiletto",
    "Glaive",
    "Swordstaff",
    "Halberd",
    "Tanto",
    "Hatchet",
    "Three-part staff",
    "Hook sword",
    "Throwing axe",
    "Horsebow",
    "Throwing knife",
    "Hunting knife",
    "Tiger claws",
    "Ice pick",
    "Tonfa",
    "Javelin",
    "Trident",
    "Katana",
    "Triple flail",
    "Katar",
    "Wakizashi",
    "Kopesh",
    "War scythe",
    "Kukri",
    "Warhammer",
    "Lance",
    "Warpick",
    "Lasso",
    "Whip",
    "Longbow",
    "Zweihander",
]

weapons.sort()
