from random import choice
from dataclasses import dataclass


qualities = (
    "Bashing",
    "Binding",
    "Absorbing",
    "Adhering",
    "Bewildering",
    "Armouring",
    "Addicting",
    "Calming",
    "Blinding",
    "Banishing",
    "Blackening",
    "Charming",
    "Burning",
    "Concealing",
    "Blossoming",
    "Commanding",
    "Choking",
    "Countering",
    "Cacophonous",
    "Enticing",
    "Consuming",
    "Curing",
    "Dazzling",
    "Horrifying",
    "Corroding",
    "Cushioning",
    "Dividing",
    "Hysterical",
    "Crushing",
    "Deflecting",
    "Duplicating",
    "Maddening",
    "Deafening",
    "Disappearing",
    "Evolving",
    "Mesmerising",
    "Detonating",
    "Disarming",
    "Extinguishing",
    "Mocking",
    "Disintegrating",
    "Disguising",
    "Fusing",
    "Revealing",
    "Draining",
    "Entangling",
    "Ghostly",
    "Whirling",
    "Electrifying",
    "Warding",
    "Grasping",
    "Slithering",
    "Excruciating",
    "Guarding",
    "Inflating",
    "Dreaming",
    "Freezing",
    "Shielding",
    "Inverting",
    "Encoding",
    "Withering",
    "Healing",
    "Invulnerable",
    "Enraging",
    "Impaling",
    "Hindering",
    "Prismatic",
    "Pulsing",
    "Imprisoning",
    "Invigorating",
    "Transmuting",
    "Saddening",
    "Infecting",
    "Mending",
    "Teleporting",
    "Scrying",
    "Liquefying",
    "Nullifying",
    "Whispering",
    "Subtle",
)
forms = (
    "Claw",
    "Salt",
    "Hail",
    "Chaos",
    "Clay",
    "Sand",
    "Haze",
    "Cold",
    "Crystal",
    "Silk",
    "Wind",
    "Darkness",
    "Flesh",
    "Skin",
    "Shard",
    "Prism",
    "Mould",
    "Soil",
    "Miasma",
    "Distortion",
    "Flower",
    "Stone",
    "Perfume",
    "Dream",
    "Fungus",
    "Sugar",
    "Pollen",
    "River",
    "Fruit",
    "Ray",
    "Plague",
    "Fire",
    "Glass",
    "Thorn",
    "Rain",
    "Frost",
    "Ice",
    "Vine",
    "Sandstorm",
    "Ghost",
    "Iron",
    "Rust",
    "Orb",
    "Gravity",
    "Ivory",
    "Void",
    "Bolt",
    "Growth",
    "Leaf",
    "Ash",
    "Snow",
    "Song",
    "Stone",
    "Blizzard",
    "Smoke",
    "Voice",
    "Moss",
    "Breath",
    "Arc",
    "Light",
    "Hand",
    "Cloud",
    "Sphere",
    "Lightning",
    "Gaze",
    "Dust",
    "Shield",
    "Thread",
    "Roots",
    "Fog",
    "Helix",
    "Parasite",
    "Beam",
    "Mist",
    "Web",
    "Paradox",
    "Cascade",
    "Fragrance",
    "Wound",
    "Entropy",
)

sources = (
    "Mystical Crystal",
    "Ritual Cannibalism",
    "Psychoactive Fungus",
    "Nanomachine Infection",
    "Irradiated at Birth",
    "Dream Quest",
    "Parastic Spirit Entity",
    "Mental Mutation",
    "Addictive Rare Drug",
    "Brain Implants",
    "Devouring Memories",
    "Brain Surgery",
    "Second Sight",
    "Secret Religion",
    "Ancient Mask",
    "Cursed Ring",
    "Born During Eclipse",
    "Found Weird Orb",
    "Beheld Azathoth, the Daemon Sultan",
    "Studied in Lost Archives",
)
gifts = (
    "Telekinesis",
    "Pyrokinesis",
    "Telepathy",
    "Memory Extraction",
    "Mind Control",
    "Meditation",
    "Invisibility",
    "Astral Projection",
    "Healing Hands",
    "Paralysing Touch",
    "Eye Lasers",
    "Augury",
    "Inhuman Speed",
    "Force Wall",
    "Generate Lightning",
    "Ultrasonic Scream",
    "Create Paradox-Clone",
    "Summon Orbs",
    "Cryokinesis",
    "Induce Sleep",
)


@dataclass
class MysticGift:
    source: str
    gift: str

    def __repr__(self):
        return f"Mystic Gift. Source {self.source}. Gift: {self.gift}."


@dataclass
class RandomGift:
    quality: str
    form: str

    def __repr__(self):
        return f"Mystic Gift: {self.quality} {self.form}"


def gen_mystery_gift():
    source = choice(sources)
    gift = choice(gifts)
    return MysticGift(source, gift)


def gen_random_gift():
    quality = choice(qualities)
    form = choice(forms)
    return RandomGift(quality, form)
