from random import choice, sample, randint
from dataclasses import dataclass
from .ancestries import ANCESTRIES


ancestry_manner_voice_drive_table = (
    (
        "True-kin",
        "Abrasive",
        "Breathy",
        "Addicted to Drug (p.xx)",
    ),
    (
        "True-kin",
        "Arrogant",
        "Shrill",
        "Religious Pilgrimage",
    ),
    (
        "Cacogen",
        "Assertive",
        "Deep",
        "Seeking Revenge",
    ),
    (
        "Cacogen",
        "Charismatic",
        "Sonorous",
        "Pay Off Debts",
    ),
    (
        "Cacogen",
        "Daring",
        "Mumbles",
        "Fleeing the Law",
    ),
    (
        "Newbeast",
        "Decadent",
        "Spits",
        "Collect a Debt",
    ),
    (
        "Newbeast",
        "Eloquent",
        "Sing-song",
        "Craves Fame",
    ),
    (
        "Mycomorph",
        "Extravagant",
        "Drawls",
        "Craves Material Wealth",
    ),
    (
        "Mycomorph",
        "Hedonistic",
        "Raspy",
        "Craves Knowledge",
    ),
    (
        "Synth",
        "Impulsive",
        "Whispers",
        "Craves Power",
    ),
    (
        "Synth",
        "Irritable",
        "Hasty",
        "Seeks Downfall of a Rival",
    ),
    (
        "Synth",
        "Melancholy",
        "Weird Laugh",
        "Hunting Escaped Prisoner",
    ),
    (
        "Faa Nomad",
        "Paranoid",
        "Monotone",
        "Seeking Missing Bond (see below)",
    ),
    (
        "Faa Nomad",
        "Quiet",
        "Jovial",
        "Searching for Fabled Lost Location",
    ),
    (
        "Cacklemaw Exile",
        "Religious",
        "Sinister",
        "Find Cure for Rare Disease",
    ),
    (
        "Cacklemaw Exile",
        "Romantic",
        "Husky",
        "Unrequited Love (Same Ancestry)",
    ),
    (
        "Neobloom",
        "Scholarly",
        "Smoky",
        "Forbidden Love (Different Ancestry)",
    ),
    (
        "Neobloom",
        "Stern",
        "Smooth",
        "Seeks Heroic Death",
    ),
    (
        "Planeyfolk",
        "Vain",
        "Gravelly",
        "Compose Great Poem",
    ),
    (
        "Lithling",
        "Volatile",
        "Can’t Speak",
        "Create Great Art",
    ),
)

bonds = (
    "Mother",
    "Father",
    "Sister",
    "Brother",
    "Uncle",
    "Aunt",
    "Spouse",
    "Eldest Child",
    "Middle Child",
    "Youngest Child",
    "Grandfather",
    "Grandmother",
    "Own Clone",
    "Adopted Child",
    "Mentor Figure",
    "Pet",
    "Tame Monster",
    "Childhood Friend",
    "Childhood Friend Simulating Hologram",
    "Inanimate Object Which They Talk To",
)

faiths = (
    "Church of Promised Sun",
    "Church of Promised Sun",
    "Church of the Everbleeding Wound",
    "Church of the Everbleeding Wound",
    "Vaa, Blue Goddess of Empty Spaces",
    "Vaa, Blue Goddess of Empty Spaces",
    "Seekers of Eyeless Wisdom",
    "Seekers of Eyeless Wisdom",
    "Binary Devotion",
    "Binary Devotion",
    "Titan Cult",
    "Autarch Cult",
    "Ghoul Cult",
    "Fungus Cult",
    "Grim-Grin Worshipper",
    "Worships Giant Immortal Animal",
    "Worships Only Themselves",
    "Worships Quantum Daemon",
    "Brotherhood of the Black Sun",
    "Brotherhood of the Black Sun",
)

reputations = (
    "Hegemony (Hero)",
    "Hegemony (Traitor)",
    "Hegemony (Outlaw, Wanted By)",
    "Faa Nomads (Hero)",
    "Faa Nomads (Traitor)",
    "Faa Nomads (Outlaw, Wanted By)",
    "Cacklemaw (Beloved)",
    "Cacklemaw (Hated)",
    "Seekers of Eyeless Wisdom (Beloved)",
    "Seekers of Eyeless Wisdom (Hated)",
    "Court of the Jigsaw Autarch (Loved)",
    "Court of the Jigsaw Autarch (Hated)",
    "Titan Cults (Loved)",
    "Titan Cults (Hated)",
    "Lithic Lyceum (Loved)",
    "Lithic Lyceum (Hated)",
    "College of Indigo Tigers (Loved)",
    "College of Indigo Tigers (Hated)",
    "Brotherhood of the Black Sun (Loved)",
    "Brotherhood of the Black Sun (Hated)",
)

names_of_vaarn = (
    "Abiah",
    "Addi",
    "Ambrosia",
    "Abandon",
    "Ahlber",
    "Agupta",
    "Andromeda",
    "Achefoot",
    "Amur",
    "Alsafil",
    "Ash",
    "Alzina",
    "Angda",
    "Andra",
    "Basik",
    "Anthur",
    "Arnfreyn",
    "Anníva",
    "Be-True",
    "Aran",
    "Arthar",
    "Anukesha",
    "Big-Spit",
    "Arb",
    "Azuko",
    "Arael",
    "Bilge",
    "Ariyei",
    "Baptist",
    "Aran",
    "Bleakblade",
    "Asaj",
    "Bathiel",
    "Arare",
    "Blackchapel",
    "Aumatell",
    "Beitus",
    "Arjuna",
    "Blue",
    "Awasad",
    "Bellin",
    "Ashwari",
    "Boots",
    "Bana",
    "Bethod",
    "Aubeahi",
    "Bronzeguts",
    "Bargh",
    "Bhutaro",
    "Augustinia",
    "Brown",
    "Basai",
    "Boaz",
    "Auri",
    "Chairman",
    "Berruzo",
    "Brinnr",
    "Auriel",
    "Conch",
    "Bitar",
    "Byzou",
    "Avalon",
    "Crab",
    "Blame",
    "Birk",
    "Aveyn",
    "Crow",
    "Blueback",
    "Cassian",
    "Beneva",
    "Cusp",
    "Bountyfull",
    "Corwin",
    "Bhakali",
    "Dog",
    "Brazen",
    "Cossmoss",
    "Bjarta",
    "Domino",
    "Brunan",
    "Cyriak",
    "Caela",
    "Duke",
    "Cawl",
    "Estaro",
    "Cayendra",
    "Easter",
    "Castarle",
    "Everney",
    "Chah",
    "Faithful",
    "Chasa",
    "Fane",
    "Elel",
    "Feasts-With-Fools",
    "Coma",
    "Farouk",
    "Elisebet",
    "Foxglory",
    "Comabella",
    "Faustyn",
    "Emizan",
    "Glass Jaw",
    "Cunill",
    "Fflaa",
    "Fendrel",
    "Glitch",
    "Dragger",
    "Frum",
    "Fingel",
    "Goldtongue",
    "Exald",
    "Fulgold",
    "Fomanyana",
    "Goodluck",
    "Faswar",
    "Gawain",
    "Freyr",
    "Gorgeous",
    "Ferrater",
    "Getakehiko",
    "Grence",
    "Grace",
    "Fouler",
    "Gorse",
    "Hadraklona",
    "Gravedigger",
    "Fraguas",
    "Grick",
    "Haulë",
    "Green",
    "Fres",
    "Haldib",
    "Helis",
    "Heartsease",
    "Fusta",
    "Hikaru",
    "Hrishna",
    "Holiday",
    "Garau",
    "Indo",
    "Idrika",
    "Indigo",
    "Gharikh",
    "Ish",
    "Imrahma",
    "Iris",
    "Ghogu",
    "Jarl",
    "Indur",
    "Jigsaw",
    "Gnomonborn",
    "Jask",
    "Irmina",
    "Jingle",
    "Greathall",
    "Johar",
    "Isandrea",
    "Knot",
    "Greenlance",
    "Juvenus",
    "Ishili",
    "Koan",
    "Grey",
    "Kaphil",
    "Ishtar",
    "Light-The-Lantern",
    "Gura",
    "Katsu",
    "Isiopeia",
    "Lilt",
    "Hanger",
    "Kayuko",
    "Isolde",
    "Little-Spit",
    "Hasikh",
    "Kircha",
    "Jacintha",
    "Lovely",
    "Hiccup",
    "Kondir",
    "Jikinio",
    "Longtooth",
    "Horehound",
    "Lachiel",
    "Jikit",
    "Look-Home",
    "Hush",
    "Lew",
    "Jindel",
    "Looks-to-the-Dawn",
    "Ishish",
    "Lucjan",
    "Julinna",
    "Lotus",
    "Kinsella",
    "Masaor",
    "Jupindi",
    "Lucky-And-True",
    "Latch",
    "Masaori",
    "Kaori",
    "Mandala",
    "Levijeans",
    "Masatorald",
    "Karra",
    "Many-Moons",
    "Lonrot",
    "Masios",
    "Kathik",
    "Merry",
    "Mairg",
    "Matheo",
    "Lami",
    "Mirage",
    "Make-Peace",
    "Maximiel",
    "Leloryl",
    "Morrow",
    "Marsal",
    "Meussau",
    "Lirockite",
    "Moth",
    "Mellod",
    "Minius",
    "Lumo",
    "Nectar",
    "Merry",
    "Mundur",
    "Lunahl",
    "Nine-Eyes",
    "Miaza",
    "Nihallen",
    "Maeri",
    "Ochre",
    "Miribiki",
    "Nörril",
    "Malamue",
    "Opal",
    "Morey",
    "Okhov",
    "Maleli",
    "Paledawn",
    "Moudan",
    "Ollon",
    "Maneva",
    "Pentecost",
    "Nafour",
    "Otger",
    "Mayana",
    "Pincher",
    "No-Luck",
    "Otringen",
    "Meena",
    "Pinkie",
    "Noro",
    "Paeon",
    "Menka",
    "Prays-For-Rain",
    "Osk",
    "Parcas",
    "Mneme",
    "Provost",
    "Pallak",
    "Peneb",
    "Moneflower",
    "Puke",
    "Paradise",
    "Phand",
    "Mosefina",
    "Purple-Dusk",
    "Pepsi-Kola",
    "Porthim",
    "Murthwaite",
    "Quill",
    "Pig-Wise",
    "Pushani",
    "Muthael",
    "Raven",
    "Posas",
    "Qeterius",
    "Nahl",
    "Ribs",
    "Prince",
    "Quarqus",
    "Nehmet",
    "Saffron",
    "Recto",
    "Quiel",
    "Nisite",
    "Saint",
    "Richter",
    "Rahamen",
    "Ojasin",
    "Salt",
    "Roper",
    "Robeflory",
    "Olanele",
    "Seeks-The-Path",
    "Sabbad",
    "Ryusuko",
    "Othoba",
    "Seven",
    "Sanaye",
    "Saintjohn",
    "Penta",
    "Silver",
    "Scar",
    "Saintpaul",
    "Poe",
    "Sir-Madam",
    "Seagreen",
    "Salar",
    "Pomory",
    "Skybreak",
    "Sharas",
    "Salka",
    "Puloma",
    "Sleeps-In-Amber",
    "Shases",
    "Seisuke",
    "Pupienua",
    "Sloe",
    "Shiningcoin",
    "Simorpheus",
    "Qusamira",
    "Slowly",
    "Sleba",
    "Solomon",
    "Rolfinnura",
    "Sovereign",
    "Sledge",
    "Sprinus",
    "Selal",
    "Static",
    "Stillborn",
    "Symeon",
    "Septi",
    "Stoutfoot",
    "Stirrup",
    "Takami",
    "Solasa",
    "Stonecipher",
    "Sunbearer",
    "Tarut",
    "Solm",
    "Swan",
    "Thule",
    "Taysk",
    "Sophla",
    "Teal",
    "Trulls",
    "Trian",
    "Soraila",
    "Ten-Stars",
    "Truth",
    "Turms",
    "Tillux",
    "Trinity",
    "Umber",
    "Tyche",
    "Vespassia",
    "Tusk",
    "Utterly",
    "Tytus",
    "Xhiva",
    "Two Times",
    "Valvern",
    "Ulmon",
    "Ximinta",
    "Ultra",
    "Verdagu",
    "Vitus",
    "Yathartha",
    "Vespers",
    "Vurt",
    "Vult",
    "Yoshar",
    "Warthog",
    "Whitsand",
    "Weston",
    "Zeta",
    "White-Eye",
    "Windblown",
    "Xylenes",
    "Zoelel",
    "Whiteknife",
    "Wing",
    "Yarapis",
    "Zofi",
    "Winterlamp",
    "Xalabar",
    "Yasuke",
    "Zumi",
    "Wren",
    "Yawngawp",
    "Zlator",
    "Zuzanna",
    "Zooth",
    "Xan Zophiel",
)

npc_careers = (
    (
        "Actor",
        "Wig, False Nose, Book of Playscripts",
    ),
    (
        "Adorcist",
        "GIFT: Embrace Spirit, Ritual Hat (+1 EGO while worn), Prayer Beads",
    ),
    (
        "Aeromancer",
        "GIFT: Raise the Winds, Billowing Cape (11 AV), Wind Instrument",
    ),
    (
        "Alchemist",
        "Hazard Wrap (AV 12), Vial of Acid, Vial of Poison (d10 TOX)",
    ),
    (
        "Ape Catcher",
        "Weighted Net (Target DEX saves vs Entangled), Bludgeon (d6), Ape Snares (3)",
    ),
    (
        "Apostle",
        "Holy Text, Sacred Icon, Incense",
    ),
    (
        "Artifex",
        "Welding Tools, Pliers, Random Exotica (p.xx)",
    ),
    (
        "Assassin",
        "Hidden Blade (d6), Silenced Pistol (d6), Poison Pill (d8 TOX)",
    ),
    (
        "Astronomer",
        "Astrolabe, Star Map, Telescope",
    ),
    (
        "Baker",
        "Rolling Pin (d6), Bag of Flour, Fresh Loaves (3)",
    ),
    (
        "Barber-surgeon",
        "Razor (d6), Badger Hair Brush, Copper Bowl",
    ),
    (
        "Barkeep",
        "Shotgun (d8, 2 slots), Amphorae of Wine, Ice-cube Maker",
    ),
    (
        "Bastard Farmer",
        "Cryo-Flask (Human Embryo), Cryo-Flask (Empty), Pistol (d6)",
    ),
    (
        "Beggar",
        "Alms Bowl, Trained Ferret (Level 1, AV 11, Bite (d4)), Club (d6)",
    ),
    (
        "Blacksmith",
        "Great Hammer (d8, 2 slots), Sky-Iron Helm (+1 AV), Tongs",
    ),
    (
        "Bookbinder",
        "Marbled Paper, Awl (d4), Random Book",
    ),
    (
        "Butcher",
        "Cleaver (d6), Salt, String of Zorse-meat Sausages",
    ),
    (
        "Caravan Guard",
        "Lizardskin Jerkin (AV 13, 3 slots), Desert Rifle (d8, 2 slots), Binoculars",
    ),
    (
        "Carpenter",
        "Saw, Hammer (d6), Nails (100)",
    ),
    (
        "Charioteer",
        "Racing Cape (+1 EGO), Whip (d6), Gilded Trophy",
    ),
    (
        "Chromepriest",
        "Mirrored Robes (AV 11, half damage from Beams), Random Cybernetic Implant, Random Cybernetic Implant",
    ),
    (
        "Clairvoyant",
        "Three-eyed Mask (+1 AV), GIFT: Second Sight, GIFT: Telepathy",
    ),
    (
        "Clerk",
        "Stylus, Wax Tablet, Abacaus",
    ),
    (
        "Clockmaker",
        "Magnifying Glasses, Precision Tools, Broken Clock",
    ),
    (
        "Clone Catcher",
        "Handcannon (d8, 2 slots), Genepeeker, Flask of Whiskey",
    ),
    (
        "Clown",
        "Jolly Bludgeon (d6), Foolish Attire, Mock Gun (fires confetti)",
    ),
    (
        "Confessor",
        "Purple Robes (11 AV), Book of Confessions, Absolving Oil",
    ),
    (
        "Cook",
        "Kitchen Knife (d6), Cast Iron Skillet, Rare Spices (3)",
    ),
    (
        "Courtesan",
        "Wig, Makeup, Prophylactics",
    ),
    (
        "Cybernetics Surgeon",
        "Scalpel (d6), Antibiotics, Random Cybernetic Implant (p.xx)",
    ),
    (
        "Cyromancer",
        "Thermo-equilibrium Suit (AV 12, Immune to Heat/Cold), GIFT: Cyrokinesis",
    ),
    (
        "Daemonologist",
        "Ritual Dagger (d4), Ritual Chalk, Book of Quantum Daemon Names",
    ),
    (
        "Diviner",
        "GIFT: Augury, Golden Bowl, Flagon of Prophetic Wine",
    ),
    (
        "Doomsinger",
        "GIFT: Deathsong, Black Robes (AV 11), Vocal Amplifier (d6 sonic weapon)",
    ),
    (
        "Drunkard",
        "Bottle of Strong Liquor (flammable), Set of Playing Cards, Automatic Cocktail Maker",
    ),
    (
        "Duellist",
        "Duelling Gloves (white), Rapier (d6), Two Duelling Pistols (d8, one shot each)",
    ),
    (
        "Embroiderer",
        "War Needle (d6, concealed), Embroidered Brigandine (13 AV), Half-finished Tapestry",
    ),
    (
        "Exorcist",
        "GIFT: Rebuke Spirit, Exorcist’s Bells, White Sword (d8)",
    ),
    (
        "Faith Healer",
        "GIFT: Healing Hands, Acupuncture Kit, 3 Cleansing Orbs (neutralise poison)",
    ),
    (
        "Falconer",
        "Leather Glove, Training Whistle, Hooded Falcon (Level 1, AV 17, Peck (d4))",
    ),
    (
        "Fire Singer",
        "Scarlet Robes (AV 11, 1 slot, half damage from flames), Flameburst Mask (+1 AV), GIFT: Pyrokinesis",
    ),
    (
        "Flagellant",
        "Scourge (d6), Doomsday Pamphlet, Insta-Scab Clotting Spray (3 doses)",
    ),
    (
        "Fungusmonger",
        "Sporegun (d8, 2 slots), Deathcap Mushroom (d12 TOX), Exotica: Dried Mycomorph",
    ),
    (
        "Gambler",
        "Flamboyant Scarf, Loaded Dice, Deck of Cards",
    ),
    (
        "Gladiator",
        "Showy AV (AV 15, 5 slots), Flashy Weapon (d8, 2 slots), Grisly Trophy",
    ),
    (
        "Goatherd",
        "Shepherd’s Staff (d6), Loyal Goat (Level 1, AV 11, d4 butt), Goat Cheese",
    ),
    (
        "Graverobber",
        "Shovel (d6), Crowbar (d6), Hooded Lantern",
    ),
    (
        "Gunslinger",
        "Revolver (d6), Scattergun (d8, close), Wide-brimmed Hat (+1 EGO)",
    ),
    (
        "Hangman",
        "Black Hood, Long Rope, Pack of Cigarettes",
    ),
    (
        "Hegemony Deserter",
        "Hegemony Rifle (d8, 2 slots), Hegemony AV (Amour 14, 4 slots), Cybernetic Implant",
    ),
    (
        "Hermit",
        "Walking Staff (d8, 2 slots), Random Gift",
    ),
    (
        "High Priest",
        "Ornate Headpiece (+1 AV), Ornate Robes (AV 13, 3 slots), Ritual Mace (d8, 2 slots)",
    ),
    (
        "Hunter",
        "Crossbow (d8, 2 slots), Bird-mimic Whistle, Snap-traps (3)",
    ),
    (
        "Hydromancer",
        "GIFT: Water Manipulation, Aquamarine Robes (AV 11), Glass Headdress (+1 AV, shatters if opponent rolls a 20)",
    ),
    (
        "Hypergeometer",
        "Manifold Dagger (d6, hypergeometric), Hypergeometric Ruler, GIFT: Carve Portal",
    ),
    (
        "Illusionist",
        "Mirrored Shield (+1 AV), Radiant Lantern, GIFT: Light Manipulation",
    ),
    (
        "Inquisitor",
        "Querulous Blade (d6), Truth Serum (3 doses), Hegemony Law Books",
    ),
    (
        "Leechmonger",
        "Tongs, Plastic Bags, 3 Medicinal Leeches (cure poison/disease, die after use)",
    ),
    (
        "Lithomancer",
        "Petrified Robes (AV 16, 6 slots), GIFT: Stone Manipulation",
    ),
    (
        "Lizard Rancher",
        "Lasso, Lizard Treats (5), Tame War Lizard (Level 1, AV 14, d6 bite)",
    ),
    (
        "Mask Maker",
        "Unsettling Mask, Jaunty Mask, Holy Mask",
    ),
    (
        "Medium",
        "Scrying Crystal, Ritual Oils, GIFT: Spirit Calling",
    ),
    (
        "Mercenary",
        "Gambeson (AV 12, 2 slots), Plasma Fusil (d8, 2 slots), 3 Plasma Grenades (d10 blast)",
    ),
    (
        "Miner",
        "Pick-axe (d6), Illuminating Helm (+1 AV, creates light), Caged Finch",
    ),
    (
        "Monk",
        "Monastic Robes (AV 11), Icon of Random Petty God, Illuminated Manuscript",
    ),
    (
        "Musician",
        "Sitar, Electric Harp, Book of Poems",
    ),
    (
        "Mystic",
        "Begging Bowl, Random GIFT, Random GIFT",
    ),
    (
        "Necromancer",
        "Skull-helmed Garb (AV 14, 4 slots), Sable Sword (d8, 2 slots), GIFT: Brief Resurrection",
    ),
    (
        "Olive Merchant",
        "Debt Ledger, Set of Scales, 300 preserved olives (3 slots)",
    ),
    (
        "Oracle",
        "Blindfold, Random Drug, GIFT: Precognition",
    ),
    (
        "Outlaw",
        "Rifle (d8, 2 slots), Grenades (d10 blast, 3), Shabby Leather (AV 13, 3 slots)",
    ),
    (
        "Painter",
        "Set of Brushes, Oil Paints, Half-finished Masterpiece",
    ),
    (
        "Philosopher",
        "Orator’s Mask (amplifies voice), Scribbled Treatise, Random Book",
    ),
    (
        "Poacher",
        "Bow (d6), Animal Traps (3), Handheld Motion Detector",
    ),
    (
        "Priest of Sevenscore",
        "MoonsMoondark Mask (AV +1), Waning Blade (d6), Draught of Merciful Tranquility (CON Save vs Death)",
    ),
    (
        "Priest of the Promised",
        "Sun Sunburst Mask (AV +1), Sun Staff (d6), Medicinal Gourds (3, d8 heal)",
    ),
    (
        "Professional Lamenter",
        "Somber Garb (AV 11), Lachrymax Pills (3 doses, induces intense grief), Liquid Sunshine (3 syringes, induces manic euphoria)",
    ),
    (
        "Psychonaut",
        "Random Gift, Random Drug, Random Drug",
    ),
    (
        "Relic Thief",
        "Grappling Hook Gun, Blackened Dagger (d6), Void-Saint’s Pickled Finger",
    ),
    (
        "Sacred Executioner",
        "Greatsword (d10, 3 slots), Fuligin Robes (11 AV, ADV to hide in shadows), Holy Claw",
    ),
    (
        "Sailor (Void)",
        "Voidsuit (AV 12, 2 slots, Breathe in Vacuum), Suit-cutter (d6), Glowstone",
    ),
    (
        "Sailor (Wind-Barge)",
        "Compass, Coil of Rope, Flask of Whiskey (flammable)",
    ),
    (
        "Scavenger",
        "Metal Detector, Random Vault Trinket (p.xx)",
    ),
    (
        "Science-Mystic’s Apprentice",
        "Stolen Beam-pistol (d6, beam), Random GIFT, Random Drug",
    ),
    (
        "Scribe",
        "Stylus, Bottle of Ink, Autoglot Translator Unit",
    ),
    (
        "Sin Eater",
        "Ritual Dining Fork (d8, 2 slots), Large Napkin, Indigestible Sin Hidden In Box",
    ),
    (
        "Slave (Escaped)",
        "Broken Chains (d6)",
    ),
    (
        "Smuggler",
        "Revolver (d6), Forged Customs Forms, Counterfeit Water-Debt Tokens (10)",
    ),
    (
        "Spy",
        "Stylus-Gun (d6, resembles pen), Suicide Pill (d12 TOX), Cryptography Machine",
    ),
    (
        "Synth Hunter",
        "Basilisk-Pattern Shield (+1 AV, Synths DIS to hit wearer), Lightning Pistol (d6 electrical), 3 EMP Bombs (Synths CON save vs shutdown)",
    ),
    (
        "Synth-surgeon",
        "Surgeon’s Toolkit (remove 1 Wound from Synths per day), Memory Bank Backpack (+1 INT), Random Cybernetic Implant",
    ),
    (
        "Tanner",
        "Leather Coat (13 AV), Fleshing Knife (d6), Pumice Stone",
    ),
    (
        "Torturer",
        "Peeler (d6), Pliers (d6), Pain Amplifier Serum (3 doses)",
    ),
    (
        "Travelling Scholar",
        "Random Book, Random Book, Outdated Field Guide to Vaarn (2nd Edition)",
    ),
    (
        "Water Diviner",
        "Dowsing Rod, Scent-Amplifier Mask, Damp Detector",
    ),
    (
        "Watermonger",
        "Water Purification Tablets (x5), Water Wealth (3d20 rations)",
    ),
    (
        "Witch",
        "Iron Cauldron, TALLHAT™ Psionic Amplifier (+1 PSY), Random GIFT",
    ),
    (
        "Woodcarver",
        "Knife (d6), Chisel, Wooden Animal",
    ),
    (
        "Wormtamer",
        "Sandworm Bridle, Sandworm Stirrups, Thumper (Summons Sandworm on open sands, 4-in-6 Juvenile, 2-in-6 Adult)",
    ),
    (
        "Zeppelin Guard",
        "Blunderbore (d8, 2 slots), Grappling Hook and Rope, Parachute",
    ),
)


@dataclass
class NPC:
    ancestry: str
    manner: str
    voice: str
    drive: str
    bond: str
    faith: str
    faction_reputation: str
    name: str
    career_name: str
    items: str


def gen_npc():
    ancestry = choice(ancestry_manner_voice_drive_table)[0]
    manner = choice(ancestry_manner_voice_drive_table)[1]
    voice = choice(ancestry_manner_voice_drive_table)[2]
    drive = choice(ancestry_manner_voice_drive_table)[3]
    bond = choice(bonds)
    faith = choice(faiths)
    faction_reputation = choice(reputations)
    name = choice(names_of_vaarn)
    career_name, items = choice(npc_careers)

    return NPC(
        ancestry,
        manner,
        voice,
        drive,
        bond,
        faith,
        faction_reputation,
        name,
        career_name,
        items,
    )
