# Generated by Django 4.2.6 on 2023-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gradientdescent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monarch",
            name="current_stress",
            field=models.IntegerField(
                default=0, verbose_name="Monarch Current Stress Level"
            ),
        ),
    ]
