warped_beyond_regognition_tables = {
    "I search the room": {
        0: "Cyberbrain (serial # scratched off)",
        4: "Rubik’s cube: ejects a d100 x 100cr credchip if solved (if you have a real one, give it to the player scrambled)",
        8: "Rough diagram of the ship’s ventilation ducts taped to the wall",
        12: "A cat! It’s scared and hungry. Its name tag says “Rigby”",
        16: "5 doses of Graxomol, a powdered stim. +10% to Speed checks for 30 minutes",
        20: "Box of awful instant coffee",
        24: "Butane Torch",
        28: "1d10 SMG Clips",
        32: "Box of Antipsychotic Medication",
        36: "Handcuffs (open, no keys)",
        40: "Small shrine to ancient Sol with 1d10 votive candles",
        44: "1d10 prosthetic limbs (inert, for now)",
        48: "Book: Solarian Bible",
        52: "Book: Be Your Own Badass: Starting Your Own Mercenary Company",
        56: "Book: The Economics of Asteroid Mining",
        60: "Gold-plated multitool",
        64: "Pamphlet: Enlist in the Tannhäuser Protection Corps Today!",
        68: "Bottle of an obscure herbal liqueur",
        72: "1d10 Packets of BioGel",
        76: "1d10 Bottles of Dissocan",
        80: "Hidden stash of cyberfetish porn mags",
        84: "Naloxone overdose kit (6 syringes)",
        86: "Pile of pit fighter trading cards",
        88: "Smashed cybernetic diagnostic scanner",
        92: "High-powered cattle prod",
        94: "Cassette of bootleg hypertrap tracks",
        96: "Open pack of Biogel mixed with vodka",
        97: "Rimworld Liberation Front pamphlet",
        98: "Personal oxygen tank, full (1 hour)",
        99: "Unlabeled tin of cookies (THC-infused)",
    },
    "I search the body": {
        0: "1d10 Tannhäuser logo condoms",
        44: "Credchip (result x 100cr)",
        50: "Bottle of Dissocan, empty",
        55: "Bottle of Dissocan, half-empty (2 doses)",
        62: "Bottle of Dissocan, full (4 doses)",
        63: "Patch: BRAIN DRAIN (dripping brain)",
        64: "Patch: WET DECK (mop)",
        66: "Patch: HELLBENT (pentagram)",
        68: "Patch: Rabid Snarling Wolf",
        70: "Patch: Mandala Design",
        72: "Patch: GOOD FOR HEALTH / BAD FOR EDUCATION (pill)",
        73: "Book: The Stars, My Lovers",
        75: "Book: Grex’aa The Seductive Betelgeusian Spy",
        77: "Pouch of BioGel, half-empty",
        79: "Electronic Multitool",
        81: "Handcuff Keys",
        83: "Toothbrush with sharpened handle",
        85: "Book: Solarian Bible (heavily annotated)",
        86: "Book: Codex of The Universal Mechanistic",
        87: "Rusty box cutter",
        88: "Makeup case",
        89: "Cybernetic Diagnostic Scanner",
        90: "Lighter engraved with owner’s name",
        91: "Bottle of antidepressants",
        92: "Lime green lipstick (contains calming narcotic, reduces Stress by 1, addictive)",
        93: "Heavily modded vape pen",
        94: "Expensive-looking wristwatch set to a core world’s planetary time",
        95: "Well-loved stuffed animal",
        96: "Expensive-looking suede gloves",
        97: "Bandanna depicting an erotic scene involving an octopus",
        98: "Nerdy-looking augmented glasses that enhance low-light vision",
        99: "Figurine of a spacer saint",
    },
}

MODULES = {"Warped Beyond Recognition": warped_beyond_regognition_tables}
