adventuring_prospecting_twists = (
    "You learn a contradictory perspective about an adventure prospect you already knew",
    "The prospect is not as good as you hoped (this is not the real tomb of Gorm, merely a ruined library of some adherents)",
    "The location is harder to get to than you initially thought (it looked closer on the map, the way has become treacherous, there was no mention of this waist-deep mud)",
    "The information you have is out of date (the gatehouse has since collapsed), incorrect or dangerously misleading (the gnolls described in the source are actually undead gnoll servitors to a demon of want)",
    "Unfriendly parties conspire to ruin the adventurers’ plans",
    "Opportunistic ruffians plan to rob the party",
    "Political enemies conspire to levy a tax on your new wealth",
    "A jaded priest or guildmaster feels this stone is best left unturned and forbids you from exploring it",
    "The denizens of the adventure location have been warned of the adventurers’ approach and have made specific preparations",
    "Allies of the denizens at the adventure location (e.g. cultists in town) follow the characters to ambush them",
    "Rival adventurers form an expedition of their own and race you to the objective",
    "This information was placed here by the monster to draw prey to its lair",
)

dungeon_twists = (
    "The water was a lot deeper than you thought",
    "The water was a lot shallower than you thought",
    "The opening was a lot narrower than you thought…and now you’re stuck",
    "That “slight dip” in the floor turns out to be a bottomless chasm",
    "The floor drops away beneath your feet",
    "You run smack into a wall",
    "You trigger a trap that drops you into another area",
    "You trigger a trap that affects the whole party",
    "You trigger a trap that targets you",
    "You arrive at a dead end",
    "You’re lost",
    "You arrive at a place that looks exactly like what you’re looking for, but it’s not the place you’re looking for",
    "You take a wrong turn into a familiar area, but something here has changed",
    "The area starts to rapidly fill with water",
    "A cave-in blocks your path",
    "Noxious fumes fill the chamber you’re exploring",
    "Lava begins to seep up through the floor",
    "The air in this area is foul; you’re having trouble breathing",
    "The earth shifts, and a crevasse yawns before you",
)

gear_twists = (
    "Your pack rips, and something falls out",
    "Your pack upends, and everything falls out",
    "The heavy blow breaks something in your pack",
    "The heavy blow breaks your weapon",
    "You drop what you’re holding",
    "Your quiver spills its contents",
    "Your purse rips and spills its contents",
    "Your waterskin is punctured",
    "Your weapon bounces out of your hands and down a crevice",
    "You find something in your pack that should not be there",
    "Your armor gets caught on something, and now you’re stuck",
    "Your helmet falls off and careens away, lost forever",
    "Your shield gets wedged in a crevice or between two trees. Can’t…get it…loose",
    "Your boots get sucked off your feet by the viscous mud",
    "Your clothes are torn and filthy",
    "Something is stolen from you by a pickpocket or cutpurse",
)


invocation_twists = (
    "You are made mute",
    "You are blinded",
    "One of your limbs goes dead",
    "You attract the attention of a powerful theurge",
    "You attract the attention of a powerful demon",
    "You attract the attention of an Immortal",
    "Your invocation is corrupted and has the opposite effect",
    "Your relic shatters from the force of your invocation",
    "The effects of the invocation become permanent",
    "The invocation affects someone you didn’t intend",
    "Stigmata appear",
    "An Immortal’s mark is blazoned across your face",
    "A ghostly fire races from your hands and mouth and cascades across the ground. It burns terribly any who do not possess Urðr.",
    "You vomit forth a pestilence that swarms around all those without Urðr.",
    "You summon the ghosts of your dead parents",
    "You curse the soon-to-be-corpse to undeath",
)

magic_twists = (
    "Sulphurous smoke surrounds you, filling the room",
    "Your target glows with an eerie light, pulsing with power",
    "A shadow crawls forth from your heart and scuttles away into the darkness",
    "A deafening bang shakes your senses",
    "A wicked wind blows through the area, scattering anything not held down",
    "Your spell burns a bright, glowing blue hole in the fabric of the Shroud of Worlds",
    "An apocalyptic, magical storm rushes forth from your inept mouth and blights the land for hundreds of miles around",
    "You attract the attention of a powerful wizard",
    "You attract the attention of a nearby demon",
    "You start a fire that can’t be put out",
    "Your spell book bursts into flames",
    "The spell steals your voice, and you can no longer speak above a whisper",
    "You cast the inverse of what you intended to cast",
    "You cast a much more powerful version of what you were attempting. Too powerful",
    "The spell is permanent and out of control",
)

monster_twists = (
    "You attract the attention of something nearby",
    "You awaken something unnatural. It stalks off into the night on an unholy errand",
    "You attract the attention of everything nearby",
    "You stumble into its hunting grounds",
    "You find the creature hungry and desperate for food. It has a taste for: your rations, your animals, your hirelings, you",
    "You stumble onto it while it’s feeding",
    "You emerge to find it at bay, hunted by something worse",
    "The lair seems empty, until you see its young",
    "You realize you’re standing on something… that’s sleeping",
    "It bounds happily toward you, acting like an excited dog",
    "You find the creature wounded and insensate",
    "You find the creature grieving for its lost young",
    "You find the creature enraged. It rushes to attack",
)

talking_twists = (
    "You say the exact wrong thing, adding insult to injury",
    "You’re tongue-tied and can’t say a thing",
    "They offer to marry you",
    "They won’t take no for an answer",
    "They demand all of your loot",
    "They demand you disarm",
    "They demand you tell your secrets!",
    "They run in terror",
    "They summon their friends",
    "They summon their “pet”",
    "They summon their soldiers",
    "Lord Julius anoints you Anti-Pope, gathers his belongings and bids you farewell",
    "They put the crown on your head and wish you the best of luck",
    "They declare unending war upon you and all that you hold dear",
    "They cast a spell on you",
    "They say a prayer for you",
    "They behave in a generous and gracious manner",
    "They do all they can to help you",
    "They don’t suspect a thing",
    "They speak in your defense, even though you’re lying",
    "They feel great sadness and remorse, even though they did nothing and are blameless",
    "They’re not who you thought they were",
    "You overhear a private, secretive conversation",
    "You overhear loud boasting",
    "You’re accused of eavesdropping",
)

town_twists = (
    "You take a wrong turn",
    "You get mugged",
    "You stumble upon a crime",
    "Someone mistakes you for someone else",
    "You break a religious taboo",
    "You inadvertently break a law",
    "You run into your enemy",
    "You run into your friend",
    "Your run into your parents; they nag you about your life choices",
    "Your mentor is in town on a strange errand",
    "You get caught in a riot",
    "You’re given a cursed gift by someone looking to get rid of it",
    "Someone slips an item into your pack",
    "Someone steals something from your pack",
    "Someone pleads with you to protect them from the person following them",
)

wilderness_twists = (
    "The water was a lot deeper than you first guessed",
    "The water was a lot shallower than you thought",
    "You find yourselves at the bottom of a steep ravine with a single way out",
    "You’re lost",
    "You’re not lost; you’re just thinking",
    "You arrive at a place that looks exactly like what you’re looking for, but it’s not the place you’re looking for",
    "You take a wrong turn into a familiar area, but something here has changed",
    "You’re caught in a torrential downpour",
    "A wildfire breaks out. Fire swirls around you",
    "You’re caught in a blizzard",
    "You’re caught in a rockslide",
    "An earthquake throws you off your feet",
    "You realize this is no cave",
)

twists_data = {
    "Adventure Prospecting Twists": adventuring_prospecting_twists,
    "Dungeon Twists": dungeon_twists,
    "Gear Twists": gear_twists,
    "Invocation Twists": invocation_twists,
    "Magic Twists": magic_twists,
    "Monster Twists": monster_twists,
    "Talking Twists": talking_twists,
    "Town Twists": town_twists,
    "Wilderness Twists": wilderness_twists,
}
