from random import choice
from .roll import roll

stat_arrays = {
    "1": (12, 9, 6),
    "2": (12, 6, 9),
    "3": (9, 12, 6),
    "4": (9, 6, 12),
    "5": (6, 12, 9),
    "6": (6, 9, 12),
}

occupations = {
    "STR": [
        (
            "Bare-knuckle boxer",
            "You know your trainer, a bookmaker, fans from all corners of society.",
        ),
        (
            "Peasant",
            "You know the local priest, a militia member, a servant in a aristocrat house.",
        ),
        (
            "Factory worker",
            "You know a union leader, a former revolutionary, a new worker.",
        ),
        (
            "Miner",
            "You know the family of a dead miner, a union member, a nurse.",
        ),
        (
            "Firefighter",
            "You know a doctor, a militia officer, a retired firefighter.",
        ),
        (
            "Gravedigger",
            "You know grieving families, a priest an undertaker.",
        ),
    ],
    "DEX": [
        (
            "Cook",
            "You know a restaurant owner, a rival, a farmer.",
        ),
        (
            "Chimney sweep",
            "You know a former burglar, servants of aristocrat houses.",
        ),
        (
            "Burglar",
            "You know a fence, a former revolutionary, a rival.",
        ),
        (
            "Knife-thrower",
            "You know a circus owner, a knife-maker, a stage magician.",
        ),
        (
            "Rat catcher",
            "You know homeless people, a pickpocket, a city hall clerk. You also own a big and vicious cat.",
        ),
        (
            "Dancer",
            "You know the opera director, fans among the aristocrats, a rival.",
        ),
    ],
    "INT": [
        (
            "Astronomer",
            "You know a colleague, a weird student, an aristocrat financing your research.",
        ),
        (
            "Librarian",
            "You know a teacher obsessed with the occult, book sellers, writers.",
        ),
        (
            "Doctor",
            "You know the hospital director, the head nurse, a patient you saved.",
        ),
        (
            "Alienist",
            "You know an asylum director, former patients, a Secret Police victim.",
        ),
        (
            "Journalist",
            "You know a fellow journalist, a censor, informants.",
        ),
        (
            "Writer",
            "You know a publisher, a librarian, an aristocrat that sponsors you.",
        ),
    ],
}

abilities = ("STR", "DEX", "INT")

teachers = {
    1: "A priest",
    2: "A priest",
    3: "A revolutionary",
    4: "A revolutionary",
    5: "An aristocrat",
    6: "You're self-taught",
}

winter_revolution_answers = (
    "Your father was hanged by the army.",
    "Your mother was exiled in the White Forest.",
    "Your family was killed in a revolutionary bombing.",
    "One of your sibling was tortured by the Secret Police.",
    "You’ve spent one year in a labor camp.",
    "You were beat up by revolutionaries.",
    "You were shot by the army during a demonstration.",
    "Your family died in a labor camp.",
    "You beat up an aristocrat. Badly.",
    "You consciously avoided to take part in these unfortunate events. A decision that has costed you a few friendships.",
    "You were arrested and tortured by the Secret Police.",
    "You took part in a bombing that killed several civilians.",
    "You had to denounce fellow revolutionaries to protect family members.",
    "You saw Secret Police members get devoured by a monster in a back alley. No one believed you.",
    "You saved the life of an aristocrat from being mugged.",
    "You killed a soldier during a demonstration.",
    "Half your friends were exiled to the White Forest.",
    "You had to choose between saving a soldier or a revolutionary from a fire. Who did you choose?",
    "You were part of the group that made a whole factory explode. The Secret Police is still looking for the culprits.",
    "You killed a Secret Police officer to avoid arrest. It was blamed on another person who was hanged.",
)

what_almost_killed_you_answers = (
    "A stabbing in a back alley.",
    "The steelpox, part of your skin looks like metal now.",
    "Several gunshots by highwaymen.",
    "Surgical error.",
    "Poison in your tea.",
    "Pneumonia while in jail.",
    "A bombing in your favorite restaurant.",
    "A mine accident.",
    "Axe attack by a maniac.",
    "Falling off a mountain.",
    "A hanging canceled at the last minute.",
    "A fire in your building.",
    "A hunting accident involving aristocrats.",
    "A train accident.",
    "A gun duel with a jealous lover.",
    "Fear-induced heart attack.",
    "A beating by the Secret police.",
    "Shipwrecked.",
    "An experimental drug.",
    "A monster but no one believes you.",
)

weapon_choices = {
    2: "A sawed-off scattergun (+2, Blast) given to you by a revolutionary.",
    3: "An army rifle (+2) stolen during the Winter Revolution.",
    4: "A hunting rifle (+2) that seen a lot of use.",
    5: "A pistol (+1) that belonged to a Tsar’s bodyguard.",
    6: "A revolver (+1) found on a Secret Police agent’s corpse.",
    7: "A dueling pistol (+1) hidden by your grand-parents.",
    8: "A dueling rapier (+1).",
    9: "A rusted saber (+1) you found in an attic.",
    10: "A hunting knife your parents gave you.",
    11: "A hussar’s whip (damages INT instead of STR).",
    12: "A kitchen knife.",
}
male_first_names = (
    "Aleksey",
    "Maximilian",
    "Evgeny",
    "Stepan",
    "Nils",
    "Anton",
    "Konstantin",
    "Valentine",
    "Ivan",
    "Pyotr",
    "Nikolai",
    "Emmanuel",
    "Niel",
    "Andrei",
    "Yuri",
    "Irakli",
    "Mark",
    "Gustav",
    "Makhmud",
    "Suleyman",
    "Georgy",
    "Rasul",
    "Sharof",
    "Daniil",
    "Lado",
    "Chinghiz",
    "Ardalion",
    "Igor",
    "Malik",
    "Vardan",
    "Sergey",
    "Emilian",
    "Jabbor",
    "Matus",
    "Näcip",
    "Vakhtang",
    "Lev",
    "Roman",
    "Kuzma",
    "Bayken",
    "Zair",
    "Martiros",
    "Alla",
    "Benjamin",
    "Mykola",
    "Gavriil",
    "Zinovie",
    "Isaak",
    "Antanas",
    "Grigol",
    "Berdi",
    "Gennady",
    "Oskar",
    "Firuz",
    "Levko",
    "Abdulla",
    "Pavel",
    "Niyazi",
    "Gamzat",
    "Oles",
    "Gara",
    "Ilya",
    "Anatoly",
    "Komil",
    "Petrus",
    "Yustin",
    "Gerbert",
    "Vitaly",
    "Sobir",
    "Andronik",
    "Aksel",
    "Rashid",
    "Bagrat",
    "Ion",
    "Kerim",
    "Yukhym",
    "Arkhyp",
    "Leon",
    "Endel",
    "Justas",
    "Artyom",
    "Piotr",
    "Lev",
    "Karl",
    "Mustai",
    "Victor",
    "Armen",
    "Kirill",
    "Lazar",
    "Evsei",
    "Gerasim",
    "Luka",
    "Farman",
    "Kandrat",
    "Frol",
    "Tahir",
    "Janos",
    "Kaarel",
    "Johan",
    "Izzat",
)
female_first_names = (
    "Lidya",
    "Tursunoy",
    "Sevil",
    "Zuurakan",
    "Yevheniia",
    "Tamara",
    "Maya",
    "Natalia",
    "Katerina",
    "Vija",
    "Veriko",
    "Zamina",
    "Serafima",
    "Galina",
    "Irina",
    "Nadezhda",
    "Raïssa",
    "Elena",
    "Maria",
    "Pasha",
    "Zamara",
    "Faina",
    "Vera",
    "Shamama",
    "Leila",
    "Zoya",
    "Kerimbubu",
    "Lyudmila",
    "Alla",
    "Alina",
    "Tatiana",
    "Zulfiya",
    "Antonina",
    "Bella",
    "Nina",
    "Liubov",
    "Sofia",
    "Lia",
    "Sa’diniso",
    "Rufina",
    "Anya",
    "Muharram",
    "Khadicha",
    "Marina",
    "Sorojon",
    "Malika",
    "Olga",
    "Claudia",
    "Julia",
    "Rozetta",
    "Kira",
    "Vitalia",
    "Ilarya",
    "Zoe",
    "Elmira",
    "Anna",
    "Sardana",
    "Albina",
    "Larisa",
    "Darya",
    "Marietta",
    "Polina",
    "Svetlana",
    "Zalpa",
    "Oksana",
    "Elvira",
    "Ksenia",
    "Viktoria",
    "Sabina",
    "Zarifa",
    "Gulsum",
    "Inesa",
    "Mu’azzama",
    "Poliksena",
    "Nora",
    "Akilina",
    "Alena",
    "Khiuaz",
    "Glafira",
    "Maguba",
    "Anastasia",
    "Kassandra",
    "Rosalia",
    "Aurora",
    "Cecilia",
    "Sholpan",
    "Katya",
    "Lena",
    "Valeria",
    "Milena",
    "Anoushka",
    "Ludmila",
    "Ruslana",
    "Zhenya",
    "Diana",
    "Regina",
    "Saida",
    "Anita",
    "Flora",
    "Masha",
)
last_names = (
    "Yefimov",
    "Yakushkin",
    "Borisov",
    "Alyokhin",
    "Runeberg",
    "Kozlov",
    "Dolgoruki",
    "Malinski",
    "Zagorsky",
    "Kiprensky",
    "Gorbunov",
    "Chokhov",
    "Zarov",
    "Abakovsky",
    "Isaev",
    "Goravsky",
    "Kuznetsov",
    "Lavochkin",
    "Novoz",
    "Ekimov",
    "Nikolaev",
    "Samarov",
    "Zeitlin",
    "Rylov",
    "Murashko",
    "Vitayev",
    "Galitzine",
    "Voronov",
    "Antokolsky",
    "Elmanov",
    "Golovin",
    "Nomis",
    "Benardos",
    "Amelin",
    "Zakharov",
    "Golubkin",
    "Harlamov",
    "Petrov",
    "Volnukhin",
    "Laikmaa",
    "Tuganov",
    "Makarov",
    "Firsov",
    "Kovalyov",
    "Vasnetsov",
    "Pymonenko",
    "Storozhenko",
    "Yelagina",
    "Rudenko",
    "Tanfilyev",
    "Bobrin",
    "Vorobieff",
    "Sokolov",
    "Golitsyn",
    "Molchanov",
    "Naryshkin",
    "Ostrovsky",
    "Khan",
    "Makovsky",
    "Kharitonov",
    "Yegorov",
    "Falk",
    "Golubev",
    "Voevodin",
    "Lubimov",
    "Uvarov",
    "Drozdov",
    "Yakovlev",
    "Iversen",
    "Aspidov",
    "Surikov",
    "Burachek",
    "Korsakov",
    "Krychevsky",
    "Vasilevsky",
    "Karelin",
    "Banzarov",
    "Tarasov",
    "Massonius",
    "Velikanof",
    "Babanin",
    "Malsag",
    "Rabus",
    "Vladimirov",
    "Borodin",
    "Pukhov",
    "Larka",
    "Baikov",
    "Volkov",
    "Milev",
    "Khozin",
    "Aspelin",
    "Stupin",
    "Buzinsky",
    "Kostandi",
    "Horawki",
    "Belkin",
    "Ascania",
    "Serov",
    "Shevshenko",
)


class Character:
    def __init__(self, stat_array_nb, ability_to_raise, gender="Male"):
        self.STR, self.DEX, self.INT = stat_arrays.get(stat_array_nb)
        # add 1d6 to an ability of the player's choice
        setattr(self, ability_to_raise, getattr(self, ability_to_raise) + roll("1d6"))
        self.defense = roll("1d6")
        self.violence = "d4"
        # get the highest ability score
        char_abilities = {ability: getattr(self, ability) for ability in abilities}
        highest_ability_score = max(list(char_abilities.values()))
        rev_abilities = {v: k for k, v in char_abilities.items()}
        highest_ability = rev_abilities.get(highest_ability_score)
        # set the occupation
        self.occupation_name, self.occupation_description = choice(
            occupations.get(highest_ability)
        )
        # literacy and location
        if highest_ability in ("STR", "DEX"):
            self.who_taught_you_to_read = teachers.get(roll("1d6"))
            self.living_area = choice(("The Workers District", "The Port District"))
        else:
            self.who_taught_you_to_read = (
                "You went through school and received an academic instruction."
            )
            self.living_area = choice(("The Fortress District", "The Star District"))

        self.winter_revolution_answer = choice(winter_revolution_answers)
        self.what_almost_killed_you_answer = choice(what_almost_killed_you_answers)
        self.age = roll("3d6") + 20
        self.weapon = weapon_choices.get(self.defense + roll("1d6"))
        if gender == "Male":
            self.first_name = choice(male_first_names)
        else:
            self.first_name = choice(female_first_names)
        self.last_name = choice(last_names)
