from random import choice, randint
from gradientdescent.dice import get_key

addresses = {
    1: "Prospect (main street)",
    2: "Place",
    3: "Square",
    7: "Lane",
    16: "Street",
    17: "Garden",
    18: "Canal",
    19: "Bridge",
    20: "Alley",
}

bars = (
    "Writer’s Block",
    "Icebreaker",
    "Hollow Pine",
    "Red Elk",
    "Dreamhouse",
    "Hangover",
    "Glass Forest",
    "Fox & Wolf",
    "Lighthouse",
    "Black Candle",
    "Seagull",
    "Queen of Spades",
    "Summer memories",
    "Golden Orchard",
    "Forgotten Hussar",
    "Nasty Spirits",
    "Precipice",
    "Silent Giant",
    "Clever Bear",
    "Frost Rainbow",
)

street_names = (
    "Azure",
    "Agartha",
    "Jade",
    "Belgorod",
    "Smoke",
    "Birch",
    "Commune",
    "Pine",
    "Hangman",
    "White forest",
    "Harvesters",
    "Blizzard",
    "Hope",
    "Compass",
    "Ironworks",
    "Feather",
    "Leonova",
    "Volunteers",
    "Lost battalion",
    "Konstantin II",
    "Red Axe",
    "Union",
    "Mieville",
    "Oath",
    "Brazier",
    "Dead Hunter",
    "Labor",
    "Flood",
    "Steelworkers",
    "Emerald",
    "Red Sails",
    "1st Dragoon",
    "Devouring Ocean",
    "Pravda",
    "Rainbow",
    "Butcher",
    "Plague",
    "Victory",
    "Tundra",
    "Alexandrovna",
    "Mosaic",
    "Poor Oleg",
    "Bullet",
    "Mad Sailor",
    "Firing Squad",
    "Doctor Titov",
    "Veteran",
    "2nd Nurse Corp",
    "Gray Owl",
    "Dog",
    "Lavender",
    "Thunder",
    "Salamander",
    "Coal",
    "Red fox",
    "Dyshka Sisters",
    "Golden Larch",
    "Shrapnel",
    "Red Ink",
    "Elk",
    "Last war",
    "Silver Shore",
    "Vanguard",
    "Red Wolf",
    "Judge Vladimir",
    "Blackfish",
    "Printing Press",
    "Martyr",
    "Wormwood",
    "Cold Iron",
    "Frost",
    "Miners",
    "Steam",
    "Fisher",
    "Bastion",
    "Great famine",
    "Church",
    "Barricade",
    "Mirror",
    "Sokol",
    "Renaissance",
    "Shipyard",
    "April 12th",
    "Ghost",
    "Remembrance",
    "Surgeon",
    "Rabbit",
    "Moss",
    "Green",
    "Captain Ulyanov",
    "Red Castle",
    "Sawmill",
    "Watchmaker",
    "Progress",
    "Molotov",
    "Winter Uprising",
    "Revolution",
    "Gold",
    "Friendship",
    "Dagger",
)


def gen_address():
    number = randint(1, 100)
    street_type = addresses[get_key(randint(1, 20), addresses)]
    name = choice(street_names)
    return f"{number}, {name} {street_type}."


def get_bar_name():
    return f"We'll meet at the {choice(bars)}."
