ARMOR = (
    ("Shield (+1 Armor)", 10),
    ("Helmet (+1 Armor)", 15),
    ("Leather Jacket (1 Armor)", 20),
    ("Chainmail (2 Armor, bulky)", 40),
    ("Plate (3 Armor, bulky)", 60),
)
WEAPONS = (
    ("Dagger, Cudgel, Sickle, Staff, etc. (d6 damage)", 5),
    ("Spear, Sword, Mace, Axe, Flail, etc. (d8 damage)", 10),
    ("Halberd, War Hammer, Longsword, etc. (d10 damage, bulky)", 20),
    ("Sling (d4 damage)", 5),
    ("Bow (d6 damage, bulky)", 20),
    ("Crossbow (d8 damage, bulky)", 30),
)


GEAR_TOOLS = (
    ("Bellows", 10),
    ("Bedroll", 5),
    ("Bucket", 5),
    ("Caltrops", 10),
    ("Cart (+4 Slots, bulky)", 30),
    ("Chain (10ft)", 10),
    ("Chalk", 1),
    ("Crowbar", 10),
    ("Drill (Manual)", 10),
    ("Fire Oil", 10),
    ("Fishing Rod", 10),
    ("Glue", 5),
    ("Grappling Hook", 25),
    ("Hammer", 5),
    ("Holy Water", 5),
    ("Horse (+4 Slots)", 75),
    ("Hourglass", 50),
    ("Incense", 10),
    ("Lantern & Oil", 10),
    ("Lockpicks", 25),
    ("Manacles", 10),
    ("Metal File", 5),
    ("Net", 10),
    ("Pick", 10),
    ("Pulley", 10),
    ("Pole (10ft)", 5),
    ("Quill & Ink", 10),
    ("Rations (three day's worth)", 10),
    ("Rope (25ft)", 5),
    ("Saw", 5),
    ("Sack", 5),
    ("Shovel", 5),
    ("Spiked Boots", 5),
    ("Spyglass", 40),
    ("Tar", 10),
    ("Torch", 1),
)
