mishaps = {
    2: "You cannot Cast Spells for [DICE] hours, and any attempts to manipulate magic will fail.",
    3: "For the next 24 hours, when Casting Spells you suffer a Fatigue on a roll of 3-6.",
    4: "There is a chain reaction to the spell; the GM will tell how. Suffer an additional Fatigue.",
    5: "The Spell’s effects are reversed; the GM will tell you how. Take an additional Fatigue.",
    6: "Any objects in your Inventory that are not made of metal instantly combust. From now on you are immune to fire for short bursts.",
    7: "You are Deprived. After recovery, Roll d6. If the total is higher than your max HP, take the new result.",
    8: "You take [DICE] MIND Damage when Casting Spells for the next 24 hours. Afterwards Roll 3d6, if the result is higher than your MIND, swap it.",
    9: "The spell turns your skin a dark shade of purple, and makes you invisible in the moonlight. Your eyes however glow a bright yellow at night.",
    10: "You become insubstantial for [DICE] hours as your spirit leaves your body, which remains unconscious. You can fly and pass through walls, but not touch anything. Also, no one can see or hear you through mundane means.",
    11: "You suffer horrible arcane burns; lose [DICE] MIND. From now on you can add +1 Power to a Spell (use a die of a different color). If it results in a 4-6 you lose 1 MIND.",
    12: "The spell backfires; you lose 1 Inventory Slot (scratch it off your sheet). You are now surrounded by a magical essence that provides +1 Armor (limits still apply).",
    13: "Your Grimoire is damaged and unusable. Creating a new Grimoire from its remains restores the original spells as well.",
    14: "Instead of Fatigue, the spell causes magical tumors to fill their respective Slots. They can only be removed by a specialized healer.",
    15: "Arcane energies wreck your body as a piece of your soul is transferred into your Grimoire. You lose half your MIND (rounded down). Your Grimoire now appears in any form you wish and takes no Slots. It cannot be destroyed except by your own death, and vice-versa.",
    16: "You permanently lose [DICE] BODY as the spell interacts with nearby plant life, which rips out of the earth and fuses against your skin. You have +1 Armor, although fire does +d12 Bonus Damage against you. You can only feed by photosynthesis.",
    17: "Large hideous wings sprout from your back, ripping through whatever you are wearing. You gain [DICE] BODY and can fly. You cannot wear armor or a backpack, and have only 5 Inventory Slots.",
    18: "One of your hands becomes fused with your Grimoire. You can never let go of it, however it only takes up 1 Inventory Slot. You can fire a bolt of arcane energy from that hand that deals d6 Damage. If your hand is cut off, you can never Cast Spells again.",
    19: "An extra-planar deity senses your arcane power (ask the GM which deity).  You are now linked, and can call on it for aid. It can likewise ask you for help, and punish you for non-compliance. Good luck.",
    20: "You create an exact duplicate of yourself. One grows older while the other grows younger. Both age at the rate of 1 year per day. Your thoughts are joined, and if one dies so does the other. Only magical aid will restore you; afterward add +1d6 to each Attribute Score.",
    21: "You have become Elemental. Create a True Name for yourself. Magical energies surround you at all times, and mundane attacks against you are Impaired. If someone learns your True Name, they can control you. Other Elementals will come for you.",
}
