# Generated by Django 4.2.4 on 2026-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "creature_type",
                    models.CharField(
                        choices=[
                            (1, "Biological"),
                            (2, "Synthetic"),
                            (3, "Psychic"),
                            (4, "Fungal"),
                            (5, "Mineral"),
                            (6, "Hypergeometric"),
                            (7, "Outsider"),
                        ],
                        max_length=1,
                    ),
                ),
                ("LVL", models.IntegerField()),
                ("HP", models.IntegerField()),
                ("AV", models.IntegerField()),
                ("ML", models.IntegerField()),
                ("Encountered", models.IntegerField()),
                ("ATK", models.CharField(blank=True, max_length=250)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
