# Generated by Django 4.2.4 on 2026-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaarn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creature",
            name="Encountered",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="creature",
            name="creature_type",
            field=models.CharField(
                choices=[
                    ("1", "Biological"),
                    ("2", "Synthetic"),
                    ("3", "Psychic"),
                    ("4", "Fungal"),
                    ("5", "Mineral"),
                    ("6", "Hypergeometric"),
                    ("7", "Outsider"),
                ],
                max_length=1,
            ),
        ),
    ]
