nature_land = {
    "spark_1_name": "Character",
    "spark_2_name": "Landscape",
    "spark_1": [
        "Barren",
        "Dry",
        "Grey",
        "Sparse",
        "Sharp",
        "Teeming",
        "Still",
        "Soft",
        "Overgrown",
        "Vivid",
        "Sodden",
        "Lush",
    ],
    "spark_2": [
        "Marsh",
        "Heath",
        "Crags",
        "Peaks",
        "Forest",
        "Valley",
        "Hills",
        "Meadow",
        "Bog",
        "Lakes",
        "Glades",
        "Plain",
    ],
}

nature_sky = {
    "spark_1_name": "Tone",
    "spark_2_name": "Texture",
    "spark_1": [
        "Glittering",
        "Violet",
        "Sapphire",
        "Pale",
        "Fiery",
        "Ivory",
        "Slate",
        "Pink",
        "Golden",
        "Bloody",
        "Bright",
        "Inky",
    ],
    "spark_2": [
        "Aurora",
        "Haze",
        "Marble",
        "Glow",
        "Billows",
        "Swirl",
        "Streaks",
        "Dapple",
        "Rays",
        "Pillars",
        "Shimmer",
        "Swells",
    ],
}


nature_water = {
    "spark_1_name": "Tone",
    "spark_2_name": "Texture",
    "spark_1": [
        "Crystal",
        "Teal",
        "Abyss",
        "Mucky",
        "Cobalt",
        "Verdant",
        "Frosted",
        "Dark",
        "Verdigris",
        "Silver",
        "Emerald",
        "Jade",
    ],
    "spark_2": [
        "Silk",
        "Ripples",
        "Pearlescent",
        "Churn",
        "Froth",
        "Mirror",
        "Surge",
        "Glass",
        "Surf",
        "Rapids",
        "Spray",
        "Bubbles",
    ],
}

nature_weather = {
    "spark_1_name": "Description",
    "spark_2_name": "Element",
    "spark_1": [
        "Gentle",
        "Fleeting",
        "Persistent",
        "Bright",
        "Thin",
        "Cool",
        "Hot",
        "Solid",
        "Dull",
        "Faint",
        "Abundant",
        "Harsh",
    ],
    "spark_2": [
        "Rain",
        "Gusts",
        "Cloud",
        "Sunlight",
        "Mist",
        "Humidity",
        "Thunder",
        "Dust",
        "Warmth",
        "Drizzle",
        "Breeze",
        "Fog",
    ],
}

nature_flora = {
    "spark_1_name": "Nature",
    "spark_2_name": "Form",
    "spark_1": [
        "Aromatic",
        "Ashen",
        "Blooming",
        "Twisted",
        "Towering",
        "Fruitful",
        "Stinging",
        "Vibrant",
        "Brittle",
        "Thorny",
        "Reeds",
        "Resinous",
    ],
    "spark_2": [
        "Grasses",
        "Heather",
        "Shrubs",
        "Brambles",
        "Canopy",
        "Ferns",
        "Trunks",
        "Vines",
        "Conifers",
        "Saplings",
        "Sturdy",
        "Roots",
    ],
}

nature_fauna = {
    "spark_1_name": "Nature",
    "spark_2_name": "Form",
    "spark_1": [
        "Watchful",
        "Helpful",
        "Graceful",
        "Loud",
        "Mischievous",
        "Deceitful",
        "Felines",
        "Placid",
        "Beautiful",
        "Mighty",
        "Fowl",
        "Aloof",
    ],
    "spark_2": [
        "Ungulates",
        "Songbirds",
        "Canines",
        "Rodents",
        "Amphibians",
        "Insects",
        "Enlightening",
        "Reptiles",
        "Hawks",
        "Mustelids",
        "Hostile",
        "Bears",
    ],
}

nature_feature = {
    "spark_1_name": "Nature",
    "spark_2_name": "Form",
    "spark_1": [
        "Buried",
        "Colourful",
        "Adorned",
        "Spiked",
        "Split",
        "Entombed",
        "Reflective",
        "Veiled",
        "Hot",
        "Drowned",
        "Arch",
        "Isolated",
    ],
    "spark_2": [
        "Brook",
        "Seat",
        "Pit",
        "Cave",
        "Monolith",
        "Mound",
        "Cairn",
        "Pond",
        "Waterfall",
        "Spring",
        "Desecrated",
        "Henge",
    ],
}

nature_wonder = {
    "spark_1_name": "Theme",
    "spark_2_name": "Element",
    "spark_1": [
        "Pleasure",
        "Secrets",
        "Prophecy",
        "Healing",
        "Desire",
        "Memory",
        "Death",
        "Strength",
        "Plants",
        "Pain",
        "Water",
        "Time",
    ],
    "spark_2": [
        "Light",
        "Flames",
        "Stones",
        "Beasts",
        "Sparks",
        "Trails",
        "Mist",
        "Colours",
        "Temptation",
        "Wind",
        "Regret",
        "Shadows",
    ],
}

nature_otherworld = {
    "spark_1_name": "Character",
    "spark_2_name": "Landscape",
    "spark_1": [
        "Acidic",
        "Black",
        "Smoke",
        "Frozen",
        "Dead",
        "Broken",
        "Colossal",
        "Living",
        "Burning",
        "Sludge",
        "Island",
        "Sweet",
    ],
    "spark_2": [
        "Flats",
        "Labyrinth",
        "Ruins",
        "Stairs",
        "Desert",
        "Craters",
        "Cavern",
        "Jungle",
        "Dunes",
        "Tunnels",
        "White",
        "Mountain",
    ],
}

template_spark = {
    "spark_1_name": "",
    "spark_2_name": "",
    "spark_1": [],
    "spark_2": [],
}

template_spark = {
    "spark_1_name": "",
    "spark_2_name": "",
    "spark_1": [],
    "spark_2": [],
}

spark_tables = {
    "Nature - Land": nature_land,
    "Nature - Sky": nature_sky,
    "Nature - Water": nature_water,
    "Nature - Weather": nature_weather,
    "Nature - Flora": nature_flora,
    "Nature - Fauna": nature_fauna,
    "Nature - Feature": nature_feature,
    "Nature - Wonder": nature_wonder,
    "Nature - Otherworld": nature_otherworld,
}
