nature_land = {
    "spark_1_name": "Character",
    "spark_2_name": "Landscape",
    "spark_1": [
        "Barren",
        "Dry",
        "Grey",
        "Sparse",
        "Sharp",
        "Teeming",
        "Still",
        "Soft",
        "Overgrown",
        "Vivid",
        "Sodden",
        "Lush",
    ],
    "spark_2": [
        "Marsh",
        "Heath",
        "Crags",
        "Peaks",
        "Forest",
        "Valley",
        "Hills",
        "Meadow",
        "Bog",
        "Lakes",
        "Glades",
        "Plain",
    ],
    "title": "Land",
}

nature_sky = {
    "spark_1_name": "Tone",
    "spark_2_name": "Texture",
    "title": "Sky",
    "spark_1": [
        "Glittering",
        "Violet",
        "Sapphire",
        "Pale",
        "Fiery",
        "Ivory",
        "Slate",
        "Pink",
        "Golden",
        "Bloody",
        "Bright",
        "Inky",
    ],
    "spark_2": [
        "Aurora",
        "Haze",
        "Marble",
        "Glow",
        "Billows",
        "Swirl",
        "Streaks",
        "Dapple",
        "Rays",
        "Pillars",
        "Shimmer",
        "Swells",
    ],
}


nature_water = {
    "title": "Water",
    "spark_1_name": "Tone",
    "spark_2_name": "Texture",
    "spark_1": [
        "Crystal",
        "Teal",
        "Abyss",
        "Mucky",
        "Cobalt",
        "Verdant",
        "Frosted",
        "Dark",
        "Verdigris",
        "Silver",
        "Emerald",
        "Jade",
    ],
    "spark_2": [
        "Silk",
        "Ripples",
        "Pearlescent",
        "Churn",
        "Froth",
        "Mirror",
        "Surge",
        "Glass",
        "Surf",
        "Rapids",
        "Spray",
        "Bubbles",
    ],
}

nature_weather = {
    "title": "Weather",
    "spark_1_name": "Description",
    "spark_2_name": "Element",
    "spark_1": [
        "Gentle",
        "Fleeting",
        "Persistent",
        "Bright",
        "Thin",
        "Cool",
        "Hot",
        "Solid",
        "Dull",
        "Faint",
        "Abundant",
        "Harsh",
    ],
    "spark_2": [
        "Rain",
        "Gusts",
        "Cloud",
        "Sunlight",
        "Mist",
        "Humidity",
        "Thunder",
        "Dust",
        "Warmth",
        "Drizzle",
        "Breeze",
        "Fog",
    ],
}

nature_flora = {
    "title": "Flora",
    "spark_1_name": "Nature",
    "spark_2_name": "Form",
    "spark_1": [
        "Aromatic",
        "Ashen",
        "Blooming",
        "Twisted",
        "Towering",
        "Fruitful",
        "Stinging",
        "Vibrant",
        "Brittle",
        "Thorny",
        "Sturdy",
        "Resinous",
    ],
    "spark_2": [
        "Grasses",
        "Heather",
        "Shrubs",
        "Brambles",
        "Canopy",
        "Ferns",
        "Trunks",
        "Vines",
        "Conifers",
        "Saplings",
        "Reeds",
        "Roots",
    ],
}

nature_fauna = {
    "title": "Fauna",
    "spark_1_name": "Nature",
    "spark_2_name": "Form",
    "spark_1": [
        "Watchful",
        "Helpful",
        "Graceful",
        "Loud",
        "Mischievous",
        "Deceitful",
        "Felines",
        "Placid",
        "Beautiful",
        "Mighty",
        "Hostile",
        "Aloof",
    ],
    "spark_2": [
        "Ungulates",
        "Songbirds",
        "Canines",
        "Rodents",
        "Amphibians",
        "Insects",
        "Enlightening",
        "Reptiles",
        "Hawks",
        "Mustelids",
        "Fowl",
        "Bears",
    ],
}

nature_feature = {
    "title": "Feature",
    "spark_1_name": "Nature",
    "spark_2_name": "Form",
    "spark_1": [
        "Buried",
        "Colourful",
        "Adorned",
        "Spiked",
        "Split",
        "Entombed",
        "Reflective",
        "Veiled",
        "Hot",
        "Drowned",
        "Desecrated",
        "Isolated",
    ],
    "spark_2": [
        "Brook",
        "Seat",
        "Pit",
        "Cave",
        "Monolith",
        "Mound",
        "Cairn",
        "Pond",
        "Waterfall",
        "Spring",
        "Arch",
        "Henge",
    ],
}

nature_wonder = {
    "title": "Wonder",
    "spark_1_name": "Theme",
    "spark_2_name": "Element",
    "spark_1": [
        "Pleasure",
        "Secrets",
        "Prophecy",
        "Healing",
        "Desire",
        "Memory",
        "Death",
        "Strength",
        "Plants",
        "Pain",
        "Regret",
        "Time",
    ],
    "spark_2": [
        "Light",
        "Flames",
        "Stones",
        "Beasts",
        "Sparks",
        "Trails",
        "Mist",
        "Colours",
        "Temptation",
        "Wind",
        "Water",
        "Shadows",
    ],
}

nature_otherworld = {
    "title": "Otherworld",
    "spark_1_name": "Character",
    "spark_2_name": "Landscape",
    "spark_1": [
        "Acidic",
        "Black",
        "Smoke",
        "Frozen",
        "Dead",
        "Broken",
        "Colossal",
        "Living",
        "Burning",
        "Sludge",
        "White",
        "Sweet",
    ],
    "spark_2": [
        "Flats",
        "Labyrinth",
        "Ruins",
        "Stairs",
        "Desert",
        "Craters",
        "Cavern",
        "Jungle",
        "Dunes",
        "Tunnels",
        "Island",
        "Mountain",
    ],
}

civilisation_holding = {
    "title": "Holding",
    "spark_1_name": "Style",
    "spark_2_name": "Feature",
    "spark_1": [
        "Dark",
        "Ruined",
        "Hostile",
        "Ancient",
        "Ornate",
        "Pristine",
        "Fortified",
        "Unfinished",
        "Welcoming",
        "Proud",
        "Bright",
        "Wild",
    ],
    "spark_2": [
        "Turrets",
        "Tower",
        "Wall",
        "Battlements",
        "Citadel",
        "Gate",
        "Spire",
        "Dome",
        "Beacons",
        "Bridge",
        "Pillars",
        "Moat",
    ],
}

civilisation_bailey = {
    "title": "Bailey",
    "spark_1_name": "Style",
    "spark_2_name": "Feature",
    "spark_1": [
        "Filthy",
        "Abandoned",
        "Joyous",
        "Sophisticated",
        "Majestic",
        "Industrious",
        "Hallowed",
        "Rustic",
        "Solemn",
        "Bustling",
        "Immaculate",
        "Humble",
    ],
    "spark_2": [
        "Marketplace",
        "Temple",
        "Forge",
        "Library",
        "Fountain",
        "Forum",
        "Tomb",
        "Garden",
        "Hall",
        "Workshops",
        "Arena",
        "Garrison",
    ],
}

civilisation_keep = {
    "title": "Keep",
    "spark_1_name": "Centrepiece",
    "spark_2_name": "Decoration",
    "spark_1": [
        "Hearth",
        "Throne",
        "Musicians",
        "Pool",
        "Advisers",
        "Shrine",
        "Table",
        "Reliquary",
        "Cauldron",
        "Chandelier",
        "Guards",
        "Servants",
    ],
    "spark_2": [
        "Antlers",
        "Silver",
        "Heraldry",
        "Bones",
        "Flowers",
        "Scripture",
        "Jewels",
        "Wreaths",
        "Candles",
        "Fur",
        "Tapestries",
        "Shields",
    ],
}

civilisation_food = {
    "title": "Food",
    "spark_1_name": "Quality",
    "spark_2_name": "Type",
    "spark_1": [
        "Spiced",
        "Herbal",
        "Crunchy",
        "Sour",
        "Dry",
        "Salted",
        "Wet",
        "Fatty",
        "Chewy",
        "Sweet",
        "Mild",
        "Fermented",
    ],
    "spark_2": [
        "Fish",
        "Fruit",
        "Stew",
        "Mushrooms",
        "Pie",
        "Cheese",
        "Nuts",
        "Cake",
        "Porridge",
        "Bread",
        "Vegetable",
        "Meat",
    ],
}

civilisation_goods = {
    "title": "Goods",
    "spark_1_name": "Theme",
    "spark_2_name": "Type",
    "spark_1": [
        "Military",
        "Abundant",
        "Specialist",
        "Industrious",
        "Innovative",
        "Secretive",
        "Simple",
        "Strong",
        "Fine",
        "Lucky",
        "Decorated",
        "Traditional",
    ],
    "spark_2": [
        "Leather",
        "Stone",
        "Textile",
        "Livestock",
        "Mead",
        "Grain",
        "Tools",
        "Wood",
        "Pottery",
        "Metal",
        "Honey",
        "Herb",
    ],
}

civilisation_luxuries = {
    "title": "Luxuries",
    "spark_1_name": "Rarity",
    "spark_2_name": "Type",
    "spark_1": [
        "Antique",
        "Intricate",
        "Unique",
        "Scarce",
        "Hazardous",
        "Luminous",
        "Lost",
        "Esoteric",
        "Sacred",
        "Mythical",
        "Beautiful",
        "Flawless",
    ],
    "spark_2": [
        "Jewel",
        "Wine",
        "Spice",
        "Fragrance",
        "Silk",
        "Fur",
        "Artwork",
        "Sword",
        "Creature",
        "Ore",
        "Root",
        "Scripture",
    ],
}

civilisation_drama = {
    "title": "Drama",
    "spark_1_name": "Theme",
    "spark_2_name": "Detail",
    "spark_1": [
        "Betrayal",
        "Jealousy",
        "Rivalry",
        "Infidelity",
        "Coup",
        "Ambition",
        "Redemption ",
        "Revelation",
        "Wrath",
        "Greed",
        "Banishment",
        "Manipulation",
    ],
    "spark_2": [
        "Brawl",
        "Poison",
        "Oath",
        "Feast",
        "Letters",
        "Disguise",
        "Inheritance",
        "Assassin",
        "Family",
        "Alcohol",
        "Blackmail",
        "Gold",
    ],
}

civilisation_woe = {
    "title": "Woe",
    "spark_1_name": "Description",
    "spark_2_name": "Incident",
    "spark_1": [
        "Secretive",
        "Violent",
        "Looming",
        "Sudden",
        "Ongoing",
        "Mysterious",
        "Sanctioned",
        "Unseen",
        "Vast",
        "Escalating",
        "Concealed",
        "Prophecised",
    ],
    "spark_2": [
        "Disease",
        "Famine",
        "Raids",
        "Invasion",
        "Abduction",
        "Storm",
        "Fire",
        "Revolt",
        "Exodus",
        "Beast",
        "Killing",
        "Theft",
    ],
}

civilisation_news = {
    "title": "News",
    "spark_1_name": "Subject",
    "spark_2_name": "Mood",
    "spark_1": [
        "Duel",
        "Birth",
        "Market",
        "Trial",
        "Ritual",
        "Festival",
        "Tournament",
        "Performance",
        "Punishment",
        "Death",
        "Marriage",
        "Mercenaries",
    ],
    "spark_2": [
        "Pensive",
        "Joyous",
        "Content",
        "Divided",
        "Furious",
        "Sceptical",
        "Adoring",
        "Nostalgic",
        "Unified",
        "Bleak",
        "Solemn",
        "Optimistic",
    ],
}

people_appearance = {
    "title": "Appearance",
    "spark_1_name": "Physique",
    "spark_2_name": "Dress",
    "spark_1": [
        "Delicate",
        "Short",
        "Robust",
        "Hard",
        "Haggard",
        "Cold",
        "Warm",
        "Youthful",
        "Soft",
        "Sickly",
        "Tall",
        "Rough",
    ],
    "spark_2": [
        "Armoured",
        "Tattered",
        "Vibrant",
        "Crude",
        "Eclectic",
        "Traditional",
        "Comfortable",
        "Gaudy",
        "Drab",
        "Decorated",
        "Functional",
        "Elegant",
    ],
}

people_voice = {
    "title": "Voice",
    "spark_1_name": "Tone",
    "spark_2_name": "Manner",
    "spark_1": [
        "Whispering",
        "Soothing",
        "Smooth",
        "Flat",
        "Mumbled",
        "Weak",
        "Strong",
        "Hesitant",
        "Melodic",
        "Gravelly",
        "Erratic",
        "Booming",
    ],
    "spark_2": [
        "Formal",
        "Poetic",
        "Precise",
        "Intense",
        "Rambling",
        "Detached",
        "Passionate",
        "Terse",
        "Relaxed",
        "Blunt",
        "Boisterous",
        "Friendly",
    ],
}

people_personality = {
    "title": "Personality",
    "spark_1_name": "Demeanor",
    "spark_2_name": "Interest",
    "spark_1": [
        "Cautious",
        "Spiritual",
        "Intellectual",
        "Ambitious",
        "Serene",
        "Righteous",
        "Empathetic",
        "Unstable",
        "Prying",
        "Melancholic",
        "Cynical",
        "Rash",
    ],
    "spark_2": [
        "Fashion",
        "Botany",
        "History",
        "Gambling",
        "Animals",
        "Art",
        "Craft",
        "Music",
        "Cookery",
        "Fishing",
        "Hunting",
        "Stories",
    ],
}

people_relationship = {
    "title": "Relationship",
    "spark_1_name": "State",
    "spark_2_name": "Connection",
    "spark_1": [
        "Adoring",
        "Reluctant",
        "Secret",
        "Estranged",
        "Hateful",
        "Distant",
        "Harmonious",
        "Intimate",
        "Recent",
        "Sworn",
        "Tumultuous",
        "Resentful",
    ],
    "spark_2": [
        "Enemy",
        "Guardian",
        "Kin",
        "Friend",
        "Rival",
        "Lover",
        "Spouse",
        "Supporter",
        "Ally",
        "Successor",
        "Mentor",
        "Peer",
    ],
}

people_desire = {
    "title": "Desire",
    "spark_1_name": "Ambition",
    "spark_2_name": "Motive",
    "spark_1": [
        "Escape",
        "Wealth",
        "Status",
        "Knowledge",
        "Heirloom",
        "Mastery",
        "Marriage",
        "Truth",
        "Travel",
        "Power",
        "Security",
        "Forgiveness",
    ],
    "spark_2": [
        "Hatred",
        "Freedom",
        "Love",
        "Legacy",
        "Revenge",
        "Duty",
        "Fear",
        "Guilt",
        "Recognition",
        "Defiance",
        "Curiosity",
        "Recovery",
    ],
}

people_task = {
    "title": "Task",
    "spark_1_name": "Action",
    "spark_2_name": "Subject",
    "spark_1": [
        "Investigate",
        "Capture",
        "Destroy",
        "Transport",
        "Retrieve",
        "Mend",
        "Break",
        "Guard",
        "Aid",
        "Salvage",
        "Conceal",
        "Hunt",
    ],
    "spark_2": [
        "Knight",
        "Seer",
        "Vassals",
        "Livestock",
        "Monument",
        "Gold",
        "Ruin",
        "Animals",
        "Dwelling",
        "Holding",
        "Bridge",
        "Warband",
    ],
}

people_background = {
    "title": "Background",
    "spark_1_name": "Upbringing",
    "spark_2_name": "Memory",
    "spark_1": [
        "Deprived",
        "Pious",
        "Outcast",
        "Military",
        "Insular",
        "Drudgery",
        "Mercantile",
        "Feral",
        "Prestigious",
        "Academic",
        "Pampered",
        "Nomadic",
    ],
    "spark_2": [
        "War",
        "Migration",
        "Riding",
        "Study",
        "Exile",
        "Joy",
        "Sickness",
        "Escape",
        "Injury",
        "Friendship",
        "Execution",
        "Romance",
    ],
}

people_ailment = {
    "title": "Ailment",
    "spark_1_name": "Descriptor",
    "spark_2_name": "Symptom",
    "spark_1": [
        "Hidden",
        "Mild",
        "Intermittent",
        "Growing",
        "Medicated",
        "Constant",
        "Unexplained",
        "Diminishing",
        "Permanent",
        "Debilitating",
        "Obvious",
        "Denied",
    ],
    "spark_2": [
        "Insomnia",
        "Migraines",
        "Arthritis",
        "Nausea",
        "Fixation",
        "Blindness",
        "Deafness",
        "Melancholy",
        "Shaking",
        "Frailty",
        "Coughing",
        "Lethargy",
    ],
}

people_heraldry = {
    "title": "Heraldry",
    "spark_1_name": "Palette",
    "spark_2_name": "Symbol",
    "spark_1": [
        "Light",
        "Hot",
        "Earthy",
        "Rich",
        "Metallic",
        "Grey",
        "Jewelled",
        "Subdued",
        "Airy",
        "Cold",
        "Dark",
        "Brilliant",
    ],
    "spark_2": [
        "Beast",
        "Bird",
        "Fish",
        "Weapon",
        "Crown",
        "Tree",
        "Flower",
        "Bodypart",
        "Structure",
        "Ring",
        "Tool",
        "Star",
    ],
}

combat_soldier = {
    "title": "Soldier",
    "spark_1_name": "Quality",
    "spark_2_name": "Type",
    "spark_1": [
        "Mobile",
        "Reluctant",
        "Mounted",
        "Renowned",
        "Zealous",
        "Cowardly",
        "Heavy",
        "Bloodthirsty",
        "Fancy",
        "Fearsome",
        "Mercenary",
        "Conscript",
    ],
    "spark_2": [
        "Skirmisher",
        "Archer",
        "Scout",
        "Militia",
        "Guard",
        "Infiltrator",
        "Raider",
        "Veteran",
        "Infantry",
        "Rider",
        "Charger",
        "Knight",
    ],
}

combat_weapon = {
    "title": "Weapon",
    "spark_1_name": "Descriptor",
    "spark_2_name": "Feature",
    "spark_1": [
        "Short",
        "Pole",
        "Chain",
        "Barbed",
        "Forked",
        "Weighted",
        "Double",
        "Crossed",
        "Throwing",
        "Thin",
        "Long",
        "Curved",
    ],
    "spark_2": [
        "Blade",
        "Spear",
        "Axe",
        "Mace",
        "Cleaver",
        "Hammer",
        "Spike",
        "Hook",
        "Club",
        "Rod",
        "Fang",
        "Sword",
    ],
}

combat_manoeuvres = {
    "title": "Manoeuvres",
    "spark_1_name": "Action",
    "spark_2_name": "Intent",
    "spark_1": [
        "Feint",
        "Strike",
        "Boast",
        "Defend",
        "Negotiate",
        "Flurry",
        "Rush",
        "Taunt",
        "Jab",
        "Charge",
        "Onslaught",
        "Provoke",
    ],
    "spark_2": [
        "Demoralise",
        "Confuse",
        "Exploit",
        "Stall",
        "Relocate",
        "Observe",
        "Defeat",
        "Expose",
        "Surprise",
        "Stagger",
        "Weaken",
        "Intimidate",
    ],
}

combat_conflict = {
    "title": "Conflict",
    "spark_1_name": "Dispute",
    "spark_2_name": "Status",
    "spark_1": [
        "Border",
        "Religion",
        "Succession",
        "Resource",
        "Debt",
        "Theft",
        "Conquest",
        "Marriage",
        "Deceit",
        "Waterway",
        "Bloodfeud",
        "Betrayal",
    ],
    "spark_2": [
        "War",
        "Raids",
        "Animosity",
        "Truce",
        "Skirmishes",
        "Standoff",
        "Occupation",
        "Stalemate",
        "Blockade",
        "Tension",
        "Forgotten",
        "Negotiations",
    ],
}

combat_duel = {
    "title": "Duel",
    "spark_1_name": "Stipulation",
    "spark_2_name": "Twist",
    "spark_1": [
        "Joust",
        "Swords",
        "Partner",
        "Team",
        "Unarmoured",
        "Blood",
        "Death",
        "Surrender",
        "Judged",
        "Blunt",
        "Javelins",
        "Chained",
    ],
    "spark_2": [
        "Timed",
        "Pit",
        "Bridge",
        "Immobile",
        "Maze",
        "Archers",
        "Fire",
        "Beasts",
        "Mud",
        "Night",
        "Water",
        "Cage",
    ],
}

combat_battlefield = {
    "title": "Battlefield",
    "spark_1_name": "Feature",
    "spark_2_name": "Detail",
    "spark_1": [
        "River",
        "Ruins",
        "Hill",
        "Forest",
        "Lake",
        "Pass",
        "Farm",
        "Trail",
        "Bridge",
        "Wall",
        "Dwelling",
        "Outpost",
    ],
    "spark_2": [
        "Smoke",
        "Mud",
        "Flies",
        "Trenches",
        "Tower",
        "Boulders",
        "Flowers",
        "Streams",
        "Thorns",
        "Stink",
        "Ravine",
        "Tombs",
    ],
}

combat_deployment = {
    "title": "Deployment",
    "spark_1_name": "Style",
    "spark_2_name": "Formation",
    "spark_1": [
        "Aggressive",
        "Mobile",
        "Tight",
        "Deceptive",
        "Shielded",
        "Flexible",
        "Open",
        "Focused",
        "Dispersed",
        "Reinforced",
        "Defensive",
        "Rigid",
    ],
    "spark_2": [
        "Line",
        "Column",
        "Chevron",
        "Ranks",
        "Square",
        "Circle",
        "Flank",
        "Skirmish",
        "Block",
        "Square",
        "Wedge",
        "Scatter",
    ],
}

combat_strategy = {
    "title": "Strategy",
    "spark_1_name": "Plan",
    "spark_2_name": "Twist",
    "spark_1": [
        "Encircle",
        "Capture",
        "Assault",
        "Harass",
        "Pillage",
        "Ambush",
        "Overwhelm",
        "Blockade",
        "Divide",
        "Focus",
        "Counter",
        "Outlast",
    ],
    "spark_2": [
        "Darkness",
        "Reserves",
        "Diversion",
        "Betrayal",
        "Artillery",
        "Camouflage",
        "Bluff",
        "Delay",
        "Decoy",
        "Bait",
        "Sacrifice",
        "Fire",
    ],
}

combat_event = {
    "title": "Event",
    "spark_1_name": "Subject",
    "spark_2_name": "Event",
    "spark_1": [
        "Allies",
        "Morale",
        "Weather",
        "Terrain",
        "Strategy",
        "Animal",
        "Opportunists",
        "Deception",
        "Leader",
        "Loot",
        "Weapons",
        "Discipline",
    ],
    "spark_2": [
        "Collapse",
        "Attack",
        "Slaughter",
        "Stalemate",
        "Stall",
        "Falter",
        "Sabotage",
        "Scatter",
        "Charge",
        "Confusion",
        "Worsening",
        "Discovery",
    ],
}


spark_tables_by_theme = {
    "Nature": (
        nature_land,
        nature_sky,
        nature_water,
        nature_weather,
        nature_flora,
        nature_fauna,
        nature_feature,
        nature_wonder,
        nature_otherworld,
    ),
    "Civilisation": (
        civilisation_holding,
        civilisation_bailey,
        civilisation_keep,
        civilisation_food,
        civilisation_goods,
        civilisation_luxuries,
        civilisation_drama,
        civilisation_woe,
        civilisation_news,
    ),
    "People": (
        people_appearance,
        people_voice,
        people_personality,
        people_relationship,
        people_desire,
        people_task,
        people_background,
        people_ailment,
        people_heraldry,
    ),
    "Combat": (
        combat_soldier,
        combat_weapon,
        combat_manoeuvres,
        combat_conflict,
        combat_duel,
        combat_battlefield,
        combat_deployment,
        combat_strategy,
        combat_event,
    ),
}

from random import choice


class Spark:
    def __init__(self, table):
        self.title = table.get("title")
        self.spark_1_name = table.get("spark_1_name")
        self.spark_2_name = table.get("spark_2_name")
        self.left = choice(table["spark_1"])
        self.right = choice(table["spark_2"])
